




	function getaddglaccountParams(){
		var paramstr = new FormData();
		paramstr.append('accountnumber',document.getElementById('oreaglaaccountnumber').value);
		paramstr.append('description',document.getElementById('oreagladescription').value);
		paramstr.append('groupname',document.getElementById('oreaglagroupname').value);
		paramstr.append('accounttype',document.getElementById('oreaglaaccounttype').value);
	   return paramstr;
}
	function getaddglaccountP(){
		var paramstr = new FormData();
		paramstr.append('accountnumber',document.getElementById('oreaglaaccountnumber').value);
	   return paramstr;
}
	

const glacc_fields = [
    // `oreaglaaccountnumber`,
    `oreaglagroupname`,
    `oreaglaaccounttype`,
    `oreagladescription`,
    ]

// const errandadd =async()=>{
//     let deescp = ['VAULT',
//   'TELLER',
//   'TELLER 2',
//   'UBA MKD',
//   'PAGA BANK',
//   'FBN',
//   'UBA AGENCY',
//   'FURNITURE/FITTINGS',
//   'VEHICLES',
//   'LAND & BUILDING',
//   'PLANT & MACHINERY',
//   'OFFICE EQUIPMENT/SOFTWARE',
//   'NTB/BANK PLACEMENTS',
//   'INVESTMENT IN SHARES',
//   'BUSINESS INVESTMENTS',
//   'SHORT TERM INVESTMENT',
//   'STAFF LOAN',
//   'PERSONAL LOAN',
//   'OVERDRAFT',
//   'GROUP/CORPORATE LOAN',
//   'EDUCATION SUPPORT LOAN',
//   'BUSINESS SUPPORT LOAN',
//   'HIREPURCHASE',
//   'ADVANCE',
//   'CLASSIFIED DEBT',
//   'MONEY TRANSFER INCOMING',
//   'BVN & NIN LICENCE',
//   'CHEQUE BOOKS & STAMP',
//   'SAVINGS BOOKLET',
//   'STATIONERY IN STOCK',
//   'SUSPENSE A/C',
//   'PREPAYMENT',
//   'ACCRUED INT. RECIEVABLE',
//   'ONLINE SERVICE APP',
//   'SUNDRY DEBTORS',
//   'DAILY COLLECTION',
//   'PROFIT & LOSS A/C',
//   'SHARE CAPITAL',
//   'SHARE PREMIUM',
//   'GENERAL RESERVES',
//   'STATUTORY RESRVES',
//   'RETAINED PROFIT',
//   'CURRENT A/C',
//   'SAVINGS A/C',
//   'FIXED DEPOSITS',
//   'DEPOSIT FOR SHARE',
//   'DIVIDEND PAYABLE',
//   'STAFF RBSCH',
//   'INTEREST IN SUSPENSE',
//   'ACCRUED INT. PAYABLE',
//   'MONEY TRF OUTGOING',
//   'SUNDRY CREDITORS',
//   'BILLS PAYABLE',
//   'PAYE',
//   'CASHIER SURPLUS',
//   'PROVISION FOR BAD DEBTS',
//   'GENERAL PROVISION',
//   'PROVISION FOR TAX',
//   'ACCUMULATED DEPRECIATION',
//   'PROV. FOR DEP. VEHICLE',
//   'PROV FOR DEP F&F',
//   'PROV FOR DEP P&M',
//   'PROV FOR DEP LAND & B',
//   'PROV FOR DEP OFF EQUIP',
//   'ELECTRIC/SOLAR',
//   'FUEL/OIL',
//   'STATIONARIES',
//   'TRANSPORT/TRAVELLING',
//   'REPAIR/MAINTENACE',
//   'AGM/DIRECTORS EXPENSES',
//   'AUDIT EXPS',
//   'FEES/DUES/SUBSCRIPTIONS',
//   'SALARY',
//   'AIRTIME & DATA',
//   'POSTAGE/COMMUNICATION',
//   'MISCELLANOUS EXPS',
//   'INTEREST ON LOAN/HP',
//   'OTHER INTEREST RECIEVED',
//   'INCOME FROM BUSINESSES',
//   'CASH HANDLING CHG',
//   'SMS CHG',
//   'COT',
//   'LOAN APPLICATION FEE',
//   'LOAN PROCESSING FEE',
//   'LOAN DEFAULT CHG',
//   'POS INCOME',
//   'ACCOUNT MANTENANCE CHG',
//   'ACCOUNT OPENING',
//   'ADDRESS VERIFICATION',
//   'ACCOUNT REACTIVATION',
//   'CHEQUE/WTD BOOKLET',
//   'ASSOCIATION/COMPANY SEARCH',
//   'MONEY TRF CHG',
//   'GENERAL INCOME',
//   'ASSET A/C',
//   'PROVISION FOR LOAN LOSSES',
//   'INTEREST ON SAVINGS',
//   'INTEREST ON FIX DEPOSIT',
//   'CAC FEES/REG. DUES/ASSOC DUES',
//   'LOAN PROVISIONING',
//   'TELLER CASH',
//   'PUB.RELATION/ADVERT/MARKETING',
//   'LOAN A/C',
//   'FIXED DEPOSIT',
//   'OD GL A/C',
//   'CASH A/C',
//   'MISC INCOME'
//   ]
//     let acctyp = ['CASH',
// 'CASH',
// 'CASH',
// 'CURRENT ASSETS',
// 'CURRENT ASSETS',
// 'CURRENT ASSETS',
// 'CURRENT ASSETS',
// 'FIXED ASSET',
// 'FIXED ASSET',
// 'FIXED ASSET',
// 'FIXED ASSET',
// 'FIXED ASSET',
// 'CURRENT ASSETS',
// 'OTHER CURRENT ASSET',
// 'OTHER CURRENT ASSET',
// 'OTHER CURRENT ASSET',
// 'CURRENT ASSETS',
// 'CURRENT ASSETS',
// 'CURRENT ASSETS',
// 'CURRENT ASSETS',
// 'CURRENT ASSETS',
// 'CURRENT ASSETS',
// 'CURRENT ASSETS',
// 'CURRENT ASSETS',
// 'OTHER ASSET',
// 'OTHER ASSET',
// 'OTHER ASSET',
// 'OTHER ASSET',
// 'OTHER ASSET',
// 'OTHER ASSET',
// 'OTHER ASSET',
// 'OTHER ASSET',
// 'OTHER ASSET',
// 'OTHER ASSET',
// 'OTHER ASSET',
// 'CASH',
// 'EQUITY',
// 'EQUITY',
// 'EQUITY',
// 'EQUITY',
// 'EQUITY',
// 'EQUITY',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'OTHER CURRENT LIABILITIES',
// 'OTHER CURRENT LIABILITIES',
// 'OTHER CURRENT LIABILITIES',
// 'OTHER CURRENT LIABILITIES',
// 'OTHER CURRENT LIABILITIES',
// 'OTHER CURRENT LIABILITIES',
// 'OTHER CURRENT LIABILITIES',
// 'OTHER CURRENT LIABILITIES',
// 'OTHER CURRENT LIABILITIES',
// 'OTHER CURRENT LIABILITIES',
// 'LONG TERM LIABILITIES',
// 'LONG TERM LIABILITIES',
// 'LONG TERM LIABILITIES',
// 'ACCUMULATED DEPRECIATION',
// 'ACCUMULATED DEPRECIATION',
// 'ACCUMULATED DEPRECIATION',
// 'ACCUMULATED DEPRECIATION',
// 'ACCUMULATED DEPRECIATION',
// 'ACCUMULATED DEPRECIATION',
// 'EXPENSE',
// 'EXPENSE',
// 'EXPENSE',
// 'EXPENSE',
// 'EXPENSE',
// 'EXPENSE',
// 'EXPENSE',
// 'EXPENSE',
// 'EXPENSE',
// 'EXPENSE',
// 'EXPENSE',
// 'EXPENSE',
// 'INCOME',
// 'INCOME',
// 'INCOME',
// 'INCOME',
// 'INCOME',
// 'INCOME',
// 'INCOME',
// 'INCOME',
// 'INCOME',
// 'INCOME',
// 'INCOME',
// 'INCOME',
// 'INCOME',
// 'INCOME',
// 'INCOME',
// 'INCOME',
// 'INCOME',
// 'INCOME',
// 'ASSET',
// 'EXPENSE',
// 'EXPENSE',
// 'EXPENSE',
// 'EXPENSE',
// 'INCOME',
// 'CASH',
// 'EXPENSE',
// 'ACCOUNTS RECEIVABLE',
// 'ACCOUNTS PAYABLE',
// 'LIABILITIES',
// 'CASH',
// 'INCOME'
// ]
//     let grname = ['ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'ASSET',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'LIABILITIES',
// 'EXPENSES',
// 'EXPENSES',
// 'EXPENSES',
// 'EXPENSES',
// 'EXPENSES',
// 'EXPENSES',
// 'EXPENSES',
// 'EXPENSES',
// 'EXPENSES',
// 'EXPENSES',
// 'EXPENSES',
// 'EXPENSES',
// 'INTEREST INCOME',
// 'INTEREST INCOME',
// 'BUSINESS INCOME',
// 'COMMISSION',
// 'COMMISSION',
// 'COMMISSION',
// 'OTHER INCOME',
// 'OTHER INCOME',
// 'OTHER INCOME',
// 'OTHER INCOME',
// 'OTHER INCOME',
// 'OTHER INCOME',
// 'OTHER INCOME',
// 'OTHER INCOME',
// 'OTHER INCOME',
// 'OTHER INCOME',
// 'OTHER INCOME',
// 'INCOME',
// 'ASSET',
// 'PROVISION FOR LOSES',
// 'INTEREST EXPENSE',
// 'INTEREST EXPENSE',
// 'EXPENSES',
// 'INCOME',
// 'TELLER CASH',
// 'EXPENSE',
// 'RECIEVABLE',
// 'LIABILITY',
// 'OD GL',
// 'CASH A/C',
// 'OTHER INCOME',]
//     console.log('deescp', deescp.length)
//     console.log('acctyp', acctyp.length)
//     console.log('grname', grname.length)
//     for (let i = 0; i < deescp.length; i++) {
//     console.log(i);
//     document.getElementById('oreagladescription').value = deescp[i];
//     document.getElementById('oreaglaaccounttype').value = acctyp[i];
//     document.getElementById('oreaglagroupname').value = grname[i];
//     callController('glaccountscript.php', getaddglaccountParams(), 'saveglaccount', glacc_fields, null)
//     await new Promise(resolve => setTimeout(resolve, 500));
//   }
// }
        let vieweditglname ;
async function oreaddglaccount() {
        //the fuction below is what calls the page and please put the 'override' as the second parameter for now.
        await httpRequest('addglaccount.php', 'override');
        // [accountnumber, description, accounttype, groupname];
        JSON.parse(sessionStorage.getItem('vieweditgl')) ? vieweditglname = JSON.parse(sessionStorage.getItem('vieweditgl')) : null;
        // console.log(vieweditglname)
        // console.log(vieweditglname.length > 0);
        if(vieweditglname.length > 0){
            sessionStorage.removeItem('vieweditgl');
            document.getElementById('oreaglaaccountnumber').value = vieweditglname[0];
            document.getElementById('oreagladescription').value = vieweditglname[1];
            document.getElementById('oreaglaaccounttype').value = vieweditglname[2];
            document.getElementById('oreaglagroupname').value = vieweditglname[3];
        };
       
        // if(document.getElementById('glacc_accretrv'))document.getElementById('glacc_accretrv').addEventListener('click', e=>callController('fetchglaccounts.php', getaddglaccountP(), 'retrieveglaccount', [`oreaglaaccountnumber`], alert),true);
        if(document.getElementById('glacc_accretrv'))document.getElementById('glacc_accretrv').addEventListener('click', e=>callModal('feature: Coming soon'),true);
        if(document.getElementById('oreaglabtnSave'))document.getElementById('oreaglabtnSave').addEventListener('click',e=>{
            callController('glaccountscript.php', getaddglaccountParams(), 'saveglaccount', glacc_fields, null)
            document.getElementById('oreaglaaccountnumber').value = '';
            document.getElementById('oreagladescription').value = '';
            document.getElementById('oreaglaaccounttype').value = '';
            document.getElementById('oreaglagroupname').value = '';
            if(vieweditglname.length > 0)document.getElementById("viewglaccounts").click();
        },false);
        if(document.getElementById('oreaglabtnDelete'))document.getElementById('oreaglabtnDelete').addEventListener('click', e=>callController('controller.php', null, 'deleteglaccount', [`oreaglaaccountnumber`], alert),true);
       
        
}


var oreaddglaccountbbtn = document.getElementById("addglaccount");
if (oreaddglaccountbbtn) oreaddglaccountbbtn.addEventListener("click", oreaddglaccount, false);
