<?php
$displayhtml .= '<div class="orecontainer">';
$displayhtml .= '<div class="oresubcontianer">';
$displayhtml .= '<div class="oremainheadercontainer">';
$displayhtml .= '<p class="oremainheader">ADD PROPERTY ACCOUNT</p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="orecardcontainer">';
$displayhtml .= '<!-- <div class="orecardcontainer"> -->';
$displayhtml .= '<!-- <div class=""> -->';
$displayhtml .= '<div class="">';
$displayhtml .= '<div class="acreg-section3">';
$displayhtml .= "<p class='oresubheader'>Customer's Account</p>";
$displayhtml .= '<button id="acreg-propertybtn" class="hidden acreg-SCROLLBTN">property-></button>';
$displayhtml .= '';
$displayhtml .= '<div class="acreg-s3container">';
$displayhtml .= '<div class="acreg-s3scroller">';
$displayhtml .= '<div id="acreg-p1">';
$displayhtml .= '<div class="acregpropertyheader">';
$displayhtml .= '<div class="acregproselectitemcontainer">';
$displayhtml .= '<p>Select Item</p>';
$displayhtml .= '<select name="" id=""></select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="acregproselecttotalcontainer">';
$displayhtml .= '<p>Totoal Cost: </p>';
$displayhtml .= '<input readonly type="text">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="acregtablepropertyheader">';
$displayhtml .= '<p>s/n</p>';
$displayhtml .= '<p>Item</p>';
$displayhtml .= '<p>Description</p>';
$displayhtml .= '<p>Qty</p>';
$displayhtml .= '<p>Rate</p>';
$displayhtml .= '<p>Cost</p>';
$displayhtml .= '<p title="remove item">X</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="acregtablepropetycontentcontainer">';
$displayhtml .= '<div class="acregtablepropertycontent">';
$displayhtml .= '<p>1</p>';
$displayhtml .= '<p>Tomatoes paste gino</p>';
$displayhtml .= '<p>used for cooking stew</p>';
$displayhtml .= '<input type="text" class="orepropertyinpput" value="1">';
$displayhtml .= '<p>100</p>';
$displayhtml .= '<p>50</p>';
$displayhtml .= '<p style="color: red; cursor: pointer;" title="remove item">X</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="acregtablepropertycontent">';
$displayhtml .= '<p>1</p>';
$displayhtml .= '<p>Tomatoes paste gino</p>';
$displayhtml .= '<p>used for cooking stew</p>';
$displayhtml .= '<input type="text" class="orepropertyinpput" value="1">';
$displayhtml .= '<p>100</p>';
$displayhtml .= '<p>50</p>';
$displayhtml .= '<p style="color: red; cursor: pointer;" title="remove item">X</p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '<!-- <div id="acreg-p2" class="hidden">';
$displayhtml .= '<div class="acreg-s2mode ">';
$displayhtml .= '<div class="acreg-s2submode">';
$displayhtml .= '<label>Account Type</label>';
$displayhtml .= '<select name="" id="acreg-accounttype">';
$displayhtml .= '<option>LOAN</option>';
$displayhtml .= '<option>PROPERTY</option>';
$displayhtml .= '<option>SAVING</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="acreg-s2submode">';
$displayhtml .= '<label>Account Number</label>';
$displayhtml .= '<input type="text" name="" id="">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="acreg-s2mode">';
$displayhtml .= '<div class="acreg-s2submode">';
$displayhtml .= '<label>Date Reg</label>';
$displayhtml .= '<input type="date" name="" id="">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="acreg-s2submode">';
$displayhtml .= '<label>Value Date</label>';
$displayhtml .= '<input type="date" name="" id="">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="acreg-s2mode">';
$displayhtml .= '<div class="acreg-s2submode">';
$displayhtml .= '<label>Other Bank -1</label>';
$displayhtml .= '<select name="" id=""></select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="acreg-s2submode">';
$displayhtml .= '<label>Other Bank -2</label>';
$displayhtml .= '<select name="" id=""></select>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="acreg-s2mode">';
$displayhtml .= '<div class="acreg-s2submode">';
$displayhtml .= '<label>Bank Account No -1</label>';
$displayhtml .= '<input type="date" name="" id="">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="acreg-s2submode">';
$displayhtml .= '<label>Bank Account No -2</label>';
$displayhtml .= '<input type="date" name="" id="">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="acreg-s2mode">';
$displayhtml .= '<div class="acreg-s2submode">';
$displayhtml .= '<label>Account Opening Officer</label>';
$displayhtml .= '<select name="" id=""></select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="acreg-s2submode">';
$displayhtml .= '<label>Registration Point</label>';
$displayhtml .= '<select name="" id=""></select>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="acreg-s2mode">';
$displayhtml .= '<div class="acreg-s2submode">';
$displayhtml .= '<label>Domiciled Branch</label>';
$displayhtml .= '<input  class="acreg-extend"  type="text" name="" id="">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '';
$displayhtml .= '</div> -->';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="">';
$displayhtml .= '<p class="oresubheader">Confirm Payment Details</p>';
$displayhtml .= '<div class="inputcontainerln icsnf">';
$displayhtml .= '<p class="normaltext">Daily Unit</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerln icsnf">';
$displayhtml .= "<p class='normaltext'>Marketer's Group</p>";
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerln icsnf">';
$displayhtml .= '<p class="normaltext">User</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="acreg-section6">';
$displayhtml .= '<!-- <label class="acreg-s2modeheader">Action box</label>  -->';
$displayhtml .= '';
$displayhtml .= '<div class="acregbtncontainer">';
$displayhtml .= '<div class=acregbtn>Add Pix/Sign</div>';
$displayhtml .= '<div class=acregbtn>Submit</div>';
$displayhtml .= '<div class=acregbtn>View</div>';
$displayhtml .= '<div class=acregbtn>Submit Marketer</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<!-- </div> -->';
$displayhtml .= '<!-- </div> -->';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

echo $displayhtml
?>