<?php
session_start();

$displayhtml .= '<div class="orecontainer">';
$displayhtml .= '<div class="oresubcontianer">';
$displayhtml .= '<div class="oremainheadercontainer">';
$displayhtml .= '<p class="oremainheader">ACCOUNT REGISTRATION</p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="orecardcontainer">';
$displayhtml .= '<div class="stcnsection1">';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<p class="oresubheader">Personal Data box</p>';
$displayhtml .= '<div class="inputcontainermsn icsnf mlll">';
$displayhtml .= '<p class="normaltext capitalize">S/No</p>';
$displayhtml .= '<input maxlength="" id="" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerln icsnf">';
$displayhtml .= '<p class="normaltext capitalize">First Name</p>';
$displayhtml .= '<input maxlength="50" id="firstname" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerln icsnf">';
$displayhtml .= '<p class="normaltext capitalize">Last Name</p>';
$displayhtml .= '<input maxlength="50" id="lastname" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerln icsnf">';
$displayhtml .= '<p class="normaltext capitalize">Other Name</p>';
$displayhtml .= '<input maxlength="50" id="othernames" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerln icsnf">';
$displayhtml .= '<p class="normaltext capitalize">Phone Number</p>';
$displayhtml .= '<input maxlength="40" id="phonenumber" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerln icsnf">';
$displayhtml .= '<p class="normaltext capitalize">Residential Address</p>';
$displayhtml .= '<input maxlength="300" id="homeaddress" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerln icsnf">';
$displayhtml .= '<p class="normaltext capitalize">Office/Shop Address</p>';
$displayhtml .= '<input maxlength="300" id="officeaddress" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerln icsnf">';
$displayhtml .= '<p class="normaltext capitalize">Gender</p>';
$displayhtml .= '<select id="gender">';
$displayhtml .= '<option>Male</option>';
$displayhtml .= '<option>Female</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerln icsnf">';
$displayhtml .= '<p class="normaltext capitalize">Occupation</p>';
$displayhtml .= '<input maxlength="50" id="occupation" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerln icsnf">';
$displayhtml .= '<p class="normaltext capitalize">State of Origin</p>';
$displayhtml .= '<select id="state">';
$displayhtml .= '<option>Delta</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerln icsnf">';
$displayhtml .= '<p class="normaltext capitalize">Date of Birth</p>';
$displayhtml .= '<input maxlength="" id="birthdate" type="date">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<p class="oresubheader">Next of Kin Data</p>';
$displayhtml .= '<div class="inputcontainerln icsnf">';
$displayhtml .= '<p class="normaltext capitalize">Full Name</p>';
$displayhtml .= '<input maxlength="100" id="kinfullname" type="text">';
$displayhtml .= '</div>';
// $displayhtml .= '<div class="inputcontainerln icsnf">';
// $displayhtml .= '<p class="normaltext capitalize">Last Name</p>';
// $displayhtml .= '<input maxlength="" id="" type="text">';
// $displayhtml .= '</div>';
// $displayhtml .= '<div class="inputcontainerln icsnf">';
// $displayhtml .= '<p class="normaltext capitalize">Other Name</p>';
// $displayhtml .= '<input maxlength="" id="" type="text">';
// $displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerln icsnf">';
$displayhtml .= '<p class="normaltext capitalize">Phone Number</p>';
$displayhtml .= '<input maxlength="30" id="kinphonenumber" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerln icsnf">';
$displayhtml .= '<p class="normaltext capitalize">Relationship</p>';
$displayhtml .= '<input maxlength="50" id="relationship" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerln icsnf">';
$displayhtml .= '<p class="normaltext capitalize">Occupation</p>';
$displayhtml .= '<input maxlength="50" id="kinoccupation" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerln icsnf">';
$displayhtml .= '<p class="normaltext capitalize">Residential Address</p>';
$displayhtml .= '<input maxlength="250" id="kinhomeaddress" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerln icsnf">';
$displayhtml .= '<p class="normaltext capitalize">Office/Shop Address</p>';
$displayhtml .= '<input maxlength="250" id="kinofficeaddress" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="acreg-section6">';
$displayhtml .= '<!-- <label class="acreg-s2modeheader">Action box</label>  -->';
$displayhtml .= '';
$displayhtml .= '<div id="photourl" class="">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="acregbtncontainer">';
$displayhtml .= '<div class="acregbtn">Add Pix/Sign</div>';
$displayhtml .= '<div class="acregbtn" id="submitaccountregistration">Submit</div>';
$displayhtml .= '<div class="acregbtn">View</div>';
$displayhtml .= '<div class="acregbtn">Submit Marketer</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

echo $displayhtml
?>