<?php
$displayhtml .='<div class="jcontainer">';
$displayhtml .='<div>';
$displayhtml .='<h1 class="jpageheader"> active loans </h1>';
$displayhtml .='</div>';
$displayhtml .='<div class="jpagecontent" id="jpagecontent">';
$displayhtml .='<div>';
$displayhtml .='<div class="jflex jcontent-between">';
$displayhtml .='<span class="jcontent-between no-pr">';
$displayhtml .='<button type="button" class="j-action-btn jborder" style="border-color: #007bff;text-transform:capitalize;" id="loan-print-action">print</button> &nbsp;';
$displayhtml .='<button class="j-action-btn jborder" style="background-color: transparent;border-color: rgb(2, 77, 30);color: rgb(2, 77, 30);text-transform:capitalize;" id="export-list-excel">export excel</button>';
$displayhtml .='</span>';
$displayhtml .='<span>';
$displayhtml .='<span class="jformgroup jformgrouprow" id="loan-search-wrapper">';
$displayhtml .='<label class="jcontrollabel"> search: &nbsp;&nbsp; </label>';
$displayhtml .='<input type="search" placeholder="Type account number" id="filteractiveloans" class="jformcontrol">';
$displayhtml .='</span>';
$displayhtml .='</span>';
$displayhtml .='</div>';
$displayhtml .='<div class="jmargin-top">';
$displayhtml .='<div class="jtable-content">';
$displayhtml .='<table class="jmargin-top" id="activeloans">';
$displayhtml .='<thead>';
$displayhtml .='<tr>';
$displayhtml .='<th>s/n </th>';
$displayhtml .='<th> account number </th>';
$displayhtml .='<th> account name  </th>';
$displayhtml .='<th> opening date </th>';
$displayhtml .='<th> due date </th>';
$displayhtml .='<th> principal</th>';
$displayhtml .='<th> principal+ interest </th>';
$displayhtml .='<th> interest </th>';
$displayhtml .='<th> loan status</th>';
$displayhtml .='<th> loan duration </th>';
$displayhtml .='<th> int. method </th>';
$displayhtml .='<th> int rate </th>';
$displayhtml .='<th> loan officer </th>';
$displayhtml .='</tr>';
$displayhtml .='</thead>';
$displayhtml .='<tbody id="jtabledata"></tbody>';
$displayhtml .='</table>';
$displayhtml .='</div>';
$displayhtml .='<div class="j-table-status jflex jcontent-between jmargin-top">';
$displayhtml .='<span class="jcontrollabel" style="text-transform: none" id="pagination-status"> </span>';
$displayhtml .='<span class="jflex jpagination">';
$displayhtml .='<button class="j-no-bg" type="button" id="jprev-button">previous</button>';
$displayhtml .='<span id="pagination-numbers"></span>';
$displayhtml .='<button  class="j-no-bg" type="button" id="jnext-button">next</button>';
$displayhtml .='</span>';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='</div>';
echo $displayhtml;
?>