<?php
session_start();

$displayhtml .= '<div class="orecontainer">';
$displayhtml .= '<div class="oresubcontianer">';
$displayhtml .= '<div class="oremainheadercontainer">';
$displayhtml .= '<p class="oremainheader">GL ACCOUNT FORM</p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="orecardcontainer">';
$displayhtml .= '<p class="oresubheader">Account Info</p>';
$displayhtml .= '<div class="inputcontainerfn icsn">';
$displayhtml .= '<p class="normaltext">Account Number:</p>';
$displayhtml .= '<input id="oreaglaaccountnumber" disabled placeholder="Account Number" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="oresubmitcontainer">';
$displayhtml .= '<div id="glacc_accretrv"class="orerbtn">Retreive Account</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcnsection1">';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<div class="inputcontainerfn icsn">';
$displayhtml .= '<p class="normaltext">Group Name:</p>';
$displayhtml .= '<input id="oreaglagroupname" placeholder="Group Name" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<div class="inputcontainerfn icsn">';
$displayhtml .= '<p class="normaltext">Type Of Account:</p>';
$displayhtml .= '<select id="oreaglaaccounttype" class="custom-select" name="accounttype" title="Select account type.">';
$displayhtml .= '<option value="" disabled selected>--Select&nbsp;Account Type--</option>';
$displayhtml .= '<option value="ASSET">ASSET</option>';
$displayhtml .= '<option value="CASH">CASH</option>';
$displayhtml .= '<option value="CURRENT ASSETS">CURRENT ASSETS</option>';
$displayhtml .= '<option value="EXPENSE">EXPENSE</option>';
$displayhtml .= '<option value="INCOME">INCOME</option>';
$displayhtml .= '<option value="EQUITY RETAINED EARNINGS">EQUITY RETAINED EARNINGS</option>';
$displayhtml .= '<option value="EQUITY DOES NOT CLOSE">EQUITY DOES NOT CLOSE</option>';
$displayhtml .= '<option value="INVENTORY">INVENTORY</option>';
$displayhtml .= '<option value="OTHER ASSET">OTHER ASSET</option>';
$displayhtml .= '<option value="COST OF SALES">COST OF SALES</option>';
$displayhtml .= '<option value="FIXED ASSET">FIXED ASSET</option>';
$displayhtml .= '<option value="OTHER CURRENT ASSET">OTHER CURRENT ASSET</option>';
$displayhtml .= '<option value="ACCOUNTS PAYABLE">ACCOUNTS PAYABLE</option>';
$displayhtml .= '<option value="ACCOUNTS RECEIVABLE">ACCOUNTS RECEIVABLE</option>';
$displayhtml .= '<option value="ACCUMULATED DEPRECIATION">ACCUMULATED DEPRECIATION</option>';
$displayhtml .= '<option value="LIABILITIES">LIABILITIES</option>';
$displayhtml .= '<option value="OTHER CURRENT LIABILITIES">OTHER CURRENT LIABILITIES</option>';
$displayhtml .= '<option value="LONG TERM LIABILITIES">LONG TERM LIABILITIES</option>';
$displayhtml .= '<option value="EQUITY">EQUITY</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerfn icsn">';
$displayhtml .= '<p class="normaltext">Description:</p>';
$displayhtml .= '<input id="oreagladescription" placeholder="" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcnsection1">';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<div class="orerightcontainer mtt">';
$displayhtml .= '<div id="oreaglabtnDelete" class="orerbtn sysred px150">Delete</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<div class="oreleftcontainer mtt">';
$displayhtml .= '<div id="oreaglabtnSave" class="orerbtn sysblue px150">Save</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

echo $displayhtml
?>