<?php
session_start();

$displayhtml .= '<div class="orecontainer">';
$displayhtml .= '<div class="oresubcontianer">';
$displayhtml .= '<div class="oremainheadercontainer">';
$displayhtml .= '<p class="oremainheader">INTERNAL TRANSACTION FORM</p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div style="overflow: auto" class="orecardcontainer">';
$displayhtml .= '';
$displayhtml .= '<div class="oresubmitcontainer">';
$displayhtml .= '<div id="oreglexport" class="orerbtn" style="background: green">Upload from Excel</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<p class="oresubheader">Transaction Info</p>';
$displayhtml .= '<div class="stcnsection1">';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Date</p>';
$displayhtml .= '<input id="gltransdate" style="width: 95%" type="date" class="orevfy">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<div class="inputcontainerfn icsn">';
$displayhtml .= '<p class="normaltext">Description</p>';
$displayhtml .= '<input class="orevfy" style="width: 95%" id="gltransdescription" placeholder="Description" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="col-md-6 mt-lg-4">';
$displayhtml .= '<div class="checkbox switcher mt-lg-2">';
$displayhtml .= '<label for="customertogl" class="my-1 chekk">';
$displayhtml .= '<input style="width: 95%" class="hidden" type="checkbox" id="orecustomertogl" value="customertogl" name="customertogl">';
$displayhtml .= '<div id="swittchhtr"><small class="" id="whiteball"></small></div>';
$displayhtml .= 'Customer to GL';
$displayhtml .= '</label>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div id="orecusttogl" class="hidden">';
$displayhtml .= '<p class="oresubheader mtt">Customer section</p>';
$displayhtml .= '';
$displayhtml .= '<p class="oresmallfred">Note: Only Customer Accounts are excepted in this section</p>';
$displayhtml .= '<div class="inputcontainerln icsn mt">';
$displayhtml .= '<p class="normaltext">Transaction Type:</p>';
$displayhtml .= '<select class="orevfyy" class="custom-select" id="gltransactiontype" name="transactiontype" title="Select transaction type">';
$displayhtml .= '<option value="">--select transaction type--</option>';
$displayhtml .= '<option value="DEBIT">DEBIT</option>';
$displayhtml .= '<option value="CREDIT">CREDIT</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="stcnsection1">';
$displayhtml .= '<div class="stcs1a2">';
$displayhtml .= '<div class="inputcontainerfn icsn">';
$displayhtml .= '<p class="normaltext">Customer Account Number</p>';
$displayhtml .= '<input class="orevfyy gltranscustomeraccount" id="gltranstanstype" style="width: 95%" list="" onfocusout="glcustomeraccountnamecheck(this.value, this.nextElementSibling, this)" placeholder="Account No." type="number">';
$displayhtml .= '<input type="text" class="borderless " style="outline: none" readonly>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcs1a2">';
$displayhtml .= '<div class="inputcontainerfn icsn">';
$displayhtml .= '<p class="normaltext">Amount</p>';
$displayhtml .= '<input class="orevfyy allcustomeramount gltranscustomeramount" onchange="allcustomeramount()" id="gltransamounttenastype" style="width: 95%" placeholder="Amount" type="number">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div id="oreadddebit" style="font-size: small;position: relative;top: -7px;" class="mt oreadddebit1">+&nbsp;Add&nbsp;More</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div id="orecustglrowcont">';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<p class="oresubheader mtt">General Ledger section</p>';
$displayhtml .= '';
$displayhtml .= '<p class="oresmallfred">Note: Only GL Accounts are excepted in this section</p>';
$displayhtml .= '';
$displayhtml .= '<p class="oresubsubheader mtt">Debit Info</p>';
$displayhtml .= '';
$displayhtml .= '';
$displayhtml .= '<div class="stcnsection1">';
$displayhtml .= '<div class="stcs1a2">';
$displayhtml .= '<div class="inputcontainerfn icsn">';
$displayhtml .= '<input class="gltrandebitaccount" type="hidden">';
$displayhtml .= '<p class="normaltext">Debit Account</p>';
$displayhtml .= '<input class="orevfy" id="gltransdebitaccnoo" style="width: 95%" list="glaccountpopulate" onfocusout="glaccountpopulatecheck(this.value, this.previousElementSibling.previousElementSibling, this)" placeholder="Account" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcs1a2">';
$displayhtml .= '<div class="inputcontainerfn icsn">';
$displayhtml .= '<p class="normaltext">Amount</p>';
$displayhtml .= '<input class="orevfy alldebitamount gltransdebitamount" id="gltransdebotaccnoamount" onchange="alldebitamount()" style="width: 95%" placeholder="Amount" type="number">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div id="oreadddebitdebit" style="font-size: small;" class="mt oreadddebit1">+&nbsp;Add&nbsp;More</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div id="orecustglrowcontdebit">';
$displayhtml .= '';
$displayhtml .= '<!-- <div class="stcnsection1">';
$displayhtml .= '<div class="stcs1a2">';
$displayhtml .= '<div class="inputcontainerfn icsn">';
$displayhtml .= '<input type="hidden">';
$displayhtml .= '<p class="normaltext">Account</p>';
$displayhtml .= '<input style="width: 95%" list="glaccountpopulate" onfocusout="glaccountpopulatecheck(this.value, this.previousElementSibling.previousElementSibling, this)" placeholder="Account" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcs1a2">';
$displayhtml .= '<div class="inputcontainerfn icsn">';
$displayhtml .= '<p class="normaltext">Amount</p>';
$displayhtml .= '<input style="width: 95%" placeholder="Amount" type="number">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div id="" class="oreadddebit oreremove mt">remove</div>';
$displayhtml .= '</div> -->';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<p class="oresubsubheader mtt">Credit Info</p>';
$displayhtml .= '';
$displayhtml .= '';
$displayhtml .= '<div class="stcnsection1">';
$displayhtml .= '<div class="stcs1a2">';
$displayhtml .= '<div class="inputcontainerfn icsn">';
$displayhtml .= '<input class="gltranscreditaccount" type="hidden">';
$displayhtml .= '<p class="normaltext">Credit Account</p>';
$displayhtml .= '<input class="orevfy" id="gltranscreditaccnoo" style="width: 95%" list="glaccountpopulate" onfocusout="glaccountpopulatecheck(this.value, this.previousElementSibling.previousElementSibling, this)" placeholder="Account" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcs1a2">';
$displayhtml .= '<div class="inputcontainerfn icsn">';
$displayhtml .= '<p class="normaltext">Amount</p>';
$displayhtml .= '<input class="orevfy allcreditamount gltranscreditamount" id="gltranscreditaccnoamount" onchange="allcreditamount()" style="width: 95%" placeholder="Amount" type="number">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div id="oreadddebitcredit" style="font-size: small;" class="mt oreadddebit1">+&nbsp;Add&nbsp;More</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div id="orecustglrowcontcredit">';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<p class="oresubheader">Deduction Submenu</p>';
$displayhtml .= '';
$displayhtml .= '<div class="stcnsection1">';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<div class="inputcontainerfn icsn">';
$displayhtml .= '<p class="normaltext">Approve Transaction:</p>';
$displayhtml .= '<input class="orevfy" id="gltransapprovedtransaction" style="width: 95%" placeholder="password" type="password">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcs1a ma0">';
$displayhtml .= '<div class="col-md-6 mt-lg-4">';
$displayhtml .= '<div class="checkbox switcher oresec mt-lg-2">';
$displayhtml .= '<label for="customertogl" class="my-1 chekk">';
$displayhtml .= '<input style="width: 95%" class="hidden" type="checkbox" id="orecustomertogl2" value="customertogl" name="customertogl">';
$displayhtml .= '<div id="swittchhtr2"><small class="" id="whiteball2"></small></div>';
$displayhtml .= 'Send for Approval';
$displayhtml .= '</label>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '';
$displayhtml .= '<div class="stcnsection1">';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<div class="inputcontainerfn icsn">';
$displayhtml .= '<p class="normaltext">Customer Total:</p>';
$displayhtml .= '<input class="orevfy" id="gltranscustomertotal" style="width: 95%" class="bgrey" value="0" readonly placeholder="" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<div class="inputcontainerfn icsn">';
$displayhtml .= '<p class="normaltext">Total Debit:</p>';
$displayhtml .= '<input class="orevfy" id="gltranstotaldebitt" style="width: 95%" class="bgrey" value="0" readonly placeholder="" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<div class="inputcontainerfn icsn">';
$displayhtml .= '<p class="normaltext">Total Credit:</p>';
$displayhtml .= '<input class="orevfy" id="gltranstotalcreditt" style="width: 95%" class="bgrey" value="0" readonly placeholder="" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<p class="oresmallfred black center">Note: This form is for GL Transactions <b>ONLY</b></p>';
$displayhtml .= '';
$displayhtml .= '<div class="stcnsection1">';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<div class="orerightcontainer mtt">';
$displayhtml .= '<div class="orerbtn sysred px150">Delete</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<div class="oreleftcontainer mtt">';
$displayhtml .= '<div class="orerbtn sysblue px150" id="gltransaveform">Save</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<datalist id="glaccountpopulate"></datalist>';

echo $displayhtml;
?>