<?php
$displayhtml .= '<div class="jcontainer">';
$displayhtml .= '<div>';
$displayhtml .= '<h1 class="jpageheader"> branch fund transfers </h1>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jpagecontent" id="jpagecontent">';
$displayhtml .= '<div>';
$displayhtml .= '<form class="jform" id="branchfundtransferform">';
$displayhtml .= '<div class="section-header">';
$displayhtml .= '<h1> transfer info </h1>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="col-form-group">';
$displayhtml .= '<div class="jformgroup">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label class="jcontrollabel"> transfer from: </label>';
$displayhtml .= '<input list="branchfundtransferaccounts" onchange="checkInputwithdatalist(this.id, this.list.id) ? getbranchtransferprofile(this.value, this) : this.nextElementSibling.innerHTML = null" type="text" placeholder="Enter Account Number" class="jformcontrol jmargin-top" id="branchtransferfrom" name="amount">';
$displayhtml .= '<label class="jcontrollabel" style="color: green;font-size:17px"> </label>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
$displayhtml .= '<label class="jcontrollabel"> transfer to: </label>';
$displayhtml .= '<input list="branchfundtransferaccounts" onchange="checkInputwithdatalist(this.id, this.list.id) ? getbranchtransferprofile(this.value, this) : this.nextElementSibling.innerHTML = null" type="text" placeholder="Enter Account Number" class="jformcontrol jmargin-top" id="branchtransferto" name="amount">';
$displayhtml .= '<label class="jcontrollabel" style="color: green;font-size:17px"> </label>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="section-header">';
$displayhtml .= '<h1> details </h1>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="col-form-group">';
$displayhtml .= '<div class="jformgroup">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label class="jcontrollabel"> Amount: </label>';
$displayhtml .= '<input type="text" placeholder="Enter amount" class="jformcontrol jmargin-top" id="branchtransferamount" name="amount">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label class="jcontrollabel"> transaction date: </label>';
$displayhtml .= '<input type="date" class="jformcontrol jmargin-top" id="branchtransferdate" name="transactiondate">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label class="jcontrollabel"> reference: </label>';
$displayhtml .= '<input readonly type="text" class="jformcontrol jmargin-top" id="branchtransferreference" name="reference">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
$displayhtml .= '<label class="jcontrollabel"> Location: </label>';
$displayhtml .= '<select class="jformcontrol jmargin-top" id="branchtransferlocation" name="destination">';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="section-header">';
$displayhtml .= '<h1> others  </h1>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="col-form-group">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label class="jcontrollabel">Description: </label>';
$displayhtml .= '<textarea class="jformcontrol jmargin-top" rows="5" resize="none" id="branchtransferdescription"';
$displayhtml .= 'name="description"></textarea>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="jmargin-top jflex">';
$displayhtml .= '<button type="button" class="j-action-btn-alt jmargin-top" id="branchtransfersavebtn"> transfer';
$displayhtml .= '</button>';
$displayhtml .= '</div>';
$displayhtml .= '</form>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div><datalist id="branchfundtransferaccounts"></datalist>';
echo $displayhtml;
?>