<?php
session_start();

$displayhtml .= '<div class="orecontainer">';
$displayhtml .= '<div class="oresubcontianer">';
$displayhtml .= '<div class="oremainheadercontainer">';
$displayhtml .= '<p class="oremainheader">COMPANY TRANSACTIONS MONTHLY</p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="orecardcontainer">';
$displayhtml .= '<div class="pldlsubcontainer">';
$displayhtml .= '<div class="inputcontainermsn icsnf">';
$displayhtml .= '<p class="normaltext">Select Month:</p>';
$displayhtml .= '<select>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsnf">';
$displayhtml .= '<p class="normaltext">Year:</p>';
$displayhtml .= '<select>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ctmcontainer">';
$displayhtml .= '<div class="ctmtableheader">';
$displayhtml .= '<p></p>';
$displayhtml .= '<p>DEPOSIT</p>';
$displayhtml .= '<p>CONCESSION</p>';
$displayhtml .= '<p>CONCESS PROFIT</p>';
$displayhtml .= '<p>RRR FEES</p>';
$displayhtml .= '<p>EXPENDITURE</p>';
$displayhtml .= '<p>BANK DEPOSIT</p>';
$displayhtml .= '<p>WITHDRAWAL</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ctmtablebodycontainer">';
$displayhtml .= '<div class="ctmtablebody">';
$displayhtml .= '<p>DELTA</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ctmtablebody">';
$displayhtml .= '<p>DELTA</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ctmtablebody">';
$displayhtml .= '<p>DELTA</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ctmtablebody">';
$displayhtml .= '<p>DELTA</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ctmtablebody">';
$displayhtml .= '<p>DELTA</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ctmtablebody">';
$displayhtml .= '<p>DELTA</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ctmtablebody">';
$displayhtml .= '<p>DELTA</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ctmtablebody">';
$displayhtml .= '<p>DELTA</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ctmtablebody">';
$displayhtml .= '<p>DELTA</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ctmtablebody ctmtotal">';
$displayhtml .= '<p class="bolder">TOTAL</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ctmtablebody">';
$displayhtml .= '<p class="bolder">ADJUSTED DEPOSIT</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcnsection1">';
$displayhtml .= '<div class="stcs1a ctmflexend">';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext red">BANK CHARGES</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext red">ADMIN EXPENSE</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext red">UNIT SALARY</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext blue">NET</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<div class="pldlsubcontainer2">';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext blue">PROFIT ON DEPOSIT:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext blue">PROFIT ON BANK INTEREST:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext blue">PROFIT ON LOAN INTEREST:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext blue">TOTAL OPERATING INCOME:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext blue">TOTAL OPERATING EXPENSES:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

echo  $displayhtml;
?>