<?php
session_start();
$displayhtml .=  '<div class="formcontainer">';
$displayhtml .=  '<div class="formheader">';
$displayhtml .=  '<h5>CONFIRM BALANCE BROUGHT FORWARD</h5>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formmain">';
$displayhtml .=  '<div class="split formsection">';
$displayhtml .=  '<p class="topformsection">Enter Account Number</p>';
$displayhtml .=  '<div class=" specialflex">';
$displayhtml .=  '<div class="formcontrol flexgrow">';
$displayhtml .=  '<label for="enteractno"></label><br>';
$displayhtml .=  '<input type="number" name="enteractno" id="matenteraccountnumber" class="enteractno" >';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="empty"><p></p></label><br>';
$displayhtml .=  '<input type="text" name="empty" id="empty" class="empty smallestinput">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="unit">Unit</label>';
$displayhtml .=  '<input type="number" name="unit" id="matunit" class="unit smallestinput">';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="div split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="balance">Balance</label>';
$displayhtml .=  '<input type="number" name="balance" id="matbalance" class="balance">';
$displayhtml .=  '</div>';
$displayhtml .=  '';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="confirmdate">Confirm Date</label>';
$displayhtml .=  '<input type="date" name="confirmdate" id="confirmdate" class="confirmdate">';
$displayhtml .=  '</div>';
$displayhtml .=  '';
$displayhtml .=  '';
$displayhtml .=  '</div>';
$displayhtml .=  '';
$displayhtml .=  '</div>';
$displayhtml .=  '';
$displayhtml .=  '<div class="split3 formsection">';
$displayhtml .=  '<p class="topformsection">ACCOUNT DETAILS</p>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="accountname">Account Name</label><br>';
$displayhtml .=  '<input type="text" name="accountname" class="mataccountname" id="mataccountname">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="b/fdeposit">B/F Deposit</label><br>';
$displayhtml .=  '<input type="text" name="b/fdeposit" class="b/fdeposit" id="matbroughtforwarddeposit">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="postby">Post By</label><br>';
$displayhtml .=  '<input type="text" name="postby" class="postby" id="matpostby">';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '';
$displayhtml .=  '<div class="btns btnsspacebetween">';
$displayhtml .=  '<button type="submit" class="btnmedium btn btnblue">';
$displayhtml .=  'Update B/F';
$displayhtml .=  '</button>';
$displayhtml .=  '<button type="submit" class="btnmedium btn btnblue" id="matconfirmbroughtforwardbtn">';
$displayhtml .=  'Confirm B/F';
$displayhtml .=  '</button>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
echo $displayhtml;
?>