<?php
$displayhtml .= '<input id="profile-image-upload-input" type="file" hidden=""><div class="organisation-info-container item-types-first-section">';
$displayhtml .= '<div class="organisation-info-first-section">';
$displayhtml .= '<center>';
// $displayhtml .= '<img id="profile-image" class="first-section-image" src="../images/logo.png" alt="logo" width="100" height="100">';
// $displayhtml .= '<svg class="pencil-upload-image" id="profile-img-edit-icon" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="30" height="30" viewBox="0 0 30 30" style=" fill:#000000;">    <path d="M 22.828125 3 C 22.316375 3 21.804562 3.1954375 21.414062 3.5859375 L 19 6 L 24 11 L 26.414062 8.5859375 C 27.195062 7.8049375 27.195062 6.5388125 26.414062 5.7578125 L 24.242188 3.5859375 C 23.851688 3.1954375 23.339875 3 22.828125 3 z M 17 8 L 5.2597656 19.740234 C 5.2597656 19.740234 6.1775313 19.658 6.5195312 20 C 6.8615312 20.342 6.58 22.58 7 23 C 7.42 23.42 9.6438906 23.124359 9.9628906 23.443359 C 10.281891 23.762359 10.259766 24.740234 10.259766 24.740234 L 22 13 L 17 8 z M 4 23 L 3.0566406 25.671875 A 1 1 0 0 0 3 26 A 1 1 0 0 0 4 27 A 1 1 0 0 0 4.328125 26.943359 A 1 1 0 0 0 4.3378906 26.939453 L 4.3632812 26.931641 A 1 1 0 0 0 4.3691406 26.927734 L 7 26 L 5.5 24.5 L 4 23 z"></path></svg>';
$displayhtml .= '<h5>CONSUMABLE PROPERTY WITHDRAWAL</h5>';
$displayhtml .= '</center>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="organisation-info-third-section item-type-organisation-info-third-section">';
$displayhtml .= '<form class="organisation-info-form" id="organisation-info-div-basic-info">';
$displayhtml .= '<div class="stock-gift-div stock-return-div organisation-info-div-border-top-left-radius-0 item-types-organisation-info-div">';
$displayhtml .= '<div class="vicol-width-50-margin-0-auto">';
$displayhtml .= '<label for="company-name">Transaction Date &nbsp;</label>';
$displayhtml .= '<input class="stock-gift-input-50" type="date" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between-consumable-property">';
$displayhtml .= '<div class="vicol-width-40">';
$displayhtml .= '<div class="organisation-info-div-sub-container container-with-before container-with-before-enteraccountnumber">';
$displayhtml .= '<div class="vicol-width-80 vicol-display-flex-around">';
$displayhtml .= '<input class="stock-gift-input-50" type="text" name="" id="company-name" required><br>';
$displayhtml .= '<input class="stock-gift-input-35" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="organisation-info-div-sub-container container-with-before container-with-before-depositorprofilewithnoroyalty">';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-50 vicol-color-blue">Full Names</label>';
$displayhtml .= '<div class="vicol-display-flex-between vicol-width-70">';
$displayhtml .= '<div>';
$displayhtml .= '<input class="stock-gift-input-90 vicol-margin-top-0" type="text" name="" id="company-name" placeholder="First name" required>';
$displayhtml .= '</div>';
$displayhtml .= '<div>';
$displayhtml .= '<input class="stock-gift-input-90 vicol-margin-top-0" type="text" name="" id="company-name" placeholder="Last name" required>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-50 vicol-color-blue">Mobile No.</label>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-50 vicol-color-red">Office Branch</label>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-50 vicol-color-blue">Account Type</label>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-50 vicol-color-red">Gender</label>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-50 vicol-color-blue">Date Opened</label>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0" type="date" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-50 vicol-color-red">Last Active Date</label>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0" type="date" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-50 vicol-color-blue">Account Group</label>';
$displayhtml .= '<div class="vicol-display-flex-between vicol-width-70">';
$displayhtml .= '<div>';
$displayhtml .= '<br><input class="stock-gift-input-90 vicol-margin-top-0" type="text" name="" id="company-name" required>';
$displayhtml .= '</div>';
$displayhtml .= '<div>';
$displayhtml .= '<span class="vicol-color-blue">Act</span> <br> <input class="stock-gift-input-90 vicol-margin-top-0" type="text" name="" id="company-name" required>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-50 vicol-color-red">Marketer</label>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-50 vicol-color-blue">Online User</label>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-50 vicol-color-red">Transaction Point</label>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-50 vicol-color-blue">Agreed Deposit</label>';
$displayhtml .= '<div class="vicol-display-flex-between vicol-width-70">';
$displayhtml .= '<div>';
$displayhtml .= '<input class="stock-gift-input-90 vicol-margin-top-0" type="text" name="" id="company-name" required>';
$displayhtml .= '</div>';
$displayhtml .= '<div>';
$displayhtml .= '<input class="stock-gift-input-90 vicol-margin-top-0" type="text" name="" id="company-name" required>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-50 vicol-color-blue">Balance</label>';
$displayhtml .= '<div class="vicol-display-flex-between vicol-width-70">';
$displayhtml .= '<div>';
$displayhtml .= '<br><input class="stock-gift-input-90 vicol-margin-top-0" type="text" name="" id="company-name" required>';
$displayhtml .= '</div>';
$displayhtml .= '<div>';
$displayhtml .= '<span class="vicol-color-blue">Cost</span> <br> <input class="stock-gift-input-90 vicol-margin-top-0" type="text" name="" id="company-name" required>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div><br><br>';
$displayhtml .= '<div class="vicol-display-flex-between vicol-width-95-margin-0-auto">';
$displayhtml .= '<center><button class="vicol-btn-primary">&nbsp; Debit Acct &nbsp;</button></center>';
$displayhtml .= '<center><button class="vicol-btn-secondary">&nbsp; Next Rec &nbsp;</button></center>';
$displayhtml .= '<div><input class="stock-gift-input-70 vicol-margin-top-0" type="text" name="" id="company-name" required></div>';
$displayhtml .= '</div><br>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vicol-width-55">';
$displayhtml .= '<div class="organisation-info-div-sub-container container-with-before">';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<div class="vicol-color-blue">S/N</div>';
$displayhtml .= '<div class="vicol-width-30 vicol-color-blue">Description</div>';
$displayhtml .= '<div class="vicol-width-7 vicol-color-blue">Qty</div>';
$displayhtml .= '<div class="vicol-width-15 vicol-color-blue">Cost</div>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<input type="checkbox" name="" required>&nbsp;1';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-50" type="text" name="" id="company-name" required><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-10" type="text" name="" id="company-name" required><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-20" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<input type="checkbox" name="" required>&nbsp;2';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-50" type="text" name="" id="company-name" required><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-10" type="text" name="" id="company-name" required><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-20" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<input type="checkbox" name="" required>&nbsp;3';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-50" type="text" name="" id="company-name" required><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-10" type="text" name="" id="company-name" required><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-20" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<input type="checkbox" name="" required>&nbsp;4';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-50" type="text" name="" id="company-name" required><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-10" type="text" name="" id="company-name" required><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-20" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<input type="checkbox" name="" required>&nbsp;5';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-50" type="text" name="" id="company-name" required><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-10" type="text" name="" id="company-name" required><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-20" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<input type="checkbox" name="" required>&nbsp;6';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-50" type="text" name="" id="company-name" required><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-10" type="text" name="" id="company-name" required><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-20" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<input type="checkbox" name="" required>&nbsp;7';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-50" type="text" name="" id="company-name" required><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-10" type="text" name="" id="company-name" required><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-20" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<input type="checkbox" name="" required>&nbsp;8';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-50" type="text" name="" id="company-name" required><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-10" type="text" name="" id="company-name" required><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-20" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<input type="checkbox" name="" required>&nbsp;9';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-50" type="text" name="" id="company-name" required><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-10" type="text" name="" id="company-name" required><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-20" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<input type="checkbox" name="" required>10';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-50" type="text" name="" id="company-name" required><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-10" type="text" name="" id="company-name" required><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-20" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between vicol-width-70-margin-0-auto">';
$displayhtml .= '<div> <span class="vicol-color-blue">Invoice No.</span> <br> <input class="stock-gift-input-70" type="text" name="" id="company-name" required><br></div>';
$displayhtml .= '<div> <span class="vicol-color-blue">Service Charge</span> <br> <input class="stock-gift-input-70" type="text" name="" id="company-name" required><br></div>';
$displayhtml .= '<div> <span class="vicol-color-blue">Total Cost</span> <br> <input class="stock-gift-input-70" type="text" name="" id="company-name" required><br></div>';
$displayhtml .= '</div>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="organisation-info-div-sub-container container-with-before container-with-before-itemdetails">';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<div> <span class="vicol-color-red">Type</span> <br> <input class="stock-gift-input-70" type="text" name="" id="company-name" required><br></div>';
$displayhtml .= '<div> <span class="vicol-color-blue">Model</span> <br> <input class="stock-gift-input-70" type="text" name="" id="company-name" required><br></div>';
$displayhtml .= '<div> <span class="vicol-color-blue">Stock Balance</span> <br> <input class="stock-gift-input-70" type="text" name="" id="company-name" required><br></div>';
$displayhtml .= '</div>';
$displayhtml .= '</div><br>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</form>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

echo  $displayhtml;

?>