<?php
$displayhtml .= '<input id="profile-image-upload-input" type="file" hidden=""><div class="organisation-info-container item-types-first-section">';
$displayhtml .= '<div class="organisation-info-first-section">';
$displayhtml .= '<center>';
// $displayhtml .= '<img id="profile-image" class="first-section-image" src="../images/logo.png" alt="logo" width="100" height="100">';
// $displayhtml .= '<svg class="pencil-upload-image" id="profile-img-edit-icon" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="30" height="30" viewBox="0 0 30 30" style=" fill:#000000;">    <path d="M 22.828125 3 C 22.316375 3 21.804562 3.1954375 21.414062 3.5859375 L 19 6 L 24 11 L 26.414062 8.5859375 C 27.195062 7.8049375 27.195062 6.5388125 26.414062 5.7578125 L 24.242188 3.5859375 C 23.851688 3.1954375 23.339875 3 22.828125 3 z M 17 8 L 5.2597656 19.740234 C 5.2597656 19.740234 6.1775313 19.658 6.5195312 20 C 6.8615312 20.342 6.58 22.58 7 23 C 7.42 23.42 9.6438906 23.124359 9.9628906 23.443359 C 10.281891 23.762359 10.259766 24.740234 10.259766 24.740234 L 22 13 L 17 8 z M 4 23 L 3.0566406 25.671875 A 1 1 0 0 0 3 26 A 1 1 0 0 0 4 27 A 1 1 0 0 0 4.328125 26.943359 A 1 1 0 0 0 4.3378906 26.939453 L 4.3632812 26.931641 A 1 1 0 0 0 4.3691406 26.927734 L 7 26 L 5.5 24.5 L 4 23 z"></path></svg>';
$displayhtml .= '<h5>COUNTER DEPOSIT: INCORRECT AMOUNT PAID: UGWAUAGBA</h5><br>';
$displayhtml .= '</center>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="organisation-info-third-section item-type-organisation-info-third-section">';
$displayhtml .= '<form class="organisation-info-form" id="organisation-info-div-basic-info">';
$displayhtml .= '<div class="stock-gift-div stock-return-div organisation-info-div-border-top-left-radius-0 item-types-organisation-info-div">';


$displayhtml .= '<div class="organisation-info-div-sub-container vicol-width-50">';
$displayhtml .= '<div class="organisation-info-div-sub-container">';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-50 vicol-color-red">Branch: </label>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-40 vicol-color-blue">Account Officer</label>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<select class="stock-gift-input-70 vicol-margin-top-0 vicol-width-75" type="text" name="" id="company-name" required>';
$displayhtml .= '<option value="" selected disabled></option>';
$displayhtml .= '<option value="">Example 1</option>';
$displayhtml .= '<option value="">Example 2</option>';
$displayhtml .= '<option value="">Example 3</option>';
$displayhtml .= '</select>';
$displayhtml .= '<input class="stock-gift-input-70  vicol-margin-top-0 vicol-width-20" type="text" name="" id="company-name" disabled required>';
$displayhtml .= '</div>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-50 vicol-color-blue">Counter</label>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-50 vicol-color-blue">Tran. Date Names</label>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0" type="date" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-50 vicol-color-blue">Group</label>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-50 vicol-color-blue">Confirmed Status</label>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<p class="vicol-text-align-right">';
$displayhtml .= '<button class="vicol-btn-secondary">&nbsp; Reveal &nbsp;</button>';
$displayhtml .= '</p>';
$displayhtml .= '</div><br>';
$displayhtml .= '</div><br>';


$displayhtml .= '<div class="organisation-info-div-sub-container container-with-before vicol-width-80">';
$displayhtml .= '<div class="vicol-display-flex-between-view-excess">';
$displayhtml .= '<div class="vicol-width-48">';
$displayhtml .= '<div class="organisation-info-div-sub-container">';
$displayhtml .= '<br><h5>REVERSE FROM</h5><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-50 vicol-color-red">Account No.:</label>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-50 vicol-color-red">Full Names</label>';
$displayhtml .= '<div class="vicol-display-flex-between vicol-width-70">';
$displayhtml .= '<div>';
$displayhtml .= '<input class="stock-gift-input-90 vicol-margin-top-0" type="text" name="" id="company-name" placeholder="First name" required>';
$displayhtml .= '</div>';
$displayhtml .= '<div>';
$displayhtml .= '<input class="stock-gift-input-90 vicol-margin-top-0" type="text" name="" id="company-name" placeholder="Last name" required>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-50 vicol-color-red">Amount Paid</label>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-50 vicol-color-red">Balance</label>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vicol-width-48">';
$displayhtml .= '<div class="organisation-info-div-sub-container">';
$displayhtml .= '<br><h5>REVERSE TO</h5><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-70 vicol-color-blue">Reverse Amount Paid To</label>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<p class="vicol-text-align-right">';
$displayhtml .= '<button class="vicol-btn-secondary">&nbsp; Reverse &nbsp;</button>';
$displayhtml .= '</p>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div><br>';



$displayhtml .= '<div class="organisation-info-div-sub-container container-with-before vicol-width-80">';
$displayhtml .= '<div class="vicol-display-flex-between-view-excess">';
$displayhtml .= '<div class="vicol-width-48">';
$displayhtml .= '<div class="organisation-info-div-sub-container">';
$displayhtml .= '<br><h5>REVERSE FROM</h5><br>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<label for="company-name" class="vicol-width-50 vicol-color-red">Depositor</label>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vicol-width-48">';
$displayhtml .= '<div class="organisation-info-div-sub-container">';
$displayhtml .= '<br><h5>REVERSE TO</h5><br>';
$displayhtml .= '<select class="stock-gift-input-70 vicol-margin-top-0 vicol-width-95" type="text" name="" id="company-name" required>';
$displayhtml .= '<option value="" selected disabled></option>';
$displayhtml .= '<option value="">Example 1</option>';
$displayhtml .= '<option value="">Example 2</option>';
$displayhtml .= '<option value="">Example 3</option>';
$displayhtml .= '</select><br><br>';
$displayhtml .= '<div class="vicol-display-flex-between vicol-width-95">';
$displayhtml .= '<label for="company-name" class="vicol-width-80 vicol-color-red">Group</label>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-margin-top-0 vicol-width-20" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div><br>';
$displayhtml .= '<p class="vicol-text-align-right">';
$displayhtml .= '<button class="vicol-btn-secondary">&nbsp; Reverse &nbsp;</button>';
$displayhtml .= '</p>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';


$displayhtml .= '</form>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

echo  $displayhtml;

?>