<?php
session_start();

$displayhtml .='<div class="formcontainer overflowcontainer">';
$displayhtml .='<div class="formheader">';
$displayhtml .='<h5>COUNTER POST WRONG ACCOUNT ENTRY</h5>';
$displayhtml .='</div>';
$displayhtml .='<div class="formmain ">';
$displayhtml .='<div class="formsection split">';
$displayhtml .='<div class="split">';
$displayhtml .='<div class="formcontrol">';
$displayhtml .='<label for="branch">Branch</label>';
$displayhtml .='<select name="branch" id="matbranch">';
$displayhtml .='<option value=""></option>';
$displayhtml .='</select>';
$displayhtml .='';
$displayhtml .='</div>';
$displayhtml .='';
$displayhtml .='<div class="formcontrol">';
$displayhtml .='<label for="accountofficer">Account Officer</label>';
$displayhtml .='<select name="accountofficer" id="mataccountofficer">';
$displayhtml .='<option value=""></option>';
$displayhtml .='</select>';
$displayhtml .='';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='';
$displayhtml .='<div class="split">';
$displayhtml .='<div class="formcontrol">';
$displayhtml .='<label for="counter" >Counter</label>';
$displayhtml .='<input type="number" name="counter" id="matcounter">';
$displayhtml .='</div>';
$displayhtml .='<div class="formcontrol">';
$displayhtml .='<label for="transactiondate">Transaction Date</label>';
$displayhtml .='<input type="date" name="transaction" id="transactiondate">';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='';
$displayhtml .='<div class="split">';
$displayhtml .='<div class="formcontrol">';
$displayhtml .='<label for="group">Group</label>';
$displayhtml .='<input type="text" name="group" id="matgroup">';
$displayhtml .='</div>';
$displayhtml .='<div class="formcontrol">';
$displayhtml .='<label for="treatedstatus">Treated Status</label>';
$displayhtml .='<input type="text" name="treatedstatus" id="mattreatedstatus">';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='';
$displayhtml .='<div class="split">';
$displayhtml .='<div class="formcontrol">';
$displayhtml .='<label for="confirmstatus">Confirm Status</label>';
$displayhtml .='<input type="text" name="confirmstatus" id="matconfirmstatus">';
$displayhtml .='</div>';
$displayhtml .='<div class="wrapbtn">';
$displayhtml .='<button type="submit" class="btnmedium btn btnblue">';
$displayhtml .='Reveal';
$displayhtml .='</button>';
$displayhtml .='</div>';
$displayhtml .='';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='<div class="split">';
$displayhtml .='<div class="formsection">';
$displayhtml .='<p class="topformsection">';
$displayhtml .='REVERSE FROM';
$displayhtml .='</p>';
$displayhtml .='<div class="split">';
$displayhtml .='<div class="formcontrol">';
$displayhtml .='<label for="accounnumber">Account Number</label>';
$displayhtml .='<input type="number" name="accountnumber" id="matfromaccountnumber">';
$displayhtml .='</div>';
$displayhtml .='<div class="formcontrol">';
$displayhtml .='<label for="firstname">First Name</label>';
$displayhtml .='<input type="text" name="firstame" id="matfromfirstname">';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='<div class="split">';
$displayhtml .='<div class="formcontrol">';
$displayhtml .='<label for="lastname">Last Name</label>';
$displayhtml .='<input type="text" name="lastame" id="matfromlastname">';
$displayhtml .='</div>';
$displayhtml .='<div class="formcontrol">';
$displayhtml .='<label for="middlename">Middle Name</label>';
$displayhtml .='<input type="text" name="middlename" id="matfrommiddlename">';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='<div class="split">';
$displayhtml .='<div class="formcontrol">';
$displayhtml .='<label for="amountpaid">Amount Paid</label>';
$displayhtml .='<input type="number" name="amountpaid" id="matfromamountpaid">';
$displayhtml .='</div>';
$displayhtml .='<div class="formcontrol">';
$displayhtml .='<label for="balance">Balance</label>';
$displayhtml .='<input type="number" name="balance" class="balance" id="matfrombalance">';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='';
$displayhtml .='<div class="formsection">';
$displayhtml .='<p class="topformsection"> REVERSE TO</p>';
$displayhtml .='<div class="split">';
$displayhtml .='<div class="formcontrol">';
$displayhtml .='<label for="branch">Branch</label>';
$displayhtml .='<select name="branch" id="mattobranch">';
$displayhtml .='<option value=""></option>';
$displayhtml .='</select>';
$displayhtml .='';
$displayhtml .='</div>';
$displayhtml .='<div class="formcontrol">';
$displayhtml .='<label for="accountnumber">Account Number</label>';
$displayhtml .='<input type="number" name="accountnumber" id="mattoaccountnumber">';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='';
$displayhtml .='<div class="split">';
$displayhtml .='<div class="formcontrol">';
$displayhtml .='<label for="firstname">First Name</label>';
$displayhtml .='<input type="text" name="firstame" id="mattofirstname">';
$displayhtml .='</div>';
$displayhtml .='<div class="formcontrol">';
$displayhtml .='<label for="lastname">Last Name</label>';
$displayhtml .='<input type="text" name="lastame" id="mattolastname">';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='<div class="split">';
$displayhtml .='<div class="formcontrol">';
$displayhtml .='<label for="middlename">Middel Name</label>';
$displayhtml .='<input type="text" name="middlename" id="mattomiddlename">';
$displayhtml .='</div>';
$displayhtml .='<div class="formcontrol">';
$displayhtml .='<label for="group">Group</label>';
$displayhtml .='<input type="text" name="group" id="mattogroup">';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='';
$displayhtml .='<div class="split">';
$displayhtml .='<div class="formcontrol">';
$displayhtml .='<label for="balance">Balance</label>';
$displayhtml .='<input type="number" name="balance" id="mattobalance">';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='<div class=" wrapbtn btncenter">';
$displayhtml .='<button type="submit" class="btnsizetwo btn btnblue" id="matcounterpostwrongbtn">';
$displayhtml .='Reverse Posting';
$displayhtml .='</button>';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='';
$displayhtml .='</div>';


echo $displayhtml;
?>
