<?php
session_start();

$displayhtml .=  '<div class="formcontainer">';
$displayhtml .=  '<div class="formheader">';
$displayhtml .=  '<h5>CUSTOMER PROPERTY UPDATE</h5>';
$displayhtml .=  '</div>';
$displayhtml .=  '';
$displayhtml .=  '<div class="formmain">';
$displayhtml .=  '<section class="formsection">';
$displayhtml .=  '<p class="topformsection">ENTER ACCOUNT NUMBER</p>';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="specialflex">';
$displayhtml .=  '<div class="formcontrol flexgrow">';
$displayhtml .=  '<label for="enteraccountno"></label><br>';
$displayhtml .=  '<input type="number" name="enteraccountno" id="enteraccountno" class="enteraccountno">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol sm">';
$displayhtml .=  '<label for="enteraccountno"></label><br>';
$displayhtml .=  '<input type="number" name="enteraccountno" id="enteraccountno" class="enteraccountno smallestinput">';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="dateupdated">Date Update</label>';
$displayhtml .=  '<input type="date" name="dateupdated" id="dateupdated">';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '</section>';
$displayhtml .=  '<section class="split">';
$displayhtml .=  '';
$displayhtml .=  '<div class="formsection">';
$displayhtml .=  '';
$displayhtml .=  '<p class="topformsection">DEPOSITOR PROFILE</p>';
$displayhtml .=  '';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="firstname">First Name</label>';
$displayhtml .=  '<input type="text" class="firstname" name="firstname" id="firstname">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="lastname">Last Name</label>';
$displayhtml .=  '<input type="text" class="lastname" name="lastname" id="lastname">';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="othername">Other Name</label>';
$displayhtml .=  '<input type="text" class="othername" name="othername" id="othername">';

$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="mobilenumber">Mobile Number</label>';
$displayhtml .=  '<input type="number" class="othernamemobilenumber" name="mobilenumber" id="mobilenumber">';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="domicilebranch">Domicile Branch</label>';
$displayhtml .=  '<input type="text" name="domicilebranch" id="domicilebranch" class="domicilebranch">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="accounttype">Account Type</label>';
$displayhtml .=  '<input type="text" name="accounttype" id="accounttype" class="accounttype" >';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="gender">Gender</label>';
$displayhtml .=  '<input type="text" name="gender" class="gender"  id="gender">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="dateopened">Date Opened</label>';
$displayhtml .=  '<input type="date" name="dateopened" class="dateopened" id="dateopened">';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="lastactivedate">Last Active Date</label>';
$displayhtml .=  '<input type="date" name="lastactivedate" class="lastactivedate" id="lastactivedate">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="actopenofficer">Account Open Officer</label>';
$displayhtml .=  '<input type="date" name="actopenofficer" class="actopenofficer" id="actopenofficer">';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="selectnewactopenofficer">Select New Account Open Officer</label>';
$displayhtml .=  '<select name="" id=""></select>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="onlineuser">Onlone User</label>';
$displayhtml .=  '<input type="text" name="onlineuser" id="onlineuser" class="onlineuser">';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="transactionpoint">Transaction Point</label>';
$displayhtml .=  '<input type="text" name="transactionpoint" class="transactionpoint" id="transactionpoint">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="agreeddeposit">Agreed Deposit</label>';
$displayhtml .=  '<input type="text" name="agreeddeposit" class="agreeddeposit" id="agreeddeposit">';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="balance">Balance</label>';
$displayhtml .=  '<input type="number" name="balance" id="balance" class="baance">';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formsection">';
$displayhtml .=  '<p class="topformsection">SLOTS</p>';
$displayhtml .=  '';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="selectitem">Select Item</label>';
$displayhtml .=  '<select name="" id="">';
$displayhtml .=  '<option disabled selected value="">--Select Item--</option>';
$displayhtml .=  '</select>';
$displayhtml .=  '<button class="sortarrow  iconbtns btnicon">';
$displayhtml .=  '<span> <img src="images/icons/sort-arrows.png" alt="" /></span>';
$displayhtml .=  '</button>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="customerpropertygridcontainer';
$displayhtml .=  'matgridcontainer">';
$displayhtml .=  '<div class="first"></div>';
$displayhtml .=  '<div class="second"></div>';
$displayhtml .=  '<div class="third">Description</div>';
$displayhtml .=  '<div class="forth">Qty</div>';
$displayhtml .=  '<div class="fifth">Rate</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="customerpropertygridcontainer';
$displayhtml .=  'matgridcontainer">';
$displayhtml .=  '<span class="ccolor">C</span>';
$displayhtml .=  '<div class="second"><input type="text"></div>';
$displayhtml .=  '<div class="third"><input type="text"></div>';
$displayhtml .=  '<div class="forth"><input type="text"></div>';
$displayhtml .=  '<div class="fifth"><input type="text"></div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="customerpropertygridcontainer';
$displayhtml .=  'matgridcontainer">';
$displayhtml .=  '<span class="ccolor">C</span>';
$displayhtml .=  '<div class="second"><input type="text"></div>';
$displayhtml .=  '<div class="third"><input type="text"></div>';
$displayhtml .=  '<div class="forth"><input type="text"></div>';
$displayhtml .=  '<div class="fifth"><input type="text"></div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="customerpropertygridcontainer';
$displayhtml .=  'matgridcontainer">';
$displayhtml .=  '<span class="ccolor">C</span>';
$displayhtml .=  '<div class="second"><input type="text"></div>';
$displayhtml .=  '<div class="third"><input type="text"></div>';
$displayhtml .=  '<div class="forth"><input type="text"></div>';
$displayhtml .=  '<div class="fifth"><input type="text"></div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="customerpropertygridcontainer';
$displayhtml .=  'matgridcontainer">';
$displayhtml .=  '<span class="ccolor">C</span>';
$displayhtml .=  '<div class="second"><input type="text"></div>';
$displayhtml .=  '<div class="third"><input type="text"></div>';
$displayhtml .=  '<div class="forth"><input type="text"></div>';
$displayhtml .=  '<div class="fifth"><input type="text"></div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="customerpropertygridcontainer';
$displayhtml .=  'matgridcontainer">';
$displayhtml .=  '<span class="ccolor">C</span>';
$displayhtml .=  '<div class="second"><input type="text"></div>';
$displayhtml .=  '<div class="third"><input type="text"></div>';
$displayhtml .=  '<div class="forth"><input type="text"></div>';
$displayhtml .=  '<div class="fifth"><input type="text"></div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="customerpropertygridcontainer';
$displayhtml .=  'matgridcontainer">';
$displayhtml .=  '<span class="ccolor">C</span>';
$displayhtml .=  '<div class="second"><input type="text"></div>';
$displayhtml .=  '<div class="third"><input type="text"></div>';
$displayhtml .=  '<div class="forth"><input type="text"></div>';
$displayhtml .=  '<div class="fifth"><input type="text"></div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="customerpropertygridcontainer';
$displayhtml .=  'matgridcontainer">';
$displayhtml .=  '<span class="ccolor">C</span>';
$displayhtml .=  '<div class="second"><input type="text"></div>';
$displayhtml .=  '<div class="third"><input type="text"></div>';
$displayhtml .=  '<div class="forth"><input type="text"></div>';
$displayhtml .=  '<div class="fifth"><input type="text"></div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="customerpropertygridcontainer';
$displayhtml .=  'matgridcontainer">';
$displayhtml .=  '<span class="ccolor">C</span>';
$displayhtml .=  '<div class="second"><input type="text"></div>';
$displayhtml .=  '<div class="third"><input type="text"></div>';
$displayhtml .=  '<div class="forth"><input type="text"></div>';
$displayhtml .=  '<div class="fifth"><input type="text"></div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="customerpropertygridcontainer';
$displayhtml .=  'matgridcontainer">';
$displayhtml .=  '<span class="ccolor">C</span>';
$displayhtml .=  '<div class="second"><input type="text"></div>';
$displayhtml .=  '<div class="third"><input type="text"></div>';
$displayhtml .=  '<div class="forth"><input type="text"></div>';
$displayhtml .=  '<div class="fifth"><input type="text"></div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="customerpropertygridcontainer';
$displayhtml .=  'matgridcontainer">';
$displayhtml .=  '<span class="ccolor">C</span>';
$displayhtml .=  '<div class="second"><input type="text"></div>';
$displayhtml .=  '<div class="third"><input type="text"></div>';
$displayhtml .=  '<div class="forth"><input type="text"></div>';
$displayhtml .=  '<div class="fifth"><input type="text"></div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="customerpropertygridcontainer';
$displayhtml .=  'matgridcontainer">';
$displayhtml .=  '<span class="ccolor">C</span>';
$displayhtml .=  '<div class="second"><input type="text"></div>';
$displayhtml .=  '<div class="third"><input type="text"></div>';
$displayhtml .=  '<div class="forth"><input type="text"></div>';
$displayhtml .=  '<div class="fifth"><input type="text"></div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="customerpropertygridcontainer';
$displayhtml .=  'matgridcontainer">';
$displayhtml .=  '<span class="ccolor">C</span>';
$displayhtml .=  '<div class="second"><input type="text"></div>';
$displayhtml .=  '<div class="third"><input type="text"></div>';
$displayhtml .=  '<div class="forth"><input type="text"></div>';
$displayhtml .=  '<div class="fifth"><input type="text"></div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="customerpropertygridcontainer';
$displayhtml .=  'matgridcontainer">';
$displayhtml .=  '<span class="ccolor">C</span>';
$displayhtml .=  '<div class="second"><input type="text"></div>';
$displayhtml .=  '<div class="third"><input type="text"></div>';
$displayhtml .=  '<div class="forth"><input type="text"></div>';
$displayhtml .=  '<div class="fifth"><input type="text"></div>';
$displayhtml .=  '</div>';
$displayhtml .=  '';
$displayhtml .=  '<div class="btns btncenter">';
$displayhtml .=  '<button type="submit" class=" btnmedium btn btnblue">';
$displayhtml .=  'Update Non Consumable to Consumable';
$displayhtml .=  '</button>';
$displayhtml .=  '';
$displayhtml .=  '<button type="submit" class=" btnmedium btn btnblue">';
$displayhtml .=  'Update Consumable to Non Consumable';
$displayhtml .=  '</button>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '</section>';
$displayhtml .=  '</div>';
$displayhtml .=  '';
$displayhtml .=  '';
$displayhtml .=  '</div>';

echo $displayhtml;
?>