<?php
session_start();

$displayhtml .= '<div id="customerdeposit-container">';
$displayhtml .= '<div class="cusd-subcontainer">';
$displayhtml .= '<p class="headercenter">CUSTOMER DEPOSIT</p>';
$displayhtml .= '<div class="cusdformholder">';
$displayhtml .= '<div class="custs1">';
$displayhtml .= '<input id="cusdep_broughtForward" type="checkbox">';
$displayhtml .= '<p class="">Tick for Brought Forward Only</p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="cusdsubcont1">';
$displayhtml .= '';
$displayhtml .= '<div class="custholder ">';
$displayhtml .= '<p class="subheader ">Account Number</p>';
$displayhtml .= '<div class="custs2">';
$displayhtml .= '<input id="cusdep_accountnumber" class="custs2a" type="text">';
$displayhtml .= '<input class="custs2b hidden" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="custholder mtt containertweak">';
$displayhtml .= '<p class="subheader subheadertweak">Deposit Control</p>';
$displayhtml .= '<div class="custs3">';
$displayhtml .= '<div class="custs3a">';
$displayhtml .= '<div class="custs3aa">';
$displayhtml .= '<p>Posting Limit</p>';
$displayhtml .= '<input id="cusdep_postingLimit" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="custs3aa">';
$displayhtml .= '<p>Counter</p>';
$displayhtml .= '<input id="cusdep_counter" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="custs3aa">';
$displayhtml .= '<p>Date Control</p>';
$displayhtml .= '<input id="cusdep_datecontrol" type="date">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="custs3">';
$displayhtml .= '<div class="custs3a">';
$displayhtml .= '<div class="custs3aa">';
$displayhtml .= '<p class="normaltext">Account Officer</p>';
$displayhtml .= '<select id="cusdep_accountofficer">';
$displayhtml .= '<option value="">--Select--</option>';
$displayhtml .= '<option>sdfljkfksdjfldsj</option>';
$displayhtml .= '<option>sdfljkfksdjfldsj</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="custs3aa">';
$displayhtml .= '<p class="normaltext">Account Group</p>';
$displayhtml .= '<select id="cusdep_accountgroup">';
$displayhtml .= '<option value="">--Select--</option>';
$displayhtml .= '<option>sdfljkfksdjfldsj</option>';
$displayhtml .= '<option>sdfljkfksdjfldsj</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
// $displayhtml .= '<div class="custs3bb2">';
$displayhtml .= '</div>';
// $displayhtml .= '<div class="custs3loadbtn hidden">Load</div>';
// $displayhtml .= '</div>';
$displayhtml .= '<div style="margin-left: auto" class="hidden custs3loadbtn">Load</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="cusdsubcont2">';
$displayhtml .= '<div class="cusdholder2">';
$displayhtml .= '<div class="cusdds1 containertweak">';
$displayhtml .= "<p class='subheader subheadertweak bold m1'>Depositor's Profile</p>";
$displayhtml .= '<div class="pdcontent normaltext">';
$displayhtml .= '<p>First Name</p>';
$displayhtml .= '<input value="Nill" class="borderless" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pdcontent normaltext">';
$displayhtml .= '<p>Last Name</p>';
$displayhtml .= '<input value="Nill" class="borderless" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pdcontent normaltext">';
$displayhtml .= '<p>Other Name</p>';
$displayhtml .= '<input value="Nill" class="borderless" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pdcontent normaltext">';
$displayhtml .= '<p class="">Mobile Number</p>';
$displayhtml .= '<input value="Nill" class="borderless" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pdcontent normaltext">';
$displayhtml .= '<p class="">Domiciled Branch</p>';
$displayhtml .= '<input value="Nill" class="borderless" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pdcontent normaltext">';
$displayhtml .= '<p class="">Account Type</p>';
$displayhtml .= '<input value="Nill" class="borderless" id="cusdep_whichaccount" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pdcontent normaltext">';
$displayhtml .= '<p class="">Gender</p>';
$displayhtml .= '<input value="Nill" class="borderless" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pdcontent normaltext">';
$displayhtml .= '<p class="">Date opened</p>';
$displayhtml .= '<input value="Nill" class="borderless" type="date">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pdcontent normaltext">';
$displayhtml .= '<p class="">Last Active Date</p>';
$displayhtml .= '<input value="Nill" class="borderless" type="date">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pdcontent normaltext">';
$displayhtml .= '<p class="">Act Open Officer</p>';
$displayhtml .= '<input value="Nill" class="borderless" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pdcontent normaltext">';
$displayhtml .= '<p class="">Online User</p>';
$displayhtml .= '<input value="Nill" class="borderless" id="cusdep_user" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pdcontent normaltext">';
$displayhtml .= '<p class="">Transaction point</p>';
$displayhtml .= '<input value="Nill" class="borderless" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pdcontent normaltext">';
$displayhtml .= '<p class="">Agreed Deposit</p>';
$displayhtml .= '<input value="Nill" class="borderless" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pdcontent normaltext">';
$displayhtml .= '<p class="">Balance</p>';
$displayhtml .= '<input value="Nill" class="borderless" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="cusdholder2a mtt containertweak">';
$displayhtml .= '<p class="subheader subheadertweak bold m1">Transaction Details</p>';
$displayhtml .= '<div class="cusdholder2b">';
$displayhtml .= '<div class="m1 custs3a">';
$displayhtml .= '<div class="custs3aa">';
$displayhtml .= '<p>Transaction Date</p>';
$displayhtml .= '<input id="cusdep_transactiondate" type="date">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="custs3aa">';
$displayhtml .= '<p>Value Date</p>';
$displayhtml .= '<input id="cusdep_valuedate" type="date">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pdcontent normaltext">';
$displayhtml .= '<p>Deposit ID</p>';
$displayhtml .= '<input id="cusdep_depositid" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pdcontent normaltext">';
$displayhtml .= '<p>Particulars</p>';
$displayhtml .= '<input id="cusdep_particulars" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="custs1">';
$displayhtml .= '<input type="checkbox">';
$displayhtml .= '<p class="">Tick <span class="red">+ charges</span></p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pdcontent normaltext">';
$displayhtml .= '<p>Amount Paid</p>';
$displayhtml .= '<input id="cusdep_amountpaid" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="cusdbtn m hidden">Credit Acct</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="oresubmitcontainer">';
$displayhtml .= '<div id="cusdep_submitcustomerdeposit" class="orerbtn">Submit</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<input type="hidden" id="cusdep_location">';
$displayhtml .= '</div>';

echo $displayhtml
?>