<?php
session_start();

$displayhtml .= '<div class="orecontainer">';
$displayhtml .= '<div class="oresubcontianer">';
$displayhtml .= '<div class="oremainheadercontainer">';
$displayhtml .= '<p class="oremainheader">DAILY WITHDRAWAL</p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="orecardcontainer">';
$displayhtml .= '<div class="pldlsubcontainer">';
$displayhtml .= '<div class="inputcontainermsn icsnf">';
$displayhtml .= '<p class="normaltext">Total Deposit:</p>';
$displayhtml .= '<input type="date">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="pldlsubcontainer3">';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext blue">UGWUAGBA:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext blue">MAIN MARKET:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerMn icsnf">';
$displayhtml .= '<p class="normaltext blue">RELIEF</p>';
$displayhtml .= '<input type="text" >';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext blue">BRIDGE HEAD</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext blue">AGHANLA:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext blue">PLASTIC:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext blue">BUILDING:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext blue">NKPOR:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext blue">NNEWI:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext blue bolder">TOTAL:</p>';
$displayhtml .= '<input type="text" class="bglightblue">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<!--  -->';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

echo  $displayhtml;
?>