<?php
session_start();
$displayhtml .=  '<div class="formcontainer overflowcontainer">';
$displayhtml .=  '<div class="formheader">';
$displayhtml .=  '<h5>FIND UPDATE RECORD</h5>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formmain ">';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="div">';
$displayhtml .=  '<div class="formsection">';
$displayhtml .=  '<p class="topformsection" >Personal Box Market(X) must be filled</p>';
$displayhtml .=  '';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="firstname">First Name</label>';
$displayhtml .=  '<input type="text" name="firstname" id="firstname">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="lastname">Last Name</label>';
$displayhtml .=  '<input type="text" name="lastname" id="lastname">';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="othername">Other Name</label>';
$displayhtml .=  '<input type="text" name="othername" id="othername">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="phonenumber">Phone Number</label>';
$displayhtml .=  '<input type="number" name="phonenumber" id="phonenumber">';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="residentialaddress">Residential Address</label>';
$displayhtml .=  '<input type="text" name="residentialaddress" id="residentialaddress">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="residentialaddress">Office/shop Address</label>';
$displayhtml .=  '<input type="text" name="residentialaddress" id="residentialaddress">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="gender">Gender</label>';
$displayhtml .=  '<select name="gender" id="gender">';
$displayhtml .=  '<option value="Male">Male</option>';
$displayhtml .=  '<option value="Female">Female</option>';
$displayhtml .=  '</select>';
$displayhtml .=  '';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="occupation">Occupation</label>';
$displayhtml .=  '<select name="occupation" id="occupation">';
$displayhtml .=  '<option value="Business">Business</option>';
$displayhtml .=  '<option value="Front-End Dev">Front-End Dev</option>';
$displayhtml .=  '<option value="Backend-End Dev">Backend-End Dev</option>';
$displayhtml .=  '</select>';
$displayhtml .=  '';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="stateoforigin">State of Origin</label>';
$displayhtml .=  '<select name="stateoforigin" id="stateoforigin">';
$displayhtml .=  '<option value="Lagos">Lagos</option>';
$displayhtml .=  '<option value="Oyo">Oyo</option>';
$displayhtml .=  '<option value="Ekiti">Ekiti</option>';
$displayhtml .=  '</select>';
$displayhtml .=  '';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="dob">Date of Birth</label>';
$displayhtml .=  '<input type="date" name="dob" id="dob" class="dob">';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formsection">';
$displayhtml .=  '<p class="topformsection">Next Of Kin Data</p>';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="firstname">First Name</label>';
$displayhtml .=  '<input type="text" name="firstname" id="firstname">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="lastname">Last Name</label>';
$displayhtml .=  '<input type="text" name="lastname" id="lastname">';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="othername">Other Name</label>';
$displayhtml .=  '<input type="text" name="othername" id="othername">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="phonenumber">Phone Number</label>';
$displayhtml .=  '<input type="number" name="phonenumber" id="phonenumber">';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="relationship">Relationship</label>';
$displayhtml .=  '<select name="relationship" id="relationship">';
$displayhtml .=  '<option disabled selected value="">--Select--</option>';
$displayhtml .=  '<option value="Brother">Brother</option>';
$displayhtml .=  '<option value="Sister">Sister</option>';
$displayhtml .=  '<option value="Father">Father</option>';
$displayhtml .=  '<option value="Mother">Mother</option>';
$displayhtml .=  '</select>';
$displayhtml .=  '';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="Officeshopaddress">Office/Show Address</label>';
$displayhtml .=  '<textarea name="" id="" cols="10" rows=""></textarea>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="residentialaddress">Residential Address</label>';
$displayhtml .=  '<textarea name="30" id="" cols="10"  rows=""></textarea>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="occupation">Occupation</label>';
$displayhtml .=  '<select name="occupation" id="occupation">';
$displayhtml .=  '<option value="Business">Business</option>';
$displayhtml .=  '<option value="Front-End Dev">Front-End Dev</option>';
$displayhtml .=  '<option value="Backend-End Dev">Backend-End Dev</option>';
$displayhtml .=  '</select>';
$displayhtml .=  '';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="div">';
$displayhtml .=  '<div class="formsection">';
$displayhtml .=  '<p class="topformsection">CUSTOMER`S ACCOUNT</p>';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="accounttype">Account Type</label>';
$displayhtml .=  '<select name="accounttype" id="accounttype">';
$displayhtml .=  '<option value="SAVINGS">SAVINGS</option>';
$displayhtml .=  '<option value="CURRENT">CURRENT</option>';
$displayhtml .=  '</select>';
$displayhtml .=  '';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="specialflex">';
$displayhtml .=  '<div class="formcontrol flexgrow">';
$displayhtml .=  '<label for="accountno">Account Number</label>';
$displayhtml .=  '<input type="text" name="accountno" class="accountno" id="accountno">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="ac">A.C</label>';
$displayhtml .=  '<input type="text" name="ac" class="ac smallestinput">';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="dateopened">Date Opened</label>';
$displayhtml .=  '<input type="date" name="dateopened">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol ">';
$displayhtml .=  '<label for="otherbank">Othe Bank</label>';
$displayhtml .=  '<select name="otherbank" id="otherbank">';
$displayhtml .=  '<option value="UBA">UBA</option>';
$displayhtml .=  '</select>';
$displayhtml .=  '';
$displayhtml .=  '';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="bankaccountnumber">Bank Account Number</label>';
$displayhtml .=  '<input type="number" name="bankaccountnumber" id="bankaccountnumber">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="accountopeningofficer">Account Opening Officer</label>';
$displayhtml .=  '<select name="accountopeningofficer" id="accountopeningofficer">';
$displayhtml .=  '<option value=""></option>';
$displayhtml .=  '</select>';
$displayhtml .=  '';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="officebranch">Office Branch</label>';
$displayhtml .=  '<select name="officebranch" id="officebranch">';
$displayhtml .=  '<option value=""></option>';
$displayhtml .=  '</select>';
$displayhtml .=  '';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formsection">';
$displayhtml .=  '<p class="topformsection">PROPERTY`S SLOT</p>';
$displayhtml .=  '<div class="findupdategridcontainer matgridcontainer">';
$displayhtml .=  '<div class="first"></div>';
$displayhtml .=  '<div class="second">Description</div>';
$displayhtml .=  '<div class="third">Cost</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '';
$displayhtml .=  '<div class="findupdategridcontainer matgridcontainer">';
$displayhtml .=  '<div class="first"></div>';
$displayhtml .=  '<div class="second">';
$displayhtml .=  '<input type="text">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="third"><input type="text"></div>';
$displayhtml .=  '</div>';
$displayhtml .=  '';
$displayhtml .=  '<div class="findupdategridcontainer matgridcontainer">';
$displayhtml .=  '<div class="first"></div>';
$displayhtml .=  '<div class="second">';
$displayhtml .=  '<input type="text">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="third"><input type="text"></div>';
$displayhtml .=  '</div>';
$displayhtml .=  '';
$displayhtml .=  '<div class="findupdategridcontainer matgridcontainer">';
$displayhtml .=  '<div class="first"></div>';
$displayhtml .=  '<div class="second">';
$displayhtml .=  '<input type="text">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="third"><input type="text"></div>';
$displayhtml .=  '</div>';
$displayhtml .=  '';
$displayhtml .=  '<div class="findupdategridcontainer matgridcontainer">';
$displayhtml .=  '<div class="first"></div>';
$displayhtml .=  '<div class="second">';
$displayhtml .=  '<input type="text">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="third"><input type="text"></div>';
$displayhtml .=  '</div>';
$displayhtml .=  '';
$displayhtml .=  '<div class="findupdategridcontainer matgridcontainer">';
$displayhtml .=  '<div class="first "></div>';
$displayhtml .=  '<div class="second">';
$displayhtml .=  '<input type="text">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="third"><input type="text"></div>';
$displayhtml .=  '</div>';
$displayhtml .=  '';
$displayhtml .=  '<div class="btns btnend">';
$displayhtml .=  '<button type="button" class=" btnmedium btn btnblue">';
$displayhtml .=  'Update Null';
$displayhtml .=  '</button>';
$displayhtml .=  '</div>';
$displayhtml .=  '';
$displayhtml .=  '</div>';
$displayhtml .=  '';
$displayhtml .=  '<div class="formsection">';
$displayhtml .=  '<p class="topformsection">CONFIRMATION PAYMENT DETAIL</p>';
$displayhtml .=  '<div class="split3">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="dailyamount">Daily Amount</label>';
$displayhtml .=  '<input type="text" name="dailyamount" id="dailyamount">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="group">Group</label>';
$displayhtml .=  '<select name="group" id="group">';
$displayhtml .=  '<option value=""></option>';
$displayhtml .=  '</select>';
$displayhtml .=  '';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="user">User</label>';
$displayhtml .=  '<input type="text" name="user" class="user" id="user">';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formsection">';
$displayhtml .=  '<p class="topformsection">Serial Number</p>';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="from">From</label>';
$displayhtml .=  '<input type="text" name="from" id="from">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="specialflex">';
$displayhtml .=  '<div class="formcontrol flexgrow">';
$displayhtml .=  '<label for="to">To</label>';
$displayhtml .=  '<input type="text" name="to" id="to">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="wrapbtn">';
$displayhtml .=  '<div class="btns mt">';
$displayhtml .=  '<button type="button" class=" btnmedium btn btnblue">';
$displayhtml .=  'Update';
$displayhtml .=  '</button>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '';
$displayhtml .=  '<div class="formsection">';
$displayhtml .=  '<p class="topformsection">Action Box</p>';
$displayhtml .=  '';
$displayhtml .=  '<div class="btns btncenter">';
$displayhtml .=  '<button type="button" class=" btnmedium btn btnblue">';
$displayhtml .=  'Find-AccNO';
$displayhtml .=  '</button>';
$displayhtml .=  '<button type="button" class=" btnmedium btn btnblue">';
$displayhtml .=  'Find-phone No';
$displayhtml .=  '</button>';
$displayhtml .=  '';
$displayhtml .=  '<button type="button" class=" btnmedium btn btnblue">';
$displayhtml .=  'Update';
$displayhtml .=  '</button>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';

echo $displayhtml;
?>
