<?php
session_start();

$displayhtml .= '<div class="formcontainer overflowcontainer">';
$displayhtml .= '<div class="formheader">';
$displayhtml .= '<h5>INTAKE</h5>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="formmain">';
$displayhtml .= '<form action="">';
$displayhtml .= '<div class="split">';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="matintakereceivedfrom">Received From</label>';
$displayhtml .= '<select';
$displayhtml .= ' type="text"';
$displayhtml .= ' name="matintakereceivedfrom"';
$displayhtml .= ' id="matintakereceivedfrom"';
$displayhtml .= ' class="matintakereceivedfrom">';
$displayhtml .= '<option value=""></option>';
$displayhtml .= '<option value=""></option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';

$displayhtml .= '</div>';
$displayhtml .= '<div class="split">';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="matintakedate">Date</label>';
$displayhtml .= '<input type="date" class="matintakedate" id="matintakedate" />';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="split">';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="matintakereferenceno">Reference Number</label>';
$displayhtml .= '<input';
$displayhtml .= ' type="number"';
$displayhtml .= ' class="matintakereferenceno"';
$displayhtml .= ' id="matintakereferenceno"';
$displayhtml .= ' />';
$displayhtml .= '</div>';

$displayhtml .= '<div class="split">';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="btns wrapbtn">';
$displayhtml .= '<button type="button" class="btnlarge btn btnblue mt" id="matintakebtnsubmit">';
$displayhtml .= 'Submit';
$displayhtml .= '</button>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<!-- <button class="createbranchbtn btn btnblue">Enter Branch </button> -->';
$displayhtml .= '</form>';
$displayhtml .= '';
$displayhtml .= '';
$displayhtml .= '<div class="matgridholder">';
$displayhtml .= '';
$displayhtml .= '<div class="takegridheader ">';
$displayhtml .= '<div class="grid1">ITEM</div>';
$displayhtml .= '<div class="grid2">ITEM INFO</div>';
$displayhtml .= '<div class="grid3">UNIT COST</div>';
$displayhtml .= '<div class="grid4">QUANTITY</div>';
$displayhtml .= '<div class="grid5">VALUE</div>';
$displayhtml .= '<div class="grid6">DESCRIPTION</div>';
$displayhtml .= '<div class="grid7">VALUE</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="intakegridrow">';
$displayhtml .= '<!-- <div class="grid__item">';
$displayhtml .= '<select name="selectitem" id="matitakeselectitem">';
$displayhtml .= '<option value="" disabled selected>select item</option>';
$displayhtml .= '<option value="">item one</option>';
$displayhtml .= '<option value="">item two</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="grid__item">';
$displayhtml .= '<p>Type: <span class="typevalue"></span></p>';
$displayhtml .= '<p>Model: <span class="modelvalue"></span></p>';
$displayhtml .= '<p>Stock Balance: <span class="stockbalancevalue"></span></p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="grid__item">';
$displayhtml .= '<input type="number" id="intakeunitcost">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="grid__item">';
$displayhtml .= '<input type="number" id="intakequantity">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="grid__item">';
$displayhtml .= '<input type="text" id="intakevalue" disabled value="">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="grid__item">';
$displayhtml .= '<input type="text" id="intakedescription" disabled>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="grid__item">';
$displayhtml .= '<button class="plusbtn"> + </button>';
$displayhtml .= '</div> -->';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '</div>';


echo $displayhtml;
?>
