<?php
session_start();

$displayhtml .= '<div class="formcontainer">';
$displayhtml .= '<div class="formheader">';
$displayhtml .= '<h5>INVENTORY REGISTRATION</h5>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="formmain">';
$displayhtml .= '<form action="">';
$displayhtml .= '<div class="formcontrol controlspecial">';
$displayhtml .= '<label for="selectitem">Select Item</label>';
$displayhtml .= '<select name="selectitem" id="selectitem" class="selectitem">';
$displayhtml .= '<option  value=""></option>';
$displayhtml .= '</select>';
$displayhtml .= '<button class="sortarrow btnicon">';
$displayhtml .= '<span';
$displayhtml .= '><img src="images/icons/sort-arrows.png" alt=""';
$displayhtml .= '/></span>';
$displayhtml .= '</button>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="formcontrol controlspecial">';
$displayhtml .= '<label for="selectitem">Item Type</label>';
$displayhtml .= '<select name="selectitem" id="selectitem" class="selectitem">';
$displayhtml .= '<option  value=""></option>';
$displayhtml .= '</select>';
$displayhtml .= '<button class="sortarrow btnicon">';
$displayhtml .= '<span';
$displayhtml .= '><img src="images/icons/sort-arrows.png" alt=""';
$displayhtml .= '/></span>';
$displayhtml .= '</button>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="split">';
$displayhtml .= '<div class="formcontrol ">';
$displayhtml .= '<label for="itemname">Item Name</label>';
$displayhtml .= '<input type="text" name="itemname" id="itemname" class="itemname" >';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="model">Model</label>';
$displayhtml .= '<input type="text" name="model" id="model" class="model" >';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="split3">';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="savingselling">Saving Selling price</label>';
$displayhtml .= '<input type="number" id="savingselling" class="savingselling" name="savingselling">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="cashselling">Warehouse/Cash selling price</label>';
$displayhtml .= '<input type="number" id="cashselling" class="cashselling" name="cashselling">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="marketingprice">Marketing price</label>';
$displayhtml .= '<input type="number" id="marketingprice" class="marketingprice" name="marketingprice">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '';
$displayhtml .= '<div class="split4">';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="stockin">Stock In</label>';
$displayhtml .= '<input type="number" id="stockin" class="stockin" name="stockin">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="stockout">Stock Out</label>';
$displayhtml .= '<input type="number" id="stockout" class="stockout" name="stockout">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="gift">Gift</label>';
$displayhtml .= '<input type="number" id="gift" class="gift" name="gift">';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="balance">Balance</label>';
$displayhtml .= '<input type="number" id="balance" class="balance" name="balance">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="btns btncenter">';
$displayhtml .= '<button type="submit" class="btnsizetwo btn btnblue ">';
$displayhtml .= 'Update';
$displayhtml .= '</button>';
$displayhtml .= '<button type="submit" class="btnsizetwo btn btnred">';
$displayhtml .= 'Cancel';
$displayhtml .= '</button>';
$displayhtml .= '</div>';
$displayhtml .= '</form>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

echo $displayhtml;
?>