<?php
$displayhtml .= '<div class="jcontainer">';
$displayhtml .= '<div>';
$displayhtml .= '<h1 class="jpageheader"> loan reports by classification </h1>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jpagecontent" id="jpagecontent">';
$displayhtml .= '<div>';
$displayhtml .= '<form class="jform" id="loanclassificationreportform">';
$displayhtml .= '';
$displayhtml .= '<div class="col-form-group">';
$displayhtml .= '<div class="jformgroup">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label class="jcontrollabel"> report type: </label>';
$displayhtml .= '<select class="jformcontrol jmargin-top" id="loanreporttype" name="reporttype" title="select report type">';
$displayhtml .= '<option value=""> -- Select report type --</option>';
$displayhtml .= '<option value="LENDING MODEL">LENDING MODEL</option>';
$displayhtml .= '<option value="BREAKDOWN OF OTHER LOANS">BREAKDOWN OF OTHER LOANS</option>';
$displayhtml .= '<option value="SUMMARY OF LOAN CLASSIFICATTION">SUMMARY OF LOAN CLASSIFICATTION</option>';
$displayhtml .= '<option value="SUMMARY OF NON PERFORMING LOANS">SUMMARY OF NON PERFORMING LOANS</option>';
$displayhtml .= '<option value="SECTORAL ANALYSIS OF LOANS AND ADVANCES">SECTORAL ANALYSIS OF LOANS AND ADVANCES</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
$displayhtml .= '<label class="jcontrollabel"> report date: </label>';
$displayhtml .= '<input type="date" class="jformcontrol jmargin-top" id="loanreportdate" name="reportdate">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jflex jitems-left">';
$displayhtml .= '<div class="jflex jitems-left" style="width: 100%;">';
$displayhtml .= '<button type="button" class="j-action-btn" style="width: 15%;text-transform: capitalize;background-color: rgb(34, 33, 33);" id="view-lcr">view</button>&nbsp;';
$displayhtml .= '<button type="button" class="j-action-btn" style="width: 15%;text-transform: capitalize;" id="print-lcr">print</button>&nbsp;';
$displayhtml .= '<button type="button" class="j-action-btn" style="width: 15%;text-transform: capitalize;background-color: rgb(2, 77, 30);" id="export-lcr">report</button>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="section-header" style="border: none;">';
$displayhtml .= '<h1 class=" jmargin-top" style="text-align: center;"> </h1>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div id ="reportcontainer ">';
$displayhtml .= '<div class="section-header">';
$displayhtml .= '<h1 class=" jmargin-top" style="text-align: center;" id="reportclassficationheader"></h1>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jmargin-top">';
$displayhtml .= '<div class="jtable-content">';
$displayhtml .= '<table class="jmargin-top" id="loanreportbyclasstable">';
$displayhtml .= '<thead id="jtableheader">';
$displayhtml .= '</thead>';
$displayhtml .= '<tbody id="jtabledata"></tbody>';
$displayhtml .= '';
$displayhtml .= '</table>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</form>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
echo $displayhtml;
?>