<?php
$displayhtml .= '<div class="jcontainer">';
$displayhtml .= '<div>';
$displayhtml .= '<h1 class="jpageheader">loan fee</h1>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jpagecontent" id="jpagecontent">';
$displayhtml .= '<div>';
$displayhtml .= '<form id="loanfeeform" class="no-pr">';
$displayhtml .= '<div class="col-form-group">';
$displayhtml .= '<div class="jformgroup">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label class="jcontrollabel"> feename: </label>';
$displayhtml .= '<input placeholder="Enter fee name" type="text" class="jformcontrol jmargin-top"  id="loanfeename" name="feename" />';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
$displayhtml .= '<label class="jcontrollabel"> fee method: </label>';
$displayhtml .= '<select class="jformcontrol jmargin-top" id="loanfeemethod" name="feemethod">';
$displayhtml .= '<option value="FIXED">FIXED</option>';
$displayhtml .= '<option value="PERCENTAGE">PERCENTAGE</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label class="jcontrollabel"> charges based on: </label>';
$displayhtml .= '<select class="jformcontrol jmargin-top" id="loanchargebasis" name="chargebasis">';
$displayhtml .= '<option value="PRINCIPAL AMOUNT ONLY">';
$displayhtml .= 'PRINCIPAL AMOUNT ONLY';
$displayhtml .= '</option>';
$displayhtml .= '<option value="PRINCIPAL PLUS INTEREST">';
$displayhtml .= 'PRINCIPAL PLUS INTEREST';
$displayhtml .= '</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
$displayhtml .= '<label class="jcontrollabel">';
$displayhtml .= '<span style="text-transform: none"></span> GL Account';
$displayhtml .= '</label>';
$displayhtml .= '<select class="jformcontrol jmargin-top" id="loanglaccount" name="glaccount">';
$displayhtml .= '<option value="" selected="">';
$displayhtml .= '-- SELECT GL ACCOUNT --';
$displayhtml .= '</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="form-paragraph" style="font-size: small; margin: 30px 0">';
$displayhtml .= '<span>';
$displayhtml .= '*Note: Loan fee will be credited to the Income GL Account';
$displayhtml .= 'set here</span>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jflex jitems-left">';
$displayhtml .= '<div class="jflex jitems-right" style="width: 100%">';
$displayhtml .= '<button type="button" class="j-action-btn" style="width: 15%; text-transform: capitalize;  background-color: red;" id="reset-lf">';
$displayhtml .= 'reset</button>&nbsp;';
$displayhtml .= '<button type="button" class="j-action-btn"  style="width: 15%; text-transform: capitalize" id="save-lf">  save</button>&nbsp;';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</form>';
$displayhtml .= '';
$displayhtml .= '<div class="jform">';
$displayhtml .= '<div class="section-header">';
$displayhtml .= '<h1 class="jmargin-top"></h1>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jflex jitems-left no-pr" style="margin: 20px 0">';
$displayhtml .= '<span>';
$displayhtml .= '<button type="button" class="j-action-btn jborder no-pr" style="text-transform: capitalize" id="print-lfs">print</button>&nbsp;';
$displayhtml .= '<button type="button" class="j-action-btn jborder no-pr" style="text-transform: capitalize; background-color: rgb(34, 33, 33)" id="export-lfs"> export</button>';
$displayhtml .= '&nbsp;';
$displayhtml .= '</span>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jtable-content">';
$displayhtml .= '<table class="jmargin-top" id="loanfeetable">';
$displayhtml .= '<thead>';
$displayhtml .= '<tr>';
$displayhtml .= '<th>s/n</th>';
$displayhtml .= '<th>fee name</th>';
$displayhtml .= '<th>fee method</th>';
$displayhtml .= '<th>charge base on</th>';
$displayhtml .= '<th>gl account</th>';
$displayhtml .= '</tr>';
$displayhtml .= '</thead>';
$displayhtml .= '<tbody id="jtabledata"></tbody>';
$displayhtml .= '</table>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
echo $displayhtml;
?>