<?php
$displayhtml .='<div class="formcontainer overflowcontainer">';
$displayhtml .='<div class="formheader">';
$displayhtml .='<h5>DASHBOARD</h5>';
$displayhtml .='</div>';
$displayhtml .='<div class="dashboardmain">';
$displayhtml .='<div class="dashboardcard">';
$displayhtml .='<div class="dashboardicon loans"><i class="fa-sharp fa-solid fa-scale-balanced iconsize"></i> </div>';
$displayhtml .='<div class="dashboardcontent">';
$displayhtml .='<h6 class="dashboardcardheader">LOANS</h6>';
$displayhtml .='<p class="dashboardcarddata"><span class="cardkey">Total</span> <span class="cardvalue">7</span></p>';
$displayhtml .='<p class="dashboardcarddata"><span class="cardkey">Active</span> <span class="cardvalue">0</span></p>';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='';
$displayhtml .='<div class="dashboardcard">';
$displayhtml .='<div class="dashboardicon savings"><i class="fa-solid fa-landmark iconsize"></i></div>';
$displayhtml .='<div class="dashboardcontent ">';
$displayhtml .='<h6 class="dashboardcardheader">SAVINGS</h6>';
$displayhtml .='<p class="dashboardcarddata"><span class="cardkey">Total</span> <span class="cardvalue">7</span></p>';
$displayhtml .='<p class="dashboardcarddata"><span class="cardkey">Active</span> <span class="cardvalue">0</span></p>';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='';
$displayhtml .='<div class="dashboardcard">';
$displayhtml .='<div class="dashboardicon consumable"><i class="fa-solid fa-users iconsize"></i></div>';
$displayhtml .='<div class="dashboardcontent">';
$displayhtml .='<h6 class="dashboardcardheader">INVENTORY CONSUMABLE</h6>';
$displayhtml .='<p class="dashboardcarddata"><span class="cardkey">Total</span> <span class="cardvalue">7</span></p>';
$displayhtml .='<p  class="dashboardcarddata"><span class="cardkey">Active</span> <span class="cardvalue">0</span></p>';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='';
$displayhtml .='<div class="dashboardcard">';
$displayhtml .='<div class="dashboardicon nonconsumable"><i class="fa-solid fa-book iconsize"></i></div>';
$displayhtml .='<div class="dashboardcontent">';
$displayhtml .='<h6 class="dashboardcardheader">INVENTORY NON-CONSUMABLE</h6>';
$displayhtml .='<p class="dashboardcarddata"><span class="cardkey">Total</span> <span class="cardvalue">7</span></p>';
$displayhtml .='<p  class="dashboardcarddata"><span class="cardkey">Active</span> <span class="cardvalue">0</span></p>';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='';
$displayhtml .='<div class="dashboardcard">';
$displayhtml .='<div class="dashboardicon property"><i class="fa-sharp fa-solid fa-house iconsize"></i></div>';
$displayhtml .='<div class="dashboardcontent">';
$displayhtml .='<h6 class="dashboardcardheader">PROPERTY ACCOUNT</h6>';
$displayhtml .='<p class="dashboardcarddata"><span class="cardkey">Total</span> <p id="mPropertyAccounts" class="cardvalue">7</p></p>';
$displayhtml .='<p  class="dashboardcarddata"><span class="cardkey">Active</span> <span class="cardvalue">0</span></p>';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='</div>'; 
$displayhtml .='<div>';
$displayhtml .='<div style="height: 45px; border: none">'; 
$displayhtml .='<select name="" id="threedselectyear">';
$displayhtml .='<option>FULL YEAR</option>';
$displayhtml .='<option>1ST HALF OF THE YEAR</option>';
$displayhtml .='<option>2ND HALF OF THE YEAR</option>';
$displayhtml .='<option>1ST QUARTER OF THE YEAR</option>';
$displayhtml .='<option>2ND QUARTER OF THE YEAR</option>';
$displayhtml .='<option>3RD QUARTER OF THE YEAR</option>';
$displayhtml .='<option>LAST QUARTER OF THE YEAR</option>';
$displayhtml .='</select>';
$displayhtml .='</div>';
$displayhtml .='<canvas id="myChart"></canvas>';
$displayhtml .='</div>';
$displayhtml .='</div>';

echo $displayhtml;
?>