<?php
session_start();

$displayhtml .= '<div class="orecontainer">';
$displayhtml .= '<div class="oresubcontianer">';
$displayhtml .= '<div class="oremainheadercontainer">';
$displayhtml .= '<p class="oremainheader">MONTHLY SALARY SHEDULE</p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="orecardcontainer">';
$displayhtml .= '<div class="msscontainer">';
$displayhtml .= '<div class="msstableheader">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="msstablebodycontainer">';
$displayhtml .= '<div class="msstablebody">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="msstablebody">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="msstablebody">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="msstablebody">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="msstablebody">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="msstablebody">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="msstablebody">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="msstablebody">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="msstablebody">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="msstablebody">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="msstablebody">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="msstablebody">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="msstablebody">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="msstablebody">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="msstablebody">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="msstablebody">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="msstablebody">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="msstablebody">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="msstablebody">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="msstablebody">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="msstablebody">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="msstablebody">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="msstablebody">';
$displayhtml .= '<p>ID No.</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Department</p>';
$displayhtml .= '<p>levels</p>';
$displayhtml .= '<p>Basic</p>';
$displayhtml .= '<p>Benefit</p>';
$displayhtml .= '<p>Bonus</p>';
$displayhtml .= '<p>Loan Monthly Debuct</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Surcharges</p>';
$displayhtml .= '<p>....</p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

echo  $displayhtml;
?>