<?php
session_start();

$displayhtml .= '<div class="orecontainer">';
$displayhtml .= '<div class="oresubcontianer">';
$displayhtml .= '<div class="oremainheadercontainer">';
$displayhtml .= '<p class="oremainheader">MONTHLY TRANSACTION WINDOW</p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="orecardcontainer">';
$displayhtml .= '<div class="pldlsubcontainer">';
$displayhtml .= '<div class="inputcontainermsn icsnf">';
$displayhtml .= '<p class="normaltext">Select Month:</p>';
$displayhtml .= '<select>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsnf">';
$displayhtml .= '<p class="normaltext">Year:</p>';
$displayhtml .= '<select>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsnf">';
$displayhtml .= '<p class="normaltext">NAME</p>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="stcnsection1">';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<p>N</p>';
$displayhtml .= '<div class="pldlsubcontainer2">';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext">Total Cash Transaction:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext">Loss Concession Amount:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerln icsnf">';
$displayhtml .= '<p class="normaltext"></p>';
$displayhtml .= '<input type="text" class="mla">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext">Profit on cash Transaction:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext">Profit on Concession Transaction:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext">Registration Fees:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext">Replacement Fees:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext">Renewal Fees:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext">TOTAL RRR FEES:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<p class="oresubheader red">Expenditure</p>';
$displayhtml .= '<div class="mtwsmalltableheader">';
$displayhtml .= '<p>Particular</p>';
$displayhtml .= '<p>Debit</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="mtwsmalltablebody">';
$displayhtml .= '<p>Salary</p>';
$displayhtml .= '<p>N 4,343,344.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="stcnsection1">';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<div class="pldlsubcontainer2">';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext">TOTAL OPERATING INCOME:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext">NET TOTAL:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<div class="pldlsubcontainer2">';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext red">BANK CHARGES:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext red">TOTAL OPERATING EXPENSE:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<p class="oresubheader">Deduction Submenu</p>';
$displayhtml .= '<div class="stcnsection1">';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<div class="pldlsubcontainer2">';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext red">CASH WITHDRAWAL:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext red">E-WITHDRAWAL:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext red">PROPERTY WITHDRAWAL:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext red">TOTAL WITHDRAWAL:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsnf">';
$displayhtml .= '<p class="normaltext red">BANK DEPOSIT</p>:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<P>NAME</P>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<!--  -->';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

echo  $displayhtml;
?>