<?php
session_start();

$displayhtml .= '<div class="formcontainer overflowcontainer">';
$displayhtml .= '<div class="formheader">';
$displayhtml .= '<h5>NET TRANSACTION ENTRY </h5>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="formmain ">';
$displayhtml .= '<div class="formsection">';
$displayhtml .= '<div class="split3">';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="transactiondate">Transaction Date</label>';
$displayhtml .= '<input type="date" name="transacttiondate" id="mattransactiondate" >';
$displayhtml .= '</div>';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="branch">Branch</label>';
$displayhtml .= '<input type="text" name="branch" id="matentrybranch">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="selectnexttransactiondate">Select Next Transaction Date</label>';
$displayhtml .= '<input type="date" name="selectnexttransactiondate" id="matselectnexttransactiondate">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class=" wrapbtn ">';
$displayhtml .= '<button type="submit" class="btnmedium btn btnblue">';
$displayhtml .= 'Update';
$displayhtml .= '</button>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="split">';
$displayhtml .= '<div class="formsection">';
$displayhtml .= '<p class="topformsection">CREDIT ENTRIES</p>';
$displayhtml .= '<div class="split">';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="balancebroughtforward">Balance Brought forward</label>';
$displayhtml .= '<input type="number" name="balancebroughtforward" id="matcreditbalancebroughtforward">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="dailydeposit">Daily Deposit</label>';
$displayhtml .= '<input type="number" name="dailydeposit" id="matcreditdailydeposit">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="split">';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="dailyrrr">Daily R/R/R</label>';
$displayhtml .= '<input type="number" name="dailyrrr" id="matcreditdailyrrr">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="cashfrombank">Cash From Bank  </label>';
$displayhtml .= '<input type="text" name="cashfrombank" id="matcreditcashfrombank">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="split">';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="cashfrombranch">Cash from Branch</label>';
$displayhtml .= '<input type="text" name="cashfrombranch" id="matcreditcashfrombranch" >';
$displayhtml .= '</div>';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="excess">Excess</label>';
$displayhtml .= '<input type="number" name="excess" id="matcreditexcess">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="split">';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="loanrepayment">Loan Repayment</label>';
$displayhtml .= '<input type="number" name="loanrepayment" id="matcreditloanrepayment" >';
$displayhtml .= '</div>';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="returncash">Return Cash</label>';
$displayhtml .= '<input type="number" name="returncash" id="matcreditreturncash">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="split">';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="cashproperty">Cash Property</label>';
$displayhtml .= '<input type="number" name="cashproperty" id="matcreditcashproperty">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="totalcredit">Total Credit</label>';
$displayhtml .= '<input type="number" name="totalcredit" id="matcredittotalcredit">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="formsection">';
$displayhtml .= '<p class="topformsection"> Debit Entries </p>';
$displayhtml .= '<div class="split">';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="dailyexpense">Daily Expense</label>';
$displayhtml .= '<input type="number" name="dailyexpense" id="matdebitdailyexpense">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="cashpayment">Cash Payment</label>';
$displayhtml .= '<input type="number" name="cashpayment" id="matdebitcashpayment">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="split">';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="paymentbybank">Payment By Bank</label>';
$displayhtml .= '<input type="number" name="paymentbybank" id="matdebitpaymentbybank">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="cashtobank">Cash to Bank</label>';
$displayhtml .= '<input type="number" name="cashtobank" id="matdebitcashtobank">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="split">';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="cashtobranch">Cash To Branch</label>';
$displayhtml .= '<input type="number" name="cashtobranch" id="matdebitcashtobranch" >';
$displayhtml .= '</div>';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="nia">NIA</label>';
$displayhtml .= '<input type="text" name="nia" id="matdebitnia">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="split">';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="returncash">Return Cash(Payment)</label>';
$displayhtml .= '<input type="number" name="returncash" id="matdebitreturncash" >';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="totaldebit">Total Debit</label>';
$displayhtml .= '<input type="number" name="totaldebit" id="matdebittotaldebit">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '<div class="formsection centerdiv">';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="netbalance">Net Balance</label>';
$displayhtml .= '<input type="text" name="netbalance" id="matnetbalance">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class=" wrapbtn btncenter">';
$displayhtml .= '<button type="submit" class="btnmedium btn btnblue" id="matNetTransactionentry">';
$displayhtml .= 'Reverse Posting';
$displayhtml .= '</button>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';

echo $displayhtml;
?>