<?php
echo '<div class="jcontainer">';
echo '<div>';
echo '<h1 class="jpageheader"> no repayments </h1>';
echo '</div>';
echo '<div class="jpagecontent" id="jpagecontent">';
echo '<div>';
echo '<form class="jformgroup" id="norepaymentform">';
echo '<div class="col-form-group jformgroup" >';
echo '<div class="jflex">';
echo '<div class="jformgroup jformgroupcol">';
echo '<label class="jcontrollabel"> start date: </label>';
echo '<input type="date" class="jformcontrol jmargin-top" id="nrlstartdate" name="startdate">';
echo '</div>';
echo '<div class="jformgroup jformgroupcol jmargin-left">';
echo '<label class="jcontrollabel"> end date: </label>';
echo '<input type="date" class="jformcontrol jmargin-top" id="nrlenddate" name="enddate">';
echo '</div>';
echo '<div class="jformgroup jformgroupcol jmargin-left">';
echo '<label class="jcontrollabel"> location: </label>';
echo '<input list="loanlocations" class="jformcontrol jmargin-top" id="nrllocation">';
echo '</div>';
echo '</div>';
echo '<div class="jflex jitems-left" >';
echo '<div class="jflex jitems-left" style="width: 100%;">';
echo '<button type="button" class="j-action-btn"';
echo 'style="width: 15%;text-transform: capitalize;background-color: rgb(34, 33, 33);"';
echo 'id="filter-nr">filter</button>&nbsp;';
echo '<button type="button" class="j-action-btn" style="width: 15%;text-transform: capitalize;"';
echo 'id="print-nr">print</button>&nbsp;';
echo '<button type="button" class="j-action-btn"';
echo 'style="width: 15%;text-transform: capitalize;background-color: rgb(2, 77, 30);"';
echo 'id="export-nr">report</button>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</form>';
echo '</div>';
echo '<div class="jmargin-top" style="margin-top: 40px">';
echo '<div class="jtable-content">';
echo '<table class="jmargin-top" id="norepaymentstable">';
echo '<thead>';
echo '<tr>';
echo '<th>s/n </th>';
echo '<th> account number </th>';
echo '<th> account name  </th>';
echo '<th> due date </th>';
echo '<th> amount</th>';
echo '<th> status</th>';
echo '</tr>';
echo '</thead>';
echo '<tbody id="jtabledata"></tbody>';
echo '</table>';
echo '</div>';
echo '<div class="j-table-status jflex jcontent-between jmargin-top no-pr">';
echo '<span class="jcontrollabel" style="text-transform: none" id="pagination-status"> </span>';
echo '<span class="jflex jcontent-between">';
echo '<span>';
echo '<select id="pagination-limit" class="jmargin-left jformcontrol jmargin-right">';
echo '<option value="40">40</option>';
echo '<option value="70">50</option>';
echo '<option value="100">100</option>';
echo '<option value="150">150</option>';
echo '<option value="200">200</option>';
echo '<option value="250">250</option>';
echo '<option value="500">500</option>';
echo '<option value="750">750</option>';
echo '<option value="1000">1000</option>';
echo '<option value="1500">1500</option>';
echo '</select>';
echo '</span>';
echo '<span class="jflex jpagination">';
echo '<button class="j-no-bg" type="button" id="jprev-button">previous</button>';
echo '<span id="pagination-numbers"></span>';
echo '<button  class="j-no-bg" type="button" id="jnext-button">next</button>';
echo '</span>';
echo '</span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
?>