<?php
$displayhtml .='<div class="jcontainer">';
$displayhtml .='<div>';
$displayhtml .='<h1 class="jpageheader"> past maturity date </h1>';
$displayhtml .='</div>';
$displayhtml .='<div class="jpagecontent" id="jpagecontent">';
$displayhtml .='<div class="jmargin-top">';
$displayhtml .='<div class="jtable-content">';
$displayhtml .='<table class="jmargin-top" id="pastmaturityloanstable">';
$displayhtml .='<thead>';
$displayhtml .='<tr>';
$displayhtml .='<th>s/n </th>';
$displayhtml .='<th> account&nbsp;number </th>';
$displayhtml .='<th> account&nbsp;name  </th>';
$displayhtml .='<th> opening&nbsp;date </th>';
$displayhtml .='<th> maturity&nbsp;date </th>';
$displayhtml .='<th> loan&nbsp;type </th>';
$displayhtml .='<th> loan&nbsp;duration </th>';
$displayhtml .='<th> amount </th>';
$displayhtml .='<th> loan&nbsp;officer </th>';
$displayhtml .='<th> interest&nbsp;rate </th>';
$displayhtml .='<th> interest&nbsp;type </th>';
$displayhtml .='<th> interest&nbsp;period </th>';
$displayhtml .='<th> interest&nbsp;method </th>';
$displayhtml .='<th> reference&nbsp;number </th>';
$displayhtml .='<th> installment&nbsp;amount </th>';
$displayhtml .='<th> location </th>';
$displayhtml .='<th> status </th>';
$displayhtml .='</tr>';
$displayhtml .='</thead>';
$displayhtml .='<tbody id="jtabledata"></tbody>';
$displayhtml .='</table>';
$displayhtml .='</div>';
$displayhtml .='<div class="j-table-status jflex jcontent-between jmargin-top">';
$displayhtml .='<span class="jcontrollabel" style="text-transform: none" id="pagination-status"> </span>';
$displayhtml .='<span class="jflex jcontent-between">';
$displayhtml .='<span>';
$displayhtml .='<select id="pagination-limit" class="jmargin-left jformcontrol jmargin-right">';
$displayhtml .='<option value="20">20</option>';
$displayhtml .='<option value="50">50</option>';
$displayhtml .='<option value="100">100</option>';
$displayhtml .='<option value="150">150</option>';
$displayhtml .='<option value="200">200</option>';
$displayhtml .='<option value="250">250</option>';
$displayhtml .='<option value="500">500</option>';
$displayhtml .='<option value="750">750</option>';
$displayhtml .='<option value="1000">1000</option>';
$displayhtml .='<option value="1500">1500</option>';
$displayhtml .='</select>';
$displayhtml .='</span>';
$displayhtml .='<span class="jflex jpagination">';
$displayhtml .='<button class="j-no-bg" type="button" id="jprev-button">previous</button>';
$displayhtml .='<span id="pagination-numbers"></span>';
$displayhtml .='<button  class="j-no-bg" type="button" id="jnext-button">next</button>';
$displayhtml .='</span>';
$displayhtml .='</span>';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='</div>';
$displayhtml .='</div>';
echo $displayhtml;
?>