<?php
$displayhtml .= '<div class="orecontainer">';
$displayhtml .= '<div class="oresubcontianer">';
$displayhtml .= '<div class="oremainheadercontainer">';
$displayhtml .= '<p class="oremainheader">PERSONAL LEDGER: <span>WARRI</span></p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="orecardcontainer">';
$displayhtml .= '<div class="stcnsection1">';
$displayhtml .= '<div class="stcs1a30">';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Enter Account Number</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= "<p class='oresubheader'>Depositor's Profile</p>";
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">First Name </p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Last Name </p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Middle Name </p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Phone Number</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">Last Active Date</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Reg. Branch</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Account Type</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">Gender</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Date Opened</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Act Open Officer</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">Account Group</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Online User</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Transaction Point</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">Agreed Deposit</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Balance</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="orecentercontainer">';
$displayhtml .= '<div class="orerbtn">Print</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcs1a70">';
$displayhtml .= '<div class="pldleftcontainer">';
$displayhtml .= '<div class="pldlsubcontainer">';
$displayhtml .= '<div class="inputcontainermsn icsnf">';
$displayhtml .= '<p class="normaltext">Total Deposit:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsnf">';
$displayhtml .= '<p class="normaltext">Total Withdrawal:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsnf">';
$displayhtml .= '<p class="normaltext">Total Reverse:</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsnf">';
$displayhtml .= '<p class="normaltext">Select Month:</p>';
$displayhtml .= '<select>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '</select>';
$displayhtml .= '<select>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pldcontainer">';
$displayhtml .= '<div class="pldtableheader">';
$displayhtml .= '<p>Full Names</p>';
$displayhtml .= '<p>Act Officer</p>';
$displayhtml .= '<p>Posted By</p>';
$displayhtml .= '<p>Deposit</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Reverse Deposit</p>';
$displayhtml .= '<p>Withdrawal</p>';
$displayhtml .= '<p>Service Charge</p>';
$displayhtml .= '<p>Transfer Amount</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pldtablebodycontainer">';
$displayhtml .= '<div class="pldtablebody">';
$displayhtml .= '<p>Full Names</p>';
$displayhtml .= '<p>Act Officer</p>';
$displayhtml .= '<p>Posted By</p>';
$displayhtml .= '<p>Deposit</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Reverse Deposit</p>';
$displayhtml .= '<p>Withdrawal</p>';
$displayhtml .= '<p>Service Charge</p>';
$displayhtml .= '<p>Transfer Amount</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pldtablebody">';
$displayhtml .= '<p>Full Names</p>';
$displayhtml .= '<p>Act Officer</p>';
$displayhtml .= '<p>Posted By</p>';
$displayhtml .= '<p>Deposit</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Reverse Deposit</p>';
$displayhtml .= '<p>Withdrawal</p>';
$displayhtml .= '<p>Service Charge</p>';
$displayhtml .= '<p>Transfer Amount</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pldtablebody">';
$displayhtml .= '<p>Full Names</p>';
$displayhtml .= '<p>Act Officer</p>';
$displayhtml .= '<p>Posted By</p>';
$displayhtml .= '<p>Deposit</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Reverse Deposit</p>';
$displayhtml .= '<p>Withdrawal</p>';
$displayhtml .= '<p>Service Charge</p>';
$displayhtml .= '<p>Transfer Amount</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pldtablebody">';
$displayhtml .= '<p>Full Names</p>';
$displayhtml .= '<p>Act Officer</p>';
$displayhtml .= '<p>Posted By</p>';
$displayhtml .= '<p>Deposit</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Reverse Deposit</p>';
$displayhtml .= '<p>Withdrawal</p>';
$displayhtml .= '<p>Service Charge</p>';
$displayhtml .= '<p>Transfer Amount</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pldtablebody">';
$displayhtml .= '<p>Full Names</p>';
$displayhtml .= '<p>Act Officer</p>';
$displayhtml .= '<p>Posted By</p>';
$displayhtml .= '<p>Deposit</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Reverse Deposit</p>';
$displayhtml .= '<p>Withdrawal</p>';
$displayhtml .= '<p>Service Charge</p>';
$displayhtml .= '<p>Transfer Amount</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pldtablebody">';
$displayhtml .= '<p>Full Names</p>';
$displayhtml .= '<p>Act Officer</p>';
$displayhtml .= '<p>Posted By</p>';
$displayhtml .= '<p>Deposit</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Reverse Deposit</p>';
$displayhtml .= '<p>Withdrawal</p>';
$displayhtml .= '<p>Service Charge</p>';
$displayhtml .= '<p>Transfer Amount</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pldtablebody">';
$displayhtml .= '<p>Full Names</p>';
$displayhtml .= '<p>Act Officer</p>';
$displayhtml .= '<p>Posted By</p>';
$displayhtml .= '<p>Deposit</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Reverse Deposit</p>';
$displayhtml .= '<p>Withdrawal</p>';
$displayhtml .= '<p>Service Charge</p>';
$displayhtml .= '<p>Transfer Amount</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pldtablebody">';
$displayhtml .= '<p>Full Names</p>';
$displayhtml .= '<p>Act Officer</p>';
$displayhtml .= '<p>Posted By</p>';
$displayhtml .= '<p>Deposit</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Reverse Deposit</p>';
$displayhtml .= '<p>Withdrawal</p>';
$displayhtml .= '<p>Service Charge</p>';
$displayhtml .= '<p>Transfer Amount</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pldtablebody">';
$displayhtml .= '<p>Full Names</p>';
$displayhtml .= '<p>Act Officer</p>';
$displayhtml .= '<p>Posted By</p>';
$displayhtml .= '<p>Deposit</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Reverse Deposit</p>';
$displayhtml .= '<p>Withdrawal</p>';
$displayhtml .= '<p>Service Charge</p>';
$displayhtml .= '<p>Transfer Amount</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pldtablebody">';
$displayhtml .= '<p>Full Names</p>';
$displayhtml .= '<p>Act Officer</p>';
$displayhtml .= '<p>Posted By</p>';
$displayhtml .= '<p>Deposit</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Reverse Deposit</p>';
$displayhtml .= '<p>Withdrawal</p>';
$displayhtml .= '<p>Service Charge</p>';
$displayhtml .= '<p>Transfer Amount</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pldtablebody">';
$displayhtml .= '<p>Full Names</p>';
$displayhtml .= '<p>Act Officer</p>';
$displayhtml .= '<p>Posted By</p>';
$displayhtml .= '<p>Deposit</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Reverse Deposit</p>';
$displayhtml .= '<p>Withdrawal</p>';
$displayhtml .= '<p>Service Charge</p>';
$displayhtml .= '<p>Transfer Amount</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="pldtablebody">';
$displayhtml .= '<p>Full Names</p>';
$displayhtml .= '<p>Act Officer</p>';
$displayhtml .= '<p>Posted By</p>';
$displayhtml .= '<p>Deposit</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Reverse Deposit</p>';
$displayhtml .= '<p>Withdrawal</p>';
$displayhtml .= '<p>Service Charge</p>';
$displayhtml .= '<p>Transfer Amount</p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="pldtablebody">';
$displayhtml .= '<p>Full Names</p>';
$displayhtml .= '<p>Act Officer</p>';
$displayhtml .= '<p>Posted By</p>';
$displayhtml .= '<p>Deposit</p>';
$displayhtml .= '<p>NIA</p>';
$displayhtml .= '<p>Reverse Deposit</p>';
$displayhtml .= '<p>Withdrawal</p>';
$displayhtml .= '<p>Service Charge</p>';
$displayhtml .= '<p>Transfer Amount</p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="orecentercontainer mtt">';
$displayhtml .= '<div class="orerbtn">Reconcile</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

echo  $displayhtml;
?>