<?php
session_start(); 

$displayhtml .= '<div class="jcontainer">';
$displayhtml .= '<input class="jformcontrol jmargin-top pervfy" type="hidden" id="id">';
$displayhtml .= '<h1 class="jpageheader">PERSONNNEL</h1>';
$displayhtml .= '<div class="jpagecontent" id="jpagecontent">';
$displayhtml .= '<div>';
$displayhtml .= '<div class="section-header mbb" style="display:flex; gap:6px; align-items:center;">';
$displayhtml .= '<h3>BIO DATA</h3>';
$displayhtml .= '</div>';
$displayhtml .= '<form class="jform" id ="">';
$displayhtml .= '<div class="jformgroup">
                    <div class="file-area"></div>
                </div>
                <div class="jformgroup" style="margin-bottom: 10px">
                    <div class="jformgroup jformgroupcol file-action">
                        <input type="file" placeholder="Enter title" class="jformcontrol jmargin-top hidden" id="document">
                        <div class="">
                            <p>click to add profile image and signature in one scan</p>
                            <p style="text-transform: none;font-weight: 400;font-size: x-small;">.png | .jpeg | .jpg and upload size should not be more than 200kb</p>
                        </div>
                    </div>
                </div>
                <div class="col-form-group" >';
$displayhtml .= '<div class="jformgroup jformgroup form_row">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label  class="jcontrollabel">Last name</label>';
$displayhtml .= '<input class="jformcontrol jmargin-top pervfy" name="" id="personellastname" required>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol  jmargin-left">';
$displayhtml .= '<label  class="jcontrollabel">first Name</label>';
$displayhtml .= '<input class="jformcontrol jmargin-top pervfy" type="text" id="personelfirstname" required>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol  jmargin-left">';
$displayhtml .= '<label  class="jcontrollabel">other names</label>';
$displayhtml .= '<input class="jformcontrol jmargin-top pervfy" name="" id="personelothernames" required>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroup form_row">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label  class="jcontrollabel">phone number</label>';
$displayhtml .= '<input class="jformcontrol jmargin-top pervfy" type="tel" id="personelphonenumber" required>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol  jmargin-left">';
$displayhtml .= '<label  class="jcontrollabel">work status</label>';
$displayhtml .= '<input class="jformcontrol jmargin-top pervfy" name="" id="personelworkstatus" required>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol  jmargin-left">';
$displayhtml .= '<label  class="jcontrollabel">marital status</label>';
$displayhtml .= '<select class="jformcontrol jmargin-top pervfy" name="" id="personelmaritalstatus" required>';
$displayhtml .= '<option value=""> -- Select Status --</option>';
$displayhtml .= '<option> SINGLE </option>';
$displayhtml .= '<option> MARRIED </option>';
$displayhtml .= '<option> SEPERATED </option>';
$displayhtml .= '<option> WIDOW </option>';
$displayhtml .= '<option> WIDOWER </option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroup form_row">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label  class="jcontrollabel">residential address</label>';
$displayhtml .= '<input class="jformcontrol jmargin-top pervfy" type="text" id="personelresidentialaddress" required>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol  jmargin-left">';
$displayhtml .= '<label  class="jcontrollabel">permanent home address</label>';
$displayhtml .= '<input class="jformcontrol jmargin-top pervfy" name="" id="personelpermanenthome" required>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol  jmargin-left">';
$displayhtml .= '<label  class="jcontrollabel">gender</label>';
$displayhtml .= '<select class="jformcontrol jmargin-top pervfy" name="" id="personelgender" required>';
$displayhtml .= '<option value="">--select gender--</option>';
$displayhtml .= '<option>MALE</option>';
$displayhtml .= '<option>FEMALE</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div style="margin-top:20px"></div>';
$displayhtml .= '<div class="section-header" style="display:flex; gap:6px; align-items:center;">';
$displayhtml .= '<h1>General details</h1>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div style="background: #195819;display: flex;padding: 20px;border-radius: 14px;" class="jformgroup jformgroup form_row">';
$displayhtml .= '<div class="jformgroup jformgroupcol" style="border-radius: 9px;">';
$displayhtml .= '<label style="color: white; font-weight: bolder;" class="jcontrollabel">Account Number </label>';
$displayhtml .= '<input value="" class="jformcontrol jmargin-top" style="width: 200px;border: none;background: #195819;border-bottom:2px solid white;color: white !important;" list="" type="text" style="color: white; font-weight: bolder;"id="personnelh2gaccountnumber" readonly required>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label style="color: white; font-weight: bolder;" class="jcontrollabel">Bank Account No. [Basic]</label>';
$displayhtml .= '<input value="" class="jformcontrol jmargin-top" style="width: 200px;background: white;border:2px solid white;color: #195819 !important;" list="" type="text" style="color: white; font-weight: bolder;"id="personnelaccountnumber1" required>';
$displayhtml .= '<label style="color: white; font-weight: bolder;" class="jcontrollabel mtt">Bank Name</label>';
$displayhtml .= '<input value="" class="jformcontrol jmargin-top" style="width: 200px;background: white;border:2px solid white;color: #195819 !important;" list="" type="text" style="color: white; font-weight: bolder;"id="personnelbankname1" required>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label style="color: white; font-weight: bolder;" class="jcontrollabel">Bank Account No. [allowances]</label>';
$displayhtml .= '<input value="" class="jformcontrol jmargin-top" style="width: 200px;background: white;border:2px solid white;color: #195819 !important;" list="" type="text" style="color: white; font-weight: bolder;"id="personnelaccountnumber2" required>';
$displayhtml .= '<label style="color: white; font-weight: bolder;" class="jcontrollabel mtt">Bank Name</label>';
$displayhtml .= '<input value="" class="jformcontrol jmargin-top" style="width: 200px;background: white;border:2px solid white;color: #195819 !important;" list="" type="text" style="color: white; font-weight: bolder;"id="personnelbankname2" required>';
$displayhtml .= '</div>';
$displayhtml .= '</div>'; 
$displayhtml .= '<div class="jformgroup jformgroup form_row">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label  class="jcontrollabel">Username/Email</label>';
$displayhtml .= '<input class="jformcontrol jmargin-top pervfy" list="personelallemail" type="text" id="personelusernameemail" onchange="checkdatalist(this)" required>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
$displayhtml .= '<label  class="jcontrollabel">Department</label>';
$displayhtml .= '<select class="jformcontrol jmargin-top pervfy" name="" id="personeldepartment" required>';
$displayhtml .= '<option value="">--select--</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroup form_row">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label  class="jcontrollabel">birth date</label>';
$displayhtml .= '<input class="jformcontrol jmargin-top pervfy" type="date" id="personelbirthdate" required>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
$displayhtml .= '<label  class="jcontrollabel">nationality</label>';
$displayhtml .= '<input class="jformcontrol jmargin-top pervfy" type="text" onfocusout="personnelgetstate(this)" list="orecountry" id="personnelnationalityy" required>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol  jmargin-left">';
$displayhtml .= '<label  class="jcontrollabel">state</label>';
$displayhtml .= '<input class="jformcontrol jmargin-top pervfy" onfocusout="personnelgetcity(this)" name="" id="personelstate" list="orestate" required>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol  jmargin-left">';
$displayhtml .= '<label  class="jcontrollabel">lga</label>';
// $displayhtml .= '<input class="jformcontrol jmargin-top pervfy" name="" onfocusout="personnelgetlga(this)" id="" list="orelga" required>';
$displayhtml .= '<input class="jformcontrol jmargin-top pervfy" name="" id="personellga" list="orelga" required>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroup form_row">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label  class="jcontrollabel">deformity</label>';
$displayhtml .= '<select class="jformcontrol jmargin-top pervfy" name="" id="personeldeformity" required>';
$displayhtml .= '<option value="">--select--</option>';
$displayhtml .= '<option value="0">NO</option>';
$displayhtml .= '<option value="1">YES</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol  jmargin-left">';
$displayhtml .= '<label  class="jcontrollabel">eye glasses</label>';
$displayhtml .= '<select class="jformcontrol jmargin-top pervfy" name="" id="personeleyeglasses" required>';
$displayhtml .= '<option value="">--select--</option>';
$displayhtml .= '<option value="0">NO</option>';
$displayhtml .= '<option value="1">YES</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol  jmargin-left">';
$displayhtml .= '<label  class="jcontrollabel">Hearing Aid</label>';
$displayhtml .= '<select class="jformcontrol jmargin-top pervfy" name="" id="personelotherdeformity" required>';
$displayhtml .= '<option value="">--select--</option>';
$displayhtml .= '<option value="0">NO</option>';
$displayhtml .= '<option value="1">YES</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol  jmargin-left">';
$displayhtml .= '<label  class="jcontrollabel">height</label>';
$displayhtml .= '<input type="number" class="jformcontrol jmargin-top pervfy" name="" id="personelheight" required>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroup form_row">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label  class="jcontrollabel">weight</label>';
$displayhtml .= '<input type="number" class="jformcontrol jmargin-top pervfy" name="" id="personelweight" required>';
$displayhtml .= '</div>';
// $displayhtml .= '<div class="jformgroup jformgroupcol  jmargin-left">';
// $displayhtml .= '<label  class="jcontrollabel">bank</label>';
// $displayhtml .= '<input type="text" class="jformcontrol jmargin-top pervfy" name="" id="personelbank" required>';
// $displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol  jmargin-left">';
$displayhtml .= '<label  class="jcontrollabel">employment date</label>';
$displayhtml .= '<input type="date" class="jformcontrol jmargin-top pervfy" name="" id="personelemplymentdate" required>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroup form_row">';
$displayhtml .= '<div class="jformgroup jformgroupcol hidden">';
$displayhtml .= '<label  class="jcontrollabel">Basic Salary</label>';
$displayhtml .= '<input type="text" class="jformcontrol jmargin-top" name="" id="personelbasicsalary" required>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label  class="jcontrollabel">Level</label>';
$displayhtml .= '<select class="jformcontrol jmargin-top pervfy" name="" id="personellevel" required>';
$displayhtml .= '<option value="">--select--</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol  jmargin-left">';
$displayhtml .= '<label  class="jcontrollabel">Group</label>';
$displayhtml .= '<select class="jformcontrol jmargin-top pervfy" name="" id="personelgroup" required>';
$displayhtml .= '<option value="">--select--</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jflex" style="margin: 30px 0;">';
$displayhtml .= '<button type="button" style="padding:10px; min-width: 15%; text-transform: capitalize" class="j-action-btn" id="personelsubmit"> Submit </button>';
$displayhtml .= '</div>';
$displayhtml .= '</form>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<datalist id="orecountry"></datalist>';
$displayhtml .= '<datalist id="orestate"></datalist>';
$displayhtml .= '<datalist id="orelga"></datalist>';
$displayhtml .= '<datalist id="personelallemail"></datalist>';

echo $displayhtml;
?>

<!--
$displayhtml .= '<div class="jformgroup jformgroupcol  jmargin-left hidden">';
// $displayhtml .= '<label  class="jcontrollabel"></label>';
// $displayhtml .= '<input type="date" class="jformcontrol jmargin-top pervfy" name="" id="" required>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="section-header mtt" style="display:flex; gap:6px;margin-top: 30px; align-items:center;">';
$displayhtml .= '<h1>Allowances</h1>';
$displayhtml .= '</div>';

$displayhtml .= '<div name="allowancepersonnelcontainer">';
$displayhtml .= '<div class="jformgroup jformgroup form_row">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<input class="jformcontrol jmargin-top pervfy allowancename" type="text" id="allowancename0" placeholder="Allowance name" required>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
$displayhtml .= '<input class="jformcontrol jmargin-top pervfy allowancepercent" type="number" id="allowancepercent0" placeholder="Percentage %" required>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
$displayhtml .= '<div id="personneladdallowance" style="font-size: small;" class="mt oreadddebit1"> Add More </div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

$displayhtml .= '<div id="allowancepersonnelcontainer">';
// $displayhtml .= '<div name="allowancepersonnelcontainer">';
// $displayhtml .= '<div class="jformgroup jformgroup form_row">';
// $displayhtml .= '<div class="jformgroup jformgroupcol">'; 
// $displayhtml .= '<input class="jformcontrol jmargin-top pervfy" type="text" id="" placeholder="Allowance name" required>';
// $displayhtml .= '</div>';
// $displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
// $displayhtml .= '<input class="jformcontrol jmargin-top pervfy" type="text" id="" placeholder="Percentage %" required>';
// $displayhtml .= '</div>';
// $displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
// $displayhtml .= '<div id="" class="oreadddebit oreremove mt" onclick="this.parentElement.parentElement.parentElement.remove();">Remove</div>';
// $displayhtml .= '</div>';
// $displayhtml .= '</div>';
// $displayhtml .= '</div>';

$displayhtml .= '</div>';
$displayhtml .= '</div>'; 
$displayhtml .= '<div class="section-header mtt" style="display:flex; gap:6px;margin-top: 30px; align-items:center;">';
$displayhtml .= '<h1>Deductions</h1>';
$displayhtml .= '</div>';

$displayhtml .= '<div name="deductionspersonnelcontainer">';
$displayhtml .= '<div class="jformgroup jformgroup form_row">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<input class="jformcontrol jmargin-top pervfy deductionname" type="text" id="deductionname0" placeholder="Deductions name" required>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
$displayhtml .= '<input class="jformcontrol jmargin-top pervfy deductionpecent" type="number" id="deductionpecent0" placeholder="Percentage %" required>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
$displayhtml .= '<div id="personneladddeductions" style="font-size: small;margin-left: 0px" class="mt oreadddebit1"> Add More </div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

$displayhtml .= '<div id="deductionspersonnelcontainer">';
// $displayhtml .= '<div name="allowancepersonnelcontainer">';
// $displayhtml .= '<div class="jformgroup jformgroup form_row">';
// $displayhtml .= '<div class="jformgroup jformgroupcol">'; 
// $displayhtml .= '<input class="jformcontrol jmargin-top pervfy" type="text" id="" placeholder="Allowance name" required>';
// $displayhtml .= '</div>';
// $displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
// $displayhtml .= '<input class="jformcontrol jmargin-top pervfy" type="text" id="" placeholder="Percentage %" required>';
// $displayhtml .= '</div>';
// $displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
// $displayhtml .= '<div id="" class="oreadddebit oreremove mt" onclick="this.parentElement.parentElement.parentElement.remove();">Remove</div>';
// $displayhtml .= '</div>';
// $displayhtml .= '</div>';
// $displayhtml .= '</div>';

$displayhtml .= '</div>';
$displayhtml .= '</div>';-->