<?php
session_start();

$displayhtml .= '<div class="orecontainer">';
$displayhtml .= '<div class="oresubcontianer">';
$displayhtml .= '<div class="oremainheadercontainer">';
$displayhtml .= '<p class="oremainheader">PROPERTY TRANSACTION MONTHLY</p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="orecardcontainer">';
$displayhtml .= '<div class="pldlsubcontainer">';
$displayhtml .= '<div class="inputcontainermsn icsnf">';
$displayhtml .= '<p class="normaltext">Select Month:</p>';
$displayhtml .= '<select>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsnf">';
$displayhtml .= '<p class="normaltext">Year:</p>';
$displayhtml .= '<select>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ptmncontainer">';
$displayhtml .= '<div class="ptmntableheader">';
$displayhtml .= '<p></p>';
$displayhtml .= '<p>PAID</p>';
$displayhtml .= '<p>COST</p>';
$displayhtml .= '<p>DIFFERENCE</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ptmntablebodycontainer">';
$displayhtml .= '<div class="ptmntablebody">';
$displayhtml .= '<p>UGWUAGBA</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ptmntablebody">';
$displayhtml .= '<p>MAIN MARKET</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ptmntablebody">';
$displayhtml .= '<p>RELIEF</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ptmntablebody">';
$displayhtml .= '<p>BRIDGE HEAD</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ptmntablebody">';
$displayhtml .= '<p>AGHANLA</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ptmntablebody">';
$displayhtml .= '<p>PLASTIC</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ptmntablebody">';
$displayhtml .= '<p>BUILDING</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ptmntablebody">';
$displayhtml .= '<p>NKPOR</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ptmntablebody">';
$displayhtml .= '<p>NNEWI</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ptmntablebody">';
$displayhtml .= '<p>TOTAL</p>';
$displayhtml .= '<input type="text" class="bglightblue">';
$displayhtml .= '<input type="text" class="bglightblack">';
$displayhtml .= '<input type="text" class="bglightred">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ptmntablebody mttt">';
$displayhtml .= '<p class="red">EXPENSES</p>';
$displayhtml .= '<input type="text" class="">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="ptmntablebody mttt">';
$displayhtml .= '<p class="blue">NET</p>';
$displayhtml .= '<input type="text" class="">';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '<!--  -->';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

echo  $displayhtml;
?>