<?php
session_start();

$displayhtml .= '<div class="oresubcontianer">';
$displayhtml .= '<div class="oremainheadercontainer">';
$displayhtml .= '<p class="oremainheader">REGISTERED CLIENT DISPLAY</p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="orecardcontainer">';
$displayhtml .= '<div class="rddcontainer">';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Phone Number</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtableheader">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebodycontainer">';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="rddtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<P>Account no.</P>';
$displayhtml .= '<P>Client</P>';
$displayhtml .= '<p>Mobile Number</p>';
$displayhtml .= '<p>Gender</p>';
$displayhtml .= '<p>Account Type</p>';
$displayhtml .= '<p>Date Openned</p>';
$displayhtml .= '<p>Act Open Officer</p>';
$displayhtml .= '<p>Domiciled Branch</p>';
$displayhtml .= '<p>Registered Point</p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

echo  $displayhtml;
?>