<?php
$displayhtml .= '<div class="jcontainer">';
$displayhtml .= '<div>';
$displayhtml .= '<h1 class="jpageheader"> repayment schedule </h1>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jpagecontent" id="jpagecontent">';
$displayhtml .= '<div>';
$displayhtml .= '<form class="jform">';
$displayhtml .= '<div class="section-header no-pr">';
$displayhtml .= '<h1>account info</h1>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jflex" style="align-items:end">';
$displayhtml .= '<div class="jformgroup no-pr">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label class="jcontrollabel"> Enter loan account number  </label>';
$displayhtml .= '<input type="number"';
$displayhtml .= 'class="jformcontrol jmargin-top" id="repaymentaccount" name="repaymentaccount">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jflex jmargin-left no-pr" >';
$displayhtml .= '<button type="button" class="j-action-btn" style="padding: 9px;" id="findaccountbtn">retrieve schedule</button>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div id="scheduleContainer">';
$displayhtml .= '<div class="section-header no-pr">';
$displayhtml .= '<h1 class=" jmargin-top" style="text-align: center;" id="scheduleheader"></h1>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jmargin-top">';
$displayhtml .= '<div class="jtable-content">';
$displayhtml .= '<div class="jflex jitems-left">';
$displayhtml .= '<span>';
$displayhtml .= '<button type="button" class="j-action-btn jborder no-pr" style="border-color: #007bff;text-transform:capitalize;" id="paymentscheduleprintaction">print</button> &nbsp;';
$displayhtml .= '</span>';
$displayhtml .= '</div>';
$displayhtml .= '<table class="jmargin-top" id="repaymentrescheduletable">';
$displayhtml .= '</table>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</form>';
// $displayhtml .= '<div class="j-outer-container" id="jmodal-area">';
// $displayhtml .= '<div class="modal-content" id="modal-content"></div>';
// $displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
echo $displayhtml;
?>