<?php
$displayhtml .= '<div class="jcontainer obs">';
$displayhtml .= '<div>';
$displayhtml .= '<h1 class="jpageheader"> savings product </h1>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jpagecontent">'; 
$displayhtml .= '<div>';
$displayhtml .= '<form class="jform" id="savingsproductsform">';
$displayhtml .= '';
$displayhtml .= '<div class="section-header">';
$displayhtml .= '<h1>Required Fields:</h1>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformcontainer">';
$displayhtml .= '<div class="jformgroup">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label class="jcontrollabel"> Savings Account Product: </label>';
$displayhtml .= '<input placeholder="savings Account Product" type="text"';
$displayhtml .= 'class="jformcontrol jmargin-top" id="productname" name="productname">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="section-header">';
$displayhtml .= '<h1>Savings Account Interest:</h1>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformcontainer">';
$displayhtml .= '<p class="jcontrollabel form-paragraph ">The System will not add the Interest in the past.';
$displayhtml .= 'it will only add interest from the current date. We are assuming when you add a savings';
$displayhtml .= 'account with transactions, you will already be having the interest calculated from ';
$displayhtml .= 'before the transactions will be added. So we do not add interest in the past to avoid ';
$displayhtml .= 'conflict.</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="section-header"></div>';
$displayhtml .= '<div class="col-form-group jmargin-top">';
$displayhtml .= '<div class="jformgroup">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label class="jcontrollabel">interest Rate Per Annum (%):';
$displayhtml .= '</label>';
$displayhtml .= '<input type="text" class="jformcontrol jmargin-top"';
$displayhtml .= 'placeholder="number or decimal only" id="interestrate" name="interestrate">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
$displayhtml .= '<label class="jcontrollabel"> Interest Method: </label>';
$displayhtml .= '<select class="jformcontrol jmargin-top" id="interestmethod" name="interestmethod">';
$displayhtml .= '<option value="last account balance">Latest Account Balance </option>';
$displayhtml .= '<option value="pro-rata basis"> Pro-Rata Basis </option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol" style="align-items:end">';
$displayhtml .= '<button type="button" id="interestmethodhelptoggle"';
$displayhtml .= 'class="j-action-btn float-left jmargin-top"> help </button>';
$displayhtml .= '<div style="display:none; transition:2s"';
$displayhtml .= 'class="hide jcontrollabel form-paragraph jmargin-top" id="interestmethodhelp">Here you';
$displayhtml .= 'can select last savings Account balance or Pro-rata Basis. The last savings Accoount';
$displayhtml .= 'Balance Method will calculate the interest on the last Balance. However Pro-rata Basis';
$displayhtml .= 'will look at the balance for each day and calculate the interest for those days only';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="col-form-group">';
$displayhtml .= '<div class="jformgroup">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label class="jcontrollabel">When should interest be added to savings Account:';
$displayhtml .= '</label>';
$displayhtml .= '<select class="jformcontrol jmargin-top" id="addinterestperiod"';
$displayhtml .= 'name="addinterestperiod"></select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
$displayhtml .= '<label class="jcontrollabel"> Minimum Balance for Interest rate: </label>';
$displayhtml .= '<input type="text" placeholder="0" class="jformcontrol jmargin-top"';
$displayhtml .= 'id="minimumbalanceforinterest" name="minimumbalanceforinterest">';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="section-header">';
$displayhtml .= '<h1>savings Account Withdrawal:</h1>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="col-form-group">';
$displayhtml .= '<div class="jformgroup">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label class="jcontrollabel">Allow savings Account to be overdrawn:';
$displayhtml .= '</label>';
$displayhtml .= '<div class="row-radio select-w-300">';
$displayhtml .= '<label class="jcontrollabel">';
$displayhtml .= '<input type="radio" name="savingsaccountoverdrawn"';
$displayhtml .= 'id="savingsaccountoverdrawnyes" value="yes" checked>';
$displayhtml .= '<span> &nbsp; Yes</span>';
$displayhtml .= '</label>';
$displayhtml .= '<label class="jcontrollabel">';
$displayhtml .= '<input type="radio" name="savingsaccountoverdrawn"';
$displayhtml .= 'id="savingsaccountoverdrawnno" value="no">';
$displayhtml .= '<span> &nbsp; No</span>';
$displayhtml .= '</label>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
$displayhtml .= '<label class="jcontrollabel">Minimum Balance for withdrawal:';
$displayhtml .= '</label>';
$displayhtml .= '<input type="text" class="jformcontrol jmargin-top" placeholder="Numbers only"';
$displayhtml .= 'name="minimumbalanceforwithdrawal" id="minimumbalanceforwithdrawal"></input>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="jformgroup jformgroupcol" style="align-items:end;">';
$displayhtml .= '<div class="jcontrollabel form-paragraph jmargin-top">Leave the above empty if withdrawal';
$displayhtml .= 'should be allowed on any balance. If you type value more than withdrawal transaction';
$displayhtml .= 'will only be allowed if the balance of the savings is more than or equal to the minimum';
$displayhtml .= 'balance above</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="jmargin-top" style="padding-bottom:30px">';
$displayhtml .= '<button type="button" class="j-action-btn-alt jmargin-top float-right"';
$displayhtml .= 'id="accountproductsubmitbtn">save';
$displayhtml .= '</button>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</form>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
echo $displayhtml;
?>