<?php
session_start();

$displayhtml .= '<div class="orecontainer">';
$displayhtml .= '<div class="oresubcontianer">';
$displayhtml .= '<div class="oremainheadercontainer">';
$displayhtml .= '<p class="oremainheader">REGISTER PERSONNEL</p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="orecardcontainer">';
$displayhtml .= '<div class="stcnsection1">';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<p class="oresubheader">Personal Data</p>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">S/N</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsn">';
$displayhtml .= '<p class="normaltext">First Name </p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsn">';
$displayhtml .= '<p class="normaltext">Last Name </p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsn">';
$displayhtml .= '<p class="normaltext">Middle Name </p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">ID No.</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Phone Number</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Work Status</p>';
$displayhtml .= '<select>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">Marital Status</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerln icsn">';
$displayhtml .= '<p class="normaltext">Residential Address</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerln icsn">';
$displayhtml .= '<p class="normaltext">Permanent Home Address</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">Gender</p>';
$displayhtml .= '<select>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">Date of Birth</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">Nationality</p>';
$displayhtml .= '<input type="text" value="NIGERIA">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">State of Origin</p>';
$displayhtml .= '<select>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerln icsn">';
$displayhtml .= '<p class="normaltext">Local Government</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">Work Exp(Years)</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">Any Deformity?</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">Eye Glasses?</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">Hearing Aid?</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">Height</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">Weight</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= "<p class='oresubheader'>Staff's Account</p>";
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Bank</p>';
$displayhtml .= '<select>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Account No.</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Employment Date</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">Group</p>';
$displayhtml .= '<select>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">Level</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerln icsn">';
$displayhtml .= '<p class="normaltext">Department</p>';
$displayhtml .= '<select>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">Office Branch</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Salary Status</p>';
$displayhtml .= '<select>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">User</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcnsection1">';
$displayhtml .= '<div class="stcs1aa bclightred">';
$displayhtml .= '<p class="oresubheader">Salary Submenu</p>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">Basic</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">Benefit</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">Bonus</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext red">Security Fund</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">Net Salary</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcnsection1">';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<p class="oresubheader">Education Background</p>';
$displayhtml .= '<div class="jtable-content">
                    <table class="jmargin-top" id="dueloans">
                        <thead>
                            <tr>
                                <th> School (Name) </th>
                                <th> From (year) </th>
                                <th> To (year)  </th>
                                <th> Qualification  </th>
                            </tr>
                        </thead>
                        <tbody id="leavetabledata">
                            <tr data-open="false" class="source-row-item">
                                <td> mother of the redeemer secondary school </td>
                                <td> 1950 </td>
                                <td> 1990 </td>
                                <td> Olevel </td>
                            </tr>
                            <tr data-open="false" class="source-row-item">
                                <td> mother of the redeemer secondary school </td>
                                <td> 1950 </td>
                                <td> 1990 </td>
                                <td> Olevel </td>
                            </tr>
                            <tr data-open="false" class="source-row-item">
                                <td> mother of the redeemer secondary school </td>
                                <td> 1950 </td>
                                <td> 1990 </td>
                                <td> Olevel </td>
                            </tr>
                        </tbody>
                    </table>
                </div>



';
// $displayhtml .= '<div class="oretableholder">';
// $displayhtml .= '<div class="oretablecontaienr">';
// $displayhtml .= '<div class="oertable">';
// $displayhtml .= '<p>School (Name)</p>';
// $displayhtml .= '<p>From (year)</p>';
// $displayhtml .= '<p>To (year)</p>';
// $displayhtml .= '<p>Qualification</p>';
// $displayhtml .= '</div>';
// $displayhtml .= '<div class="oertable">';
// $displayhtml .= '<input type="text">';
// $displayhtml .= '<input type="text">';
// $displayhtml .= '<input type="text">';
// $displayhtml .= '<select>';
// $displayhtml .= '<option>sfdfsdfdsf</option>';
// $displayhtml .= '<option>sfdfsdfdsf</option>';
// $displayhtml .= '<option>sfdfsdfdsf</option>';
// $displayhtml .= '</select>';
// $displayhtml .= '</div>';
// $displayhtml .= '<div class="oertable">';
// $displayhtml .= '<input type="text">';
// $displayhtml .= '<input type="text">';
// $displayhtml .= '<input type="text">';
// $displayhtml .= '<select>';
// $displayhtml .= '<option>sfdfsdfdsf</option>';
// $displayhtml .= '<option>sfdfsdfdsf</option>';
// $displayhtml .= '<option>sfdfsdfdsf</option>';
// $displayhtml .= '</select>';
// $displayhtml .= '</div>';
// $displayhtml .= '<div class="oertable">';
// $displayhtml .= '<input type="text">';
// $displayhtml .= '<input type="text">';
// $displayhtml .= '<input type="text">';
// $displayhtml .= '<select>';
// $displayhtml .= '<option>sfdfsdfdsf</option>';
// $displayhtml .= '<option>sfdfsdfdsf</option>';
// $displayhtml .= '<option>sfdfsdfdsf</option>';
// $displayhtml .= '</select>';
// $displayhtml .= '</div>';
// $displayhtml .= '</div>';
// $displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<p class="oresubheader">Previous Emplyment</p>';
$displayhtml .= '<div class="oretableholder">';
$displayhtml .= '<div class="oretablecontaienr">';
$displayhtml .= '<div class="oertablee">';
$displayhtml .= '<p>Employer</p>';
$displayhtml .= '<p>Position</p>';
$displayhtml .= '<p>B.salary</p>';
$displayhtml .= '<p>Reason for Leaving</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="oertablee">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<select>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="oertablee">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<select>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="oertablee">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<select>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '<option>sfdfsdfdsf</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcnsection1">';
$displayhtml .= '<div>';
$displayhtml .= "<p class='oresubheader'>Guarantor's File</p>";
$displayhtml .= '<div class="oretablecontaienr">';
$displayhtml .= '<div class="oertable2">';
$displayhtml .= '<p>Names</p>';
$displayhtml .= '<p>Address</p>';
$displayhtml .= '<p>Occupation</p>';
$displayhtml .= '<p>Years known</p>';
$displayhtml .= '<p>Phone Number</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="oertable2">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="oertable2">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="oertable2">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcnsection1">';
$displayhtml .= '<div class="mt">';
$displayhtml .= '<p class="oresubheader">Next of Kin Data</p>';
$displayhtml .= '<div class="orelastrow mt">';
$displayhtml .= '<div class="inputcontainermn icsn">';
$displayhtml .= '<p class="normaltext">First Name</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsn">';
$displayhtml .= '<p class="normaltext">Last Name</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsn">';
$displayhtml .= '<p class="normaltext">Middle Name</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Phone No.</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Relationship</p>';
$displayhtml .= '<select>';
$displayhtml .= '<option>xdfgdfg</option>';
$displayhtml .= '<option>xdfgdfg</option>';
$displayhtml .= '<option>xdfgdfg</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainerln icsn">';
$displayhtml .= '<p class="normaltext">Address</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Occupation</p>';
$displayhtml .= '<select>';
$displayhtml .= '<option>xdfgdfg</option>';
$displayhtml .= '<option>xdfgdfg</option>';
$displayhtml .= '<option>xdfgdfg</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcnsection1">';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<div class="uploadapane">';
$displayhtml .= '<div class="orerbtn">Upload file</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="stcs1a">';
$displayhtml .= '<div class="oresubmitcontainer">';
$displayhtml .= '<div class="orerbtn">Submit</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

echo  $displayhtml;
?>