<?php
session_start();

$displayhtml .= '<div class="orecontainer">';
$displayhtml .= '<div class="oresubcontianer">';
$displayhtml .= '<div class="oremainheadercontainer">';
$displayhtml .= '<p class="oremainheader">STAFF LOAN</p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="orecardcontainer">';
$displayhtml .= '<div class="staffloancontainer">';
$displayhtml .= '<p class="oresubheader">Personal Data</p>';
$displayhtml .= '<div class="inputcontainermn icsn">';
$displayhtml .= '<p class="normaltext">First Name</p>';
$displayhtml .= '<input id="staffloanfirstname" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsn">';
$displayhtml .= '<p class="normaltext">Last Name</p>';
$displayhtml .= '<input id="staffloanlastname" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermn icsn">';
$displayhtml .= '<p class="normaltext">Middle Name</p>';
$displayhtml .= '<input id="staffloanmiddlename" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Branch</p>';
$displayhtml .= '<input id="staffloanbranch" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">Group</p>';
$displayhtml .= '<input id="staffloangroup" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainersn icsn">';
$displayhtml .= '<p class="normaltext">Level</p>';
$displayhtml .= '<input id="staffloanlevel" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Depaartment</p>';
$displayhtml .= '<input id="staffloandepartment" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">User</p>';
$displayhtml .= '<input id="staffloanuser" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Date</p>';
$displayhtml .= '<input id="staffloandate" type="date">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Loan Amount</p>';
$displayhtml .= '<input id="staffloanamount" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Monthly Deduction</p>';
$displayhtml .= '<input id="staffloanmonthlydeduction" type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="oresubmitcontainer">';
$displayhtml .= '<div id="staffloansubmit" class="orerbtn">Submit</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

echo  $displayhtml;
?>