<?php
$displayhtml .= '<div class="jcontainer">';
$displayhtml .= '<div>';
$displayhtml .= '<h1 class="jpageheader"> supplier </h1>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jpagecontent" id="jpagecontent">';
$displayhtml .= '<div>';
$displayhtml .= '<form class="jform" id="supplierform">';
$displayhtml .= '<!-- supplier info -->';
$displayhtml .= '';
$displayhtml .= '<div class="col-form-group">';
$displayhtml .= '<div class="jformgroup">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label class="jcontrollabel"> TYPE: </label>';
$displayhtml .= '<select type="text" class="jformcontrol jmargin-top"';
$displayhtml .= 'id="ttype" name="ttype">';
$displayhtml .= '<option value="" selected=""> -- Select Supplier Type -- </option>';
$displayhtml .= '<option> SUPPLIER </option>';
$displayhtml .= '<option> CUSTOMER </option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="col-form-group">';
$displayhtml .= '<div class="jformgroup">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label class="jcontrollabel"> company name: </label>';
$displayhtml .= '<input type="text" class="jformcontrol jmargin-top"';
$displayhtml .= 'id="companyname" name="companyname">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
$displayhtml .= '<label class="jcontrollabel"> contact person: </label>';
$displayhtml .= '<input type="text" class="jformcontrol jmargin-top"';
$displayhtml .= 'id="contactperson" name="contactperson">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
$displayhtml .= '<label class="jcontrollabel"> phone number: </label>';
$displayhtml .= '<input type="tel" class="jformcontrol jmargin-top"';
$displayhtml .= 'id="phonenumber" name="phonenumber">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label class="jcontrollabel"> office address: </label>';
$displayhtml .= '<input type="text" class="jformcontrol jmargin-top"';
$displayhtml .= 'id="officeaddress" name="officeaddress">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
$displayhtml .= '<label class="jcontrollabel"> nationality: </label>';
$displayhtml .= '<input type="text" class="jformcontrol jmargin-top"';
$displayhtml .= 'id="nationality" name="nationality">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
$displayhtml .= '<label class="jcontrollabel"> state: </label>';
$displayhtml .= '<input type="text" class="jformcontrol jmargin-top"';
$displayhtml .= 'id="state" name="state">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup">';
$displayhtml .= '<div class="jformgroup jformgroupcol">';
$displayhtml .= '<label class="jcontrollabel"> activity level: </label>';
$displayhtml .= '<select type="text" class="jformcontrol jmargin-top"';
$displayhtml .= 'id="typeofsupplier" name="typeofsupplier">';
$displayhtml .= '<option value="" selected=""> -- Select Supplier Type -- </option>';
$displayhtml .= '<option value="ACTIVE"> ACTIVE</option>';
$displayhtml .= '<option value="NON-ACTIVE"> NON-ACTIVE </option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
$displayhtml .= '<label class="jcontrollabel"> bank: </label>';
$displayhtml .= '<input type="text" class="jformcontrol jmargin-top"';
$displayhtml .= 'id="supplierbank" name="supplierbank">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jformgroup jformgroupcol jmargin-left">';
$displayhtml .= '<label class="jcontrollabel"> account number: </label>';
$displayhtml .= '<input type="text" class="jformcontrol jmargin-top"';
$displayhtml .= 'id="supplieraccount" name="supplieraccount">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="jflex jitems-left" style="margin: 30px 0;">';
$displayhtml .= '<div class="jflex jitems-right" style="width: 100%">';
$displayhtml .= '<button type="button" class="j-action-btn" style="min-width: 15%; text-transform: capitalize;  background-color: red;" id="resetsupplierformbtn">';
$displayhtml .= 'reset</button>&nbsp;';
$displayhtml .= '<button type="button" class="j-action-btn"  style="min-width: 15%; text-transform: capitalize" id="savesupplierbtn"> Save Supplier </button>&nbsp;';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="section-header">';
$displayhtml .= '<h1> suppliers </h1>';
$displayhtml .= '</div>';
$displayhtml .= '</form>';
$displayhtml .= '</div>'; 
$displayhtml .= '<div class="jtable-content">';
$displayhtml .= '<table class="jmargin-top" id="approveloanstable">';
$displayhtml .= '<thead>';
$displayhtml .= '<tr>';
$displayhtml .= '<th>s/n </th>';
$displayhtml .= '<th> company&nbsp;name </th>';
$displayhtml .= '<th> type&nbsp;of&nbsp;supplier </th>';
$displayhtml .= '<th> contact&nbsp;person  </th>';
$displayhtml .= '<th> nationality </th>';
$displayhtml .= '<th> state </th>';
$displayhtml .= '<th> address </th>';
$displayhtml .= '<th> phone </th>';
$displayhtml .= '<th> bank </th>';
$displayhtml .= '<th> account </th>';
$displayhtml .= '<th> action </th>';
$displayhtml .= '</tr>';
$displayhtml .= '</thead>';
$displayhtml .= '<tbody id="jtabledata"></tbody>';
$displayhtml .= '</table>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
echo $displayhtml;
?>