<?php
session_start();

$displayhtml .= '<div class="scrollerrcontainer">';
$displayhtml .= '<div id="addinvestorfeecontainer">';
$displayhtml .= '<p class="headercenter">ADD INVESTOR</p>';
$displayhtml .= '';
$displayhtml .= '';
$displayhtml .= '<div class="aifcardcontainer cardshadow">';
$displayhtml .= '<p class="subheader">Required Fields:</p>';
$displayhtml .= '<div class="aifinputcard mt">';
$displayhtml .= '<p class="normaltext tright bold">Country</p>';
$displayhtml .= '<select class="normaltextselect w50" id="">';
$displayhtml .= '<option>Nigeria</option>';
$displayhtml .= '<option>sfsdjfksdjfsdmf</option>';
$displayhtml .= '<option>sfsdjfksdjfsdmf</option>';
$displayhtml .= '<option>sfsdjfksdjfsdmf</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<p class="subheader">Optional Fields:</p>';
$displayhtml .= '<p class="tc aifsmall">All fields are optional, but you must type at least <em>First Name</em> and <em>Middle / Last Name</em> or <em>Business Name</em> </p>';
$displayhtml .= '<div class="aifinputcard">';
$displayhtml .= '<p class="normaltext tright bold">First Name</p>';
$displayhtml .= '<input type="text" placeholder="Enter first name only" class="normaltextselect" name="" id="">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="aifinputcard">';
$displayhtml .= '<p class="normaltext tright bold">Middle / Last Name</p>';
$displayhtml .= '<input type="text" placeholder="Enter middle or last name" class="normaltextselect" name="" id="">';
$displayhtml .= '</div>';
$displayhtml .= '<p class="tc aifsmall"><em>AND/OR</em></p>';
$displayhtml .= '<div class="aifinputcard">';
$displayhtml .= '<p class="normaltext tright bold">Business Name</p>';
$displayhtml .= '<input type="text" placeholder="Enter business name" class="normaltextselect" name="" id="">';
$displayhtml .= '</div>';
$displayhtml .= '<p class="tc aifsmall aiflink">All of the below fields are optional:</p>';
$displayhtml .= '<div class="aifinputcard">';
$displayhtml .= '<p class="normaltext tright bold">Unique Number</p>';
$displayhtml .= '<input type="text" placeholder="1000001" class="normaltextselect" name="" id="">';
$displayhtml .= '</div>';
$displayhtml .= '<p class="tc aifsmall">You can enter unique number to identify the investor such as Social Security Number, License #, Registration Id...</p>';
$displayhtml .= '<div class="aifinputcard">';
$displayhtml .= '<p class="normaltext tright bold">Gender</p>';
$displayhtml .= '<input type="text" class="normaltextselect" name="" id="">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="aifinputcard">';
$displayhtml .= '<p class="normaltext tright bold">Title</p>';
$displayhtml .= '<input type="text" class="normaltextselect" name="" id="">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="aifinputcard">';
$displayhtml .= '<p class="normaltext tright bold">Mobile</p>';
$displayhtml .= '<input type="text" placeholder="Numbers Only" class="normaltextselect" name="" id="">';
$displayhtml .= '</div>';
$displayhtml .= '<p class="tc aifsmall"><em>Do not put country code, space, or characters</em> in mobile otherwise you would not be able to send SMS to this mobile </p>';
$displayhtml .= '<div class="aifinputcard">';
$displayhtml .= '<p class="normaltext tright bold">Email</p>';
$displayhtml .= '<input type="text" placeholder="Email" class="normaltextselect" name="" id="">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="aifinputcard">';
$displayhtml .= '<p class="normaltext tright bold">Date of Birth</p>';
$displayhtml .= '<input type="text" placeholder="dd/mm/yyyy" class="normaltextselect" name="" id="">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="aifinputcard">';
$displayhtml .= '<p class="normaltext tright bold">Address</p>';
$displayhtml .= '<input type="text" placeholder="Address" class="normaltextselect" name="" id="">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="aifinputcard">';
$displayhtml .= '<p class="normaltext tright bold">City</p>';
$displayhtml .= '<input type="text" placeholder="City" class="normaltextselect" name="" id="">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="aifinputcard">';
$displayhtml .= '<p class="normaltext tright bold">Province / State</p>';
$displayhtml .= '<input type="text" placeholder="Province or State" class="normaltextselect" name="" id="">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="aifinputcard">';
$displayhtml .= '<p class="normaltext tright bold">Zipcode</p>';
$displayhtml .= '<input type="text" placeholder="Zipcode" class="normaltextselect" name="" id="">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="aifinputcard">';
$displayhtml .= '<p class="normaltext tright bold">Landline Phone</p>';
$displayhtml .= '<input type="text" placeholder="Landline Phone" class="normaltextselect" name="" id="">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="aifinputcard mt">';
$displayhtml .= '<p class="normaltext tright bold">Working Status</p>';
$displayhtml .= '<select class="normaltextselect w50" id="">';
$displayhtml .= '<option>sfsdjfksdjfsdmf</option>';
$displayhtml .= '<option>sfsdjfksdjfsdmf</option>';
$displayhtml .= '<option>sfsdjfksdjfsdmf</option>';
$displayhtml .= '<option>sfsdjfksdjfsdmf</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="aifinputcard mt">';
$displayhtml .= '<p class="normaltext tright bold">Investor Photo</p>';
$displayhtml .= '<div class="submitbtncontainer2">';
$displayhtml .= '<div class="normaltext">Select Image to Upload</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="aifinputcardm mt">';
$displayhtml .= '<p class="normaltext tright bold">Description</p>';
$displayhtml .= '<textarea name="" id="" cols="30" rows="10"></textarea>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="aifinputcard mt">';
$displayhtml .= '<p class="normaltext tright bold">Investor Files</p>';
$displayhtml .= '<div class="submitbtncontainer2">';
$displayhtml .= '<div class="normaltext">Select Files to Upload</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<p class="tc aifsmaller aiflink">Click here to add custom fields to this page</p>';
$displayhtml .= '';
$displayhtml .= '<div class="submitbtncontainer mt">';
$displayhtml .= '<div class="normaltext">Submit</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';

echo  $displayhtml;
?>