<?php
session_start();
$displayhtml .=  '<div class="formcontainer">';
$displayhtml .=  '<div class="formheader">';
$displayhtml .=  '<h5>UPDATE PROVISION</h5>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formmain">';
$displayhtml .=  '<form action="">';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="selectitem">Select Item</label>';
$displayhtml .=  '<select name="selectitem" id="matselectitem" class="matselectitem">';
$displayhtml .=  '<option  value=""></option>';
$displayhtml .=  '</select>';
$displayhtml .=  '';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<!-- <p class="totallabel">Total</p><br>';
$displayhtml .=  '<p class="showtotal" name="">40000</p> -->';
$displayhtml .=  '';
$displayhtml .=  '<label for="total">Total</label>';
$displayhtml .=  '<input type="number" class="showtotal" disabled>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '';
$displayhtml .=  '<div class="containerone">';
$displayhtml .=  '<div class="selecteditemcontainer">';
$displayhtml .=  '<div class="selecteditemlabel">';
$displayhtml .=  '<div class="split">';
$displayhtml .=  '<span class="descrip" >Description</span>';
$displayhtml .=  '<span class="figures splitt testing ">';
$displayhtml .=  '<span>Quantity</span>';
$displayhtml .=  '<span>Cost</span>';
$displayhtml .=  '<span></span>';
$displayhtml .=  '</span>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="selecteditem " >';
$displayhtml .=  '<!-- <div class="splitt">';
$displayhtml .=  '<span class="descript" >';
$displayhtml .=  '<span class="number">1</span>';
$displayhtml .=  '<span class="description">4kg bags of rice with</span>';
$displayhtml .=  '</span>';
$displayhtml .=  '<span class="figures splitt3">';
$displayhtml .=  '<span id="1">';
$displayhtml .=  '<button class="btn updateminus"><i class="fa-solid fa-minus minus"></i></button>';
$displayhtml .=  '<span class="volume "> 5</span>';
$displayhtml .=  '<button class="btn  updateplus"><i class="fa-solid fa-plus plus"></i></button>';
$displayhtml .=  '</span>';
$displayhtml .=  '<span class="quantitycost">15000</span>';
$displayhtml .=  '<button class="btn btnred">Delete</button>';
$displayhtml .=  '</span>';
$displayhtml .=  '</div> -->';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '';
$displayhtml .=  '';
$displayhtml .=  '<div class="btns btncenter">';
$displayhtml .=  '<button id="matupdatebtn" type="button" class="btnsizetwo btn btnblue ">';
$displayhtml .=  'Update';
$displayhtml .=  '</button>';
$displayhtml .=  '<button type="button" class="btnsizetwo btn btnred">';
$displayhtml .=  'Cancel';
$displayhtml .=  '</button>';
$displayhtml .=  '</div>';
$displayhtml .=  '</form>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';

echo $displayhtml;
?>