<?php
session_start();

$displayhtml .= '<div class="formcontainer">';
$displayhtml .= '<div class="formheader">';
$displayhtml .= '<h5>VIEW DEPOSIT</h5>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="formmain ">';
$displayhtml .= '';
$displayhtml .= '<div class="split5">';
$displayhtml .= '<div class="formcontrol ">';
$displayhtml .= '<label for="branch"> Branch</label>';
$displayhtml .= '<input type="text" name="branch" id="branch" class="branch">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="tselecttransactiondate">Select Transaction Date</label>';
$displayhtml .= '<input type="date" name="tselecttransactiondate" class="tselecttransactiondate" id="tselecttransactiondate">';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="specialflex">';
$displayhtml .= '<div class="wrapbtn"><button class="btn btnblue ">Daily</button></div>';
$displayhtml .= '<div class="formcontrol flexgrow">';
$displayhtml .= '<label for="group">Group</label>';
$displayhtml .= '<input type="text" name="group" class="group" id="group">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="wrapbtn"><button class="btn btnblue  ">Group</button></div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="specialflex">';
$displayhtml .= '<div class="formcontrol flexgrow">';
$displayhtml .= '<label for="depositor">Depositor</label>';
$displayhtml .= '<input type="text" name="depositor" class="depositor" id="depositor">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="wrapbtn"><button class="btn btnblue ">Dep</button></div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '<div class="formcontrol">';
$displayhtml .= '<label for="totaldeposit">Total Deposit </label>';
$displayhtml .= '<input type="number" class="totaldeposit" name="totaldeposit" id="totaldeposit">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '';
$displayhtml .= '<!-- <h5>Total Quantity</h5>';
$displayhtml .= '<span class=" showvalue totalquantity">13494940</span> -->';
$displayhtml .= '';
$displayhtml .= '<div class="generaltableholder">';
$displayhtml .= '<table id="table">';
$displayhtml .= '<tr class="fixedrow">';
$displayhtml .= '<th></th>';
$displayhtml .= '<th>Value Date</th>';
$displayhtml .= '<th>Account No</th>';
$displayhtml .= '<th>Client</th>';
$displayhtml .= '<th>Particulars</th>';
$displayhtml .= '<th>Act Group</th>';
$displayhtml .= '<th>Deposit</th>';
$displayhtml .= '<th>Excess</th>';
$displayhtml .= '</tr>';
$displayhtml .= '';
$displayhtml .= '<!-- <tr>';
$displayhtml .= '<td></td>';
$displayhtml .= '<td></td>';
$displayhtml .= '<td></td>';
$displayhtml .= '<td></td>';
$displayhtml .= '<td></td>';
$displayhtml .= '<td></td>';
$displayhtml .= '<td></td>';
$displayhtml .= '<td></td>';
$displayhtml .= '</tr> -->';
$displayhtml .= '</table>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

echo $displayhtml;
?>
