<?php
$displayhtml .= '<input id="profile-image-upload-input" type="file" hidden=""><div class="organisation-info-container item-types-first-section">';
$displayhtml .= '<div class="organisation-info-first-section">';
$displayhtml .= '<center>';
// $displayhtml .= '<img id="profile-image" class="first-section-image" src="../images/logo.png" alt="logo" width="100" height="100">';
// $displayhtml .= '<svg class="pencil-upload-image" id="profile-img-edit-icon" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="30" height="30" viewBox="0 0 30 30" style=" fill:#000000;">    <path d="M 22.828125 3 C 22.316375 3 21.804562 3.1954375 21.414062 3.5859375 L 19 6 L 24 11 L 26.414062 8.5859375 C 27.195062 7.8049375 27.195062 6.5388125 26.414062 5.7578125 L 24.242188 3.5859375 C 23.851688 3.1954375 23.339875 3 22.828125 3 z M 17 8 L 5.2597656 19.740234 C 5.2597656 19.740234 6.1775313 19.658 6.5195312 20 C 6.8615312 20.342 6.58 22.58 7 23 C 7.42 23.42 9.6438906 23.124359 9.9628906 23.443359 C 10.281891 23.762359 10.259766 24.740234 10.259766 24.740234 L 22 13 L 17 8 z M 4 23 L 3.0566406 25.671875 A 1 1 0 0 0 3 26 A 1 1 0 0 0 4 27 A 1 1 0 0 0 4.328125 26.943359 A 1 1 0 0 0 4.3378906 26.939453 L 4.3632812 26.931641 A 1 1 0 0 0 4.3691406 26.927734 L 7 26 L 5.5 24.5 L 4 23 z"></path></svg>';
$displayhtml .= '<h5>VIEW GROUP - ACCOUNT OFFICERS</h5>';
$displayhtml .= '</center>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="organisation-info-third-section item-type-organisation-info-third-section">';
$displayhtml .= '<form class="organisation-info-form" id="organisation-info-div-basic-info">';
$displayhtml .= '<div class="stock-gift-div stock-return-div organisation-info-div-border-top-left-radius-0 item-types-organisation-info-div">';
$displayhtml .= '<div class="vicol-display-flex-between-gap-1">';
$displayhtml .= '<div>';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-red">Branch</label><br>';
$displayhtml .= '<select class="stock-gift-input-70 vicol-width-100" type="text" name="" id="company-name" required>';
$displayhtml .= '<option value="" selected disabled></option>';
$displayhtml .= '<option value="">Example 1</option>';
$displayhtml .= '<option value="">Example 2</option>';
$displayhtml .= '<option value="">Example 3</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vicol-width-20">';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<div>';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-red">Act Opening Officer</label><br>';
$displayhtml .= '<select class="stock-gift-input-70 vicol-width-100" type="text" name="" id="company-name" required>';
$displayhtml .= '<option value="" selected disabled></option>';
$displayhtml .= '<option value="">Example 1</option>';
$displayhtml .= '<option value="">Example 2</option>';
$displayhtml .= '<option value="">Example 3</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vicol-display-flex-between vicol-width-20">';
$displayhtml .= '<div>';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-red">D</label><br>';
$displayhtml .= '<input type="checkbox">';
$displayhtml .= '</div>';
$displayhtml .= '<div>';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-red">M</label><br>';
$displayhtml .= '<input type="checkbox">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div>';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<div>';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-red">Select Date</label><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-width-90" type="date" name="" id="company-name" required><br>';
$displayhtml .= '</div>';
$displayhtml .= '<div>';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-red"></label><br>';
$displayhtml .= '<input type="checkbox">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vicol-width-15">';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<div class="vicol-width-60">';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-red">Group</label><br>';
$displayhtml .= '<select class="stock-gift-input-70 vicol-width-100" type="text" name="" id="company-name" required>';
$displayhtml .= '<option value="" selected disabled></option>';
$displayhtml .= '<option value="">A</option>';
$displayhtml .= '<option value="">B</option>';
$displayhtml .= '<option value="">C</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vicol-display-flex-between vicol-width-30">';
$displayhtml .= '<div>';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-red">D</label><br>';
$displayhtml .= '<input type="checkbox">';
$displayhtml .= '</div>';
$displayhtml .= '<div>';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-red">M</label><br>';
$displayhtml .= '<input type="checkbox">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vicol-display-flex-between-consumable-property vicol-width-30">';
$displayhtml .= '<div class="vicol-width-50">';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-red">Select Month</label><br>';
$displayhtml .= '<select class="stock-gift-input-70 vicol-width-90" type="text" name="" id="company-name" required>';
$displayhtml .= '<option value="" selected disabled></option>';
$displayhtml .= '<option value="">Example 1</option>';
$displayhtml .= '<option value="">Example 2</option>';
$displayhtml .= '<option value="">Example 3</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vicol-width-50">';
$displayhtml .= '<div class="vicol-display-flex-between">';
$displayhtml .= '<div>';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-red">Year</label><br>';
$displayhtml .= '<select class="stock-gift-input-70 vicol-width-90" type="text" name="" id="company-name" required>';
$displayhtml .= '<option value="" selected disabled></option>';
$displayhtml .= '<option value="">Example 1</option>';
$displayhtml .= '<option value="">Example 2</option>';
$displayhtml .= '<option value="">Example 3</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vicol-display-flex-between vicol-width-30">';
$displayhtml .= '<div>';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-red">D</label><br>';
$displayhtml .= '<input type="checkbox">';
$displayhtml .= '</div>';
$displayhtml .= '<div>';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-red">M</label><br>';
$displayhtml .= '<input type="checkbox">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div>';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-red">Inactive Act Opening Officer</label><br>';
$displayhtml .= '<select class="stock-gift-input-70 vicol-width-90" type="text" name="" id="company-name" required>';
$displayhtml .= '<option value="" selected disabled></option>';
$displayhtml .= '<option value="">Example 1</option>';
$displayhtml .= '<option value="">Example 2</option>';
$displayhtml .= '<option value="">Example 3</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '</div><br>';
$displayhtml .= '</div><br>';



$displayhtml .= '<div class="vicol-width-100 vicol-display-flex-between-start-gap-1">';
$displayhtml .= '<div class="organisation-info-div-sub-container vicol-width-85">';
$displayhtml .= '<div class="vicol-table vicol-width-100">';
$displayhtml .= '<table>';
$displayhtml .= '<thead>';
$displayhtml .= '<tr>';
$displayhtml .= '<th>S/N</th>';
$displayhtml .= '<th>Transaction Date</th>';
$displayhtml .= '<th>Value Date</th>';
$displayhtml .= '<th>Account Officer</th>';
$displayhtml .= '<th>Account Group</th>';
$displayhtml .= '<th>Deposit</th>';
$displayhtml .= '<th>Return Cash</th>';
$displayhtml .= '<th>Excess Cash</th>';
$displayhtml .= '<th>Total Cash</th>';
$displayhtml .= '<th>Number Visited</th>';
$displayhtml .= '<th>Target</th>';
$displayhtml .= '</tr>';
$displayhtml .= '</thead>';
$displayhtml .= '<tbody>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N75000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N100000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '</tr>';
$displayhtml .= '</thead>';
$displayhtml .= '<tbody>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N75000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N100000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '</tr>';
$displayhtml .= '</thead>';
$displayhtml .= '<tbody>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N75000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N100000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '</tr>';
$displayhtml .= '</thead>';
$displayhtml .= '<tbody>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N75000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N100000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '</tr>';
$displayhtml .= '</thead>';
$displayhtml .= '<tbody>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N75000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N100000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '</tr>';
$displayhtml .= '</thead>';
$displayhtml .= '<tbody>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N75000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N100000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '</tr>';
$displayhtml .= '</thead>';
$displayhtml .= '<tbody>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N75000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N100000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '</tr>';
$displayhtml .= '</thead>';
$displayhtml .= '<tbody>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N75000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N100000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '</tr>';
$displayhtml .= '</thead>';
$displayhtml .= '<tbody>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N75000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N100000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '</tr>';
$displayhtml .= '</thead>';
$displayhtml .= '<tbody>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N75000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N100000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '</tr>';
$displayhtml .= '</thead>';
$displayhtml .= '<tbody>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N75000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N100000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '</tr>';
$displayhtml .= '</thead>';
$displayhtml .= '<tbody>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N75000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '<tr>';
$displayhtml .= '<td>1</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>27/01/22</td>';
$displayhtml .= '<td>OKIKIOLA BOY</td>';
$displayhtml .= '<td>A</td>';
$displayhtml .= '<td>N45000.00</td>';
$displayhtml .= '<td>N22000.00</td>';
$displayhtml .= '<td>N10000.00</td>';
$displayhtml .= '<td>N100000.00</td>';
$displayhtml .= '<td>34</td>';
$displayhtml .= '<td>N500000.00</td>';
$displayhtml .= '</tr>';
$displayhtml .= '</tbody>';
$displayhtml .= '</table>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

$displayhtml .= '<div class="vicol-width-15">';
$displayhtml .= '<div class="organisation-info-div-sub-container container-with-before">';
$displayhtml .= '<div>';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-blue">Total Deposit</label><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-width-90" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div>';
$displayhtml .= '<div>';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-blue">Marketers Target</label><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-width-90" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div>';
$displayhtml .= '<div>';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-blue">Branch Target</label><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-width-90" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div>';
$displayhtml .= '<div>';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-blue">Group Target</label><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-width-90" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div>';
$displayhtml .= '<div>';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-blue">Savings Reg</label><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-width-90" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div>';
$displayhtml .= '<div>';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-blue">Property Reg</label><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-width-90" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div>';
$displayhtml .= '<div>';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-blue">Total Reg</label><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-width-90" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div>';
$displayhtml .= '<div>';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-blue">Return Cash</label><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-width-90" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div>';
$displayhtml .= '<div>';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-blue">Excess Cash</label><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-width-90" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div>';
$displayhtml .= '<div>';
$displayhtml .= '<label for="company-name" class="vicol-width-90 vicol-color-blue">Total Visited</label><br>';
$displayhtml .= '<input class="stock-gift-input-70 vicol-width-90" type="text" name="" id="company-name" required><br>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';


$displayhtml .= '</div><br>';
$displayhtml .= '</div>';

$displayhtml .= '<center>';
$displayhtml .= '<h5>ROYALTY</h5><br><br>';
$displayhtml .= '</center>';
$displayhtml .= '</div>';
$displayhtml .= '</form>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

echo  $displayhtml;

?>