<?php
session_start();

$displayhtml .= '<div class="orecontainer">';
$displayhtml .= '<div class="oresubcontianer">';
$displayhtml .= '<div class="oremainheadercontainer">';
$displayhtml .= '<p class="oremainheader">VIEW REGISTRATION SERIAL NUMBER</span></p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="orecardcontainer">';
$displayhtml .= '<div class="vrsncontainer">';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Find by Account Number</p>';
$displayhtml .= '<input type="date">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrsntableheader">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Account Number</p>';
$displayhtml .= '<p>Start Number</p>';
$displayhtml .= '<p>End Number</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrsntablebodycontainer">';
$displayhtml .= '<div class="vrsntablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Account Number</p>';
$displayhtml .= '<p>Start Number</p>';
$displayhtml .= '<p>End Number</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrsntablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Account Number</p>';
$displayhtml .= '<p>Start Number</p>';
$displayhtml .= '<p>End Number</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrsntablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Account Number</p>';
$displayhtml .= '<p>Start Number</p>';
$displayhtml .= '<p>End Number</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrsntablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Account Number</p>';
$displayhtml .= '<p>Start Number</p>';
$displayhtml .= '<p>End Number</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrsntablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Account Number</p>';
$displayhtml .= '<p>Start Number</p>';
$displayhtml .= '<p>End Number</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrsntablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Account Number</p>';
$displayhtml .= '<p>Start Number</p>';
$displayhtml .= '<p>End Number</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrsntablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Account Number</p>';
$displayhtml .= '<p>Start Number</p>';
$displayhtml .= '<p>End Number</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrsntablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Account Number</p>';
$displayhtml .= '<p>Start Number</p>';
$displayhtml .= '<p>End Number</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrsntablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Account Number</p>';
$displayhtml .= '<p>Start Number</p>';
$displayhtml .= '<p>End Number</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrsntablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Account Number</p>';
$displayhtml .= '<p>Start Number</p>';
$displayhtml .= '<p>End Number</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrsntablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Account Number</p>';
$displayhtml .= '<p>Start Number</p>';
$displayhtml .= '<p>End Number</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrsntablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Account Number</p>';
$displayhtml .= '<p>Start Number</p>';
$displayhtml .= '<p>End Number</p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

echo  $displayhtml;
?>