<?php
session_start();

$displayhtml .= '<div class="orecontainer">';
$displayhtml .= '<div class="oresubcontianer">';
$displayhtml .= '<div class="oremainheadercontainer">';
$displayhtml .= '<p class="oremainheader">VIEW LEVEL CHANGE</span></p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="orecardcontainer">';
$displayhtml .= '<div class="vlccontainer">';
$displayhtml .= '<div class="vlctableheader">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>Old Level</p>';
$displayhtml .= '<p>Current Level</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vlctablebodycontainer">';
$displayhtml .= '<div class="vlctablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>Old Level</p>';
$displayhtml .= '<p>Current Level</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vlctablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>Old Level</p>';
$displayhtml .= '<p>Current Level</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vlctablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>Old Level</p>';
$displayhtml .= '<p>Current Level</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vlctablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>Old Level</p>';
$displayhtml .= '<p>Current Level</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vlctablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>Old Level</p>';
$displayhtml .= '<p>Current Level</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vlctablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>Old Level</p>';
$displayhtml .= '<p>Current Level</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vlctablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>Old Level</p>';
$displayhtml .= '<p>Current Level</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vlctablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>Old Level</p>';
$displayhtml .= '<p>Current Level</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vlctablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Staff Names</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>Old Level</p>';
$displayhtml .= '<p>Current Level</p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

echo  $displayhtml;
?>