<?php
session_start();

$displayhtml .= '<div class="orecontainer">';
$displayhtml .= '<div class="oresubcontianer">';
$displayhtml .= '<div class="oremainheadercontainer">';
$displayhtml .= '<p class="oremainheader">VIEW REGISTRATION COUNTER</span></p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="orecardcontainer">';
$displayhtml .= '<div class="vrcrcontainer">';
$displayhtml .= '<div class="inputcontainermsn icsn">';
$displayhtml .= '<p class="normaltext">Select Date</p>';
$displayhtml .= '<input type="date">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrcrtableheader">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Date</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>No. Registered</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrcrtablebodycontainer">';
$displayhtml .= '<div class="vrcrtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Date</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>No. Registered</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrcrtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Date</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>No. Registered</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrcrtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Date</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>No. Registered</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrcrtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Date</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>No. Registered</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrcrtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Date</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>No. Registered</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrcrtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Date</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>No. Registered</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrcrtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Date</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>No. Registered</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrcrtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Date</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>No. Registered</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrcrtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Date</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>No. Registered</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrcrtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Date</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>No. Registered</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrcrtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Date</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>No. Registered</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrcrtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Date</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>No. Registered</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrcrtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Date</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>No. Registered</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vrcrtablebody">';
$displayhtml .= '<p>S/N</p>';
$displayhtml .= '<p>Date</p>';
$displayhtml .= '<p>Branch</p>';
$displayhtml .= '<p>No. Registered</p>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';

echo  $displayhtml;
?>