<?php
session_start();

$displayhtml .= '<html>';
$displayhtml .= '<header>';
$displayhtml .= '<link rel="preconnect" href="https://fonts.googleapis.com">';
$displayhtml .= '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>';
$displayhtml .= '<link href="https://fonts.googleapis.com/css2?family=Josefin+Slab:wght@700&family=Kanit:wght@500&family=Poppins&family=Righteous&display=swap" rel="stylesheet">';
$displayhtml .= '<link rel="stylesheet" type="text/css" href="../style.css">';
$displayhtml .= '</header>';
$displayhtml .= '<body>';
$displayhtml .= '<div id="viewpropertycomission-container">';
$displayhtml .= '<p class="headercenter">CUSTOMER DEPOSIT</p>';
$displayhtml .= '<p class="subheader mc">View Monthly Report</p>';
$displayhtml .= '<div class="viewpropertycomission-subcontainer">';
$displayhtml .= '<div class="vpc-section1 mt">';
$displayhtml .= '<div class="vpcs1">';
$displayhtml .= '<div class="custs3aa">';
$displayhtml .= '<p class="normaltext">Posting Limit</p>';
$displayhtml .= '<select>';
$displayhtml .= '<option>sdfljkfksdjfldsj</option>';
$displayhtml .= '<option>sdfljkfksdjfldsj</option>';
$displayhtml .= '<option>sdfljkfksdjfldsj</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="custs3aa">';
$displayhtml .= '<p class="normaltext">Posting Limit</p>';
$displayhtml .= '<select>';
$displayhtml .= '<option>sdfljkfksdjfldsj</option>';
$displayhtml .= '<option>sdfljkfksdjfldsj</option>';
$displayhtml .= '<option>sdfljkfksdjfldsj</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="custs3aa">';
$displayhtml .= '<p class="normaltext">Posting Limit</p>';
$displayhtml .= '<select>';
$displayhtml .= '<option>sdfljkfksdjfldsj</option>';
$displayhtml .= '<option>sdfljkfksdjfldsj</option>';
$displayhtml .= '<option>sdfljkfksdjfldsj</option>';
$displayhtml .= '</select>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcs1">';
$displayhtml .= '<div class="custs3aa">';
$displayhtml .= '<p class="normaltext">Posting Limit</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="custs3aa">';
$displayhtml .= '<p class="normaltext">Posting Limit</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '<div class="custs3aa">';
$displayhtml .= '<p class="normaltext">Posting Limit</p>';
$displayhtml .= '<input type="text">';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '<div class="vpc-section2 mt">';
$displayhtml .= '<div class="vpcs2header">';
$displayhtml .= '<p class="normaltext">s/n</p>';
$displayhtml .= '<p class="normaltext">Dates</p>';
$displayhtml .= '<p class="normaltext">Branch</p>';
$displayhtml .= '<p class="normaltext">Customer</p>';
$displayhtml .= '<p class="normaltext">Invoice</p>';
$displayhtml .= '<p class="normaltext">Property</p>';
$displayhtml .= '<p class="normaltext">Marketer</p>';
$displayhtml .= '<p class="normaltext">Commission</p>';
$displayhtml .= '<p class="normaltext">Value</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcs2bodycontainer">';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '<div class="vpcbody">';
$displayhtml .= '<p class="normaltext">1</p>';
$displayhtml .= '<p class="normaltext">22/02/2022</p>';
$displayhtml .= '<p class="normaltext">Delta</p>';
$displayhtml .= '<p class="normaltext">Orizma</p>';
$displayhtml .= '<p class="normaltext">23445445</p>';
$displayhtml .= '<p class="normaltext">Mansion</p>';
$displayhtml .= '<p class="normaltext">OIM</p>';
$displayhtml .= '<p class="normaltext">2,000,000.00</p>';
$displayhtml .= '<p class="normaltext">99,000,000.00</p>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '</div>';
$displayhtml .= '<script type="text/javascript" src="./accountregistration.JS"></script>';
$displayhtml .= '</body>';
$displayhtml .= '</html>';

echo $displayhtml
?>