<?php
session_start();

$displayhtml .=   '<div class="formcontainer overflowcontainer">';
$displayhtml .=   '<div class="formheader">';
$displayhtml .=   '<h5>WAREHOUSE SALES</h5>';
$displayhtml .=   '</div>';
$displayhtml .=   '<div class="formmain">';
$displayhtml .=   '<div class="top ">';
$displayhtml .=   '<div class="split">';
$displayhtml .=   '<div class="formsection">';
$displayhtml .=   '<p class="topformsection">Enter Account Number</p>';
$displayhtml .=   '<div class="formcontrol">';
$displayhtml .=   '<label for="accountname"></label><br>';
$displayhtml .=   '<input type="number" class="accountn" id="mataccountnumber">';
$displayhtml .=   '</div>';
$displayhtml .=   '</div>';
$displayhtml .=   '<div class="split">';
$displayhtml .=   '<div class="formsection">';
$displayhtml .=   '<p class="topformsection">Choose Payment Mode to Activate Page</p><br>';
$displayhtml .=   '<div class="formcontrolradiobtn">';
$displayhtml .=   '<label class="container">Cash Payment';
$displayhtml .=   '<input type="radio" name="radio">';
$displayhtml .=   '<span class="checkmark"></span>';
$displayhtml .=   '</label>';
$displayhtml .=   '<label class="container">Bank Payment';
$displayhtml .=   '<input type="radio" name="radio">';
$displayhtml .=   '<span class="checkmark"></span>';
$displayhtml .=   '</label>';
$displayhtml .=   '</div>';
$displayhtml .=   '</div>';
$displayhtml .=   '';
$displayhtml .=   '<div class="formsection">';
$displayhtml .=   '<p class="topformsection">Treansaction Date</p><br>';
$displayhtml .=   '<div class="formcontrol">';
$displayhtml .=   '<input type="date" name="transactiondate" id="mattransactiondate">';
$displayhtml .=   '</div>';
$displayhtml .=   '</div>';
$displayhtml .=   '</div>';
$displayhtml .=   '</div>';
$displayhtml .=   '</div>';
$displayhtml .=   '';
$displayhtml .=   '<section class="split">';
$displayhtml .=   '<div class="">';
$displayhtml .=   '<div class="wrapper formsection">';
$displayhtml .=   '<p class="topformsection">DEPOSITOR PROFILE</p>';
$displayhtml .=   '<div class="split">';
$displayhtml .=   '<div class="formcontrol">';
$displayhtml .=   '<label for="firstname">First Name</label>';
$displayhtml .=   '<input type="text" class="firstname" id="firstname" name="matdepfirstname">';
$displayhtml .=   '</div>';
$displayhtml .=   '<div class="formcontrol">';
$displayhtml .=   '<label for="lastname">Last Name</label>';
$displayhtml .=   '<input type="text" class="lastname" id="lastname" name="matdeplastname">';
$displayhtml .=   '</div>';
$displayhtml .=   '</div>';
$displayhtml .=   '<div class="split">';
$displayhtml .=   '<div class="formcontrol">';
$displayhtml .=   '<label for="mobilenumber">Mobile Number</label>';
$displayhtml .=   '<input type="number" name="mobilenumber" id="matdepmobilenumber">';
$displayhtml .=   '</div>';
$displayhtml .=   '<div class="formcontrol">';
$displayhtml .=   '<label for="accountgroup">Account Group</label>';
$displayhtml .=   '<select name="accountgroup" id="matdepaccountgroup">';
$displayhtml .=   '<option value=""></option>';
$displayhtml .=   '</select>';
$displayhtml .=   '';
$displayhtml .=   '';
$displayhtml .=   '</div>';
$displayhtml .=   '';
$displayhtml .=   '</div>';
$displayhtml .=   '<div class="split">';
$displayhtml .=   '';
$displayhtml .=   '<div class="formcontrol">';
$displayhtml .=   '<label for="expirydate">Expiry Date</label>';
$displayhtml .=   '<input type="date" class="expirydate" id="expirydate" itemid="matdepexpirydate">';
$displayhtml .=   '</div>';
$displayhtml .=   '<div class="formcontrol">';
$displayhtml .=   '<label for="penalty">Penalty</label>';
$displayhtml .=   '<input type="text" class="penalty" id="matdeppenalty" itemid="penalty">';
$displayhtml .=   '</div>';
$displayhtml .=   '';
$displayhtml .=   '';
$displayhtml .=   '</div>';
$displayhtml .=   '<div class="split3">';
$displayhtml .=   '';
$displayhtml .=   '<div class="formcontrol">';
$displayhtml .=   '<label for="onlineuser">Online User</label>';
$displayhtml .=   '<input type="text" class="onlineuser" id="matdeponlineuser" itemid="onlineuser">';
$displayhtml .=   '</div>';
$displayhtml .=   '<div class="formcontrol">';
$displayhtml .=   '<label for="transactionpoint">Transaction Point</label>';
$displayhtml .=   '<input type="transactionpoint" name="transactionpoint" id="matdeptransactionpoint">';
$displayhtml .=   '</div>';
$displayhtml .=   '<div class="formcontrol">';
$displayhtml .=   '<label for="product">Product</label>';
$displayhtml .=   '<input type="text" class="product" id="matdepproduct" name="product">';
$displayhtml .=   '</div>';
$displayhtml .=   '</div>';
$displayhtml .=   '<div class="split">';
$displayhtml .=   '<div class="formcontrol">';
$displayhtml .=   '<label for="amountpatable">Amount Payable</label>';
$displayhtml .=   '<input type="number" class="amountpayable" id="matdepamountpayable" name="amountpayable">';
$displayhtml .=   '</div>';
$displayhtml .=   '<div class="formcontrol">';
$displayhtml .=   '<label for="balance">Balance</label>';
$displayhtml .=   '<input type="number" class="balance" id="matdepbalance" name="balance">';
$displayhtml .=   '</div>';
$displayhtml .=   '</div>';
$displayhtml .=   '</div>';
$displayhtml .=   '';
$displayhtml .=   '<div class="wrapper formsection">';
$displayhtml .=   '<p class="topformsection">ITEM DETAILS</p>';
$displayhtml .=   '<div class="">';
$displayhtml .=   '<div class="split3">';
$displayhtml .=   '<div class="formcontrol">';
$displayhtml .=   '<label for="type">Type</label>';
$displayhtml .=   '<input type="text" name="type" id="matitemtype" class="type">';
$displayhtml .=   '</div>';
$displayhtml .=   '';
$displayhtml .=   '<div class="formcontrol">';
$displayhtml .=   '<label for="Model">Model</label>';
$displayhtml .=   '<input type="text" name="model" id="matitemmodel" class="model">';
$displayhtml .=   '</div>';
$displayhtml .=   '';
$displayhtml .=   '<div class="formcontrol">';
$displayhtml .=   '<label for="stockbalance">Stock Balance</label>';
$displayhtml .=   '<input type="text" name="stockbalance" id="matitemstockbalance" class="stockbalance">';
$displayhtml .=   '</div>';
$displayhtml .=   '</div>';
$displayhtml .=   '</div>';
$displayhtml .=   '';
$displayhtml .=   '</div>';
$displayhtml .=   '</div>';
$displayhtml .=   '';
$displayhtml .=   '<div class="wrapper formsection">';
$displayhtml .=   '<p class="topformsection">PROPERTY SLOTS</p>';
$displayhtml .=   '';
$displayhtml .=   '<!-- <div class="generaltableholder"> -->';
$displayhtml .=   '<div class="warehousegridcontainer matgridcontainer">';
$displayhtml .=   '<div class="first "><p>S/N</p></div>';
$displayhtml .=   '<div class="second "><p>Product</p></div>';
$displayhtml .=   '<div class="third"><p>Description</p></div>';
$displayhtml .=   '</div>';
$displayhtml .=   '';
$displayhtml .=   '<div class="warehousegridcontainer matgridcontainer">';
$displayhtml .=   '<div class="first "><input type="text"></div>';
$displayhtml .=   '<div class="second "><input type="text"></div>';
$displayhtml .=   '<div class="third"><input type="text"></div>';
$displayhtml .=   '</div>';
$displayhtml .=   '<div class="warehousegridcontainer matgridcontainer">';
$displayhtml .=   '<div class="first "><input type="text"></div>';
$displayhtml .=   '<div class="second "><input type="text"></div>';
$displayhtml .=   '<div class="third"><input type="text"></div>';
$displayhtml .=   '</div>';
$displayhtml .=   '';
$displayhtml .=   '<div class="warehousegridcontainer matgridcontainer">';
$displayhtml .=   '<div class="first "><input type="text"></div>';
$displayhtml .=   '<div class="second "><input type="text"></div>';
$displayhtml .=   '<div class="third"><input type="text"></div>';
$displayhtml .=   '</div>';
$displayhtml .=   '<div class="warehousegridcontainer matgridcontainer ">';
$displayhtml .=   '<div class="first "><input type="text"></div>';
$displayhtml .=   '<div class="second "><input type="text"></div>';
$displayhtml .=   '<div class="third"><input type="text"></div>';
$displayhtml .=   '</div>';
$displayhtml .=   '<div class="warehousegridcontainer matgridcontainer">';
$displayhtml .=   '<div class="first "><input type="text"></div>';
$displayhtml .=   '<div class="second "><input type="text"></div>';
$displayhtml .=   '<div class="third"><input type="text"></div>';
$displayhtml .=   '</div>';
$displayhtml .=   '<div class="warehousegridcontainer matgridcontainer">';
$displayhtml .=   '<div class="first "><input type="text"></div>';
$displayhtml .=   '<div class="second "><input type="text"></div>';
$displayhtml .=   '<div class="third"><input type="text"></div>';
$displayhtml .=   '</div>';
$displayhtml .=   '<div class="warehousegridcontainer matgridcontainer">';
$displayhtml .=   '<div class="first "><input type="text"></div>';
$displayhtml .=   '<div class="second "><input type="text"></div>';
$displayhtml .=   '<div class="third"><input type="text"></div>';
$displayhtml .=   '</div>';
$displayhtml .=   '<div class="warehousegridcontainer matgridcontainer">';
$displayhtml .=   '<div class="first "><input type="text"></div>';
$displayhtml .=   '<div class="second "><input type="text"></div>';
$displayhtml .=   '<div class="third"><input type="text"></div>';
$displayhtml .=   '</div>';
$displayhtml .=   '<div class="warehousegridcontainer matgridcontainer">';
$displayhtml .=   '<div class="first "><input type="text"></div>';
$displayhtml .=   '<div class="second "><input type="text"></div>';
$displayhtml .=   '<div class="third"><input type="text"></div>';
$displayhtml .=   '</div>';
$displayhtml .=   '<div class="warehousegridcontainer matgridcontainer">';
$displayhtml .=   '<div class="first "><input type="text"></div>';
$displayhtml .=   '<div class="second "><input type="text"></div>';
$displayhtml .=   '<div class="third"><input type="text"></div>';
$displayhtml .=   '</div>';
$displayhtml .=   '<div class="warehousegridcontainer matgridcontainer">';
$displayhtml .=   '<div class="first "><input type="text"></div>';
$displayhtml .=   '<div class="second "><input type="text"></div>';
$displayhtml .=   '<div class="third"><input type="text"></div>';
$displayhtml .=   '</div>';
$displayhtml .=   '<div class="warehousegridcontainer matgridcontainer">';
$displayhtml .=   '<div class="first "><input type="text"></div>';
$displayhtml .=   '<div class="second "><input type="text"></div>';
$displayhtml .=   '<div class="third"><input type="text"></div>';
$displayhtml .=   '</div>';
$displayhtml .=   '';
$displayhtml .=   '';
$displayhtml .=   '<div class="split3">';
$displayhtml .=   '<div class="formcontrol">';
$displayhtml .=   '<label for="invoiceno">Invoice No</label>';
$displayhtml .=   '<input type="number" name="invoiceno" class="invoiceno" id="matinvoiceno">';
$displayhtml .=   '</div>';
$displayhtml .=   '';
$displayhtml .=   '<div class="formcontrol">';
$displayhtml .=   '<label for="totalcost">Total cost</label>';
$displayhtml .=   '<input type="number" name="totalcost" class="totalcost" id="mattotalcost">';
$displayhtml .=   '</div>';
$displayhtml .=   '';
$displayhtml .=   '<div class="formcontrol">';
$displayhtml .=   '<label for="servicecharge">Service Charge</label>';
$displayhtml .=   '<input type="number" name="servicecharge" class="servicecharge" id="matservicecharge">';
$displayhtml .=   '</div>';
$displayhtml .=   '';
$displayhtml .=   '';
$displayhtml .=   '</div>';
$displayhtml .=   '<!-- </div> -->';
$displayhtml .=   '</div>';
$displayhtml .=   '</section>';
$displayhtml .=   '';
$displayhtml .=   '<div class="btns btncenter">';
$displayhtml .=   '';
$displayhtml .=   '<button type="submit" class="btnsizetwo btn btnblue">';
$displayhtml .=   'Update';
$displayhtml .=   '</button>';
$displayhtml .=   '<button type="submit" class="btnsizetwo btn btnred">';
$displayhtml .=   'Cancel';
$displayhtml .=   '</button>';
$displayhtml .=   '';
$displayhtml .=   '</div>';
$displayhtml .=   '</div>';
$displayhtml .=   '';
$displayhtml .=   '</div>';

echo $displayhtml;
?>
