<?php
session_start();

$displayhtml .=  '<div class="formcontainer">';
$displayhtml .=  '<div class="formheader">';
$displayhtml .=  '<h5>WITHDRAWAL VIEW BALANCE</h5>';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formmain ">';
$displayhtml .=  '<div class="split4">';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="branch">Branch</label>';
$displayhtml .=  '<input type="text" name="branch" class="" id="branch">';
$displayhtml .=  '</div>';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="selectdate">Select Date</label>';
$displayhtml .=  '<input type="date" name="selectdate" class="selectdate" id="selectdate">';
$displayhtml .=  '</div>';
$displayhtml .=  '';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="totaldebt">Total Debt</label>';
$displayhtml .=  '<input type="number" name="totaldebt" id="totaldebt" class="totaldebt">';
$displayhtml .=  '</div>';
$displayhtml .=  '';
$displayhtml .=  '<div class="formcontrol">';
$displayhtml .=  '<label for="selectmonth">Select Month</label>';
$displayhtml .=  '<select name="selectmonth" id="selectmonth">';
$displayhtml .=  '<option value=""></option>';
$displayhtml .=  '</select>';
$displayhtml .=  '</div>';
$displayhtml .=  '';
$displayhtml .=  '';
$displayhtml .=  '</div>';
$displayhtml .=  '';
$displayhtml .=  '<div class="generaltableholder">';
$displayhtml .=  '<table id="table">';
$displayhtml .=  '<tr class="fixedrow">';
$displayhtml .=  '<th></th>';
$displayhtml .=  '<th>Particulars</th>';
$displayhtml .=  '<th>Account User</th>';
$displayhtml .=  '<th>Account Group</th>';
$displayhtml .=  '<th>Bank</th>';
$displayhtml .=  '<th>Bank Account No</th>';
$displayhtml .=  '<th>Withdrawal</th>';
$displayhtml .=  '';
$displayhtml .=  '</tr>';
$displayhtml .=  '';
$displayhtml .=  '<!-- <tr>';
$displayhtml .=  '<td></td>';
$displayhtml .=  '<td></td>';
$displayhtml .=  '<td></td>';
$displayhtml .=  '<td></td>';
$displayhtml .=  '<td></td>';
$displayhtml .=  '<td></td>';
$displayhtml .=  '<td></td>';
$displayhtml .=  '</tr> -->';
$displayhtml .=  '</table>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '</div>';
$displayhtml .=  '';

echo $displayhtml;
?>